### ISSUE TITLE
ReadMe update?

### ISSUE THREAD

**Issue by GuardRex** [Microsoft/DockerTools#10]
> The tooling requires installing Docker For Windows separately from Visual Studio.

Should the ReadMe be updated? ... I was informed that VS2017 now installs the Docker runtime with .NET Core workload install.

**Comment by dbreshears** [comment]
No.  Docker for Windows is still a separate download from the Docker web site.  The Visual Studio tooling for Docker is the only thing in VS2017.   On VS 2015, this was an install from the VS gallery.

**Comment by GuardRex** [comment]
Thanks ... I perhaps misunderstood the info that I received. Thanks again.
