### ISSUE TITLE
How to stop VS2017 preparing the docker images?

### ISSUE THREAD

**Issue by SeriousM** [Microsoft/DockerTools#100]
I use VS2017 (15.7) with Win10 (1803) and Docker (18.03).  
My solution contains a Docker-Project (dcproj) which defines how my docker container should start.

Whenever I open Visual Studio or change code it automatically starts preparing the container.

```========== Preparing Containers ==========
Getting Docker containers ready...
<snip>
Step 1/4 : FROM microsoft/aspnet:4.7.1-windowsservercore-1709
<snip>
Successfully built cbde0ec28022
<snip>
Done!  Docker containers are ready.```

How can I stop that behavior? It eats up the performance of my laptop!
When I want to start the container I would start, but building all the time is too much.

Is there a setting for this?

**Comment by dbreshears** [comment]
Yes.  Look under the following options 

  Tools->Options menu   and then Container Tools->Settings

**Comment by SeriousM** [comment]
Oh thank you, I was just blind I guess... was searching for Docker settings :/
