### ISSUE TITLE
Remote Debugging a container using a Transparent Network Driver

### ISSUE THREAD

**Issue by jmeberst** [Microsoft/DockerTools#101]
I'm trying to debug my application running on a container that I've set to use a transparent network driver.
I'm getting an error because the remote debugger doesn't know how to find the container.

What should I change in the compose file(s) to properly expose the container to the debugger?

> Unable to start debugging The debugger cannot connect to the remote computer.

My docker-compose.override.yml

```version: '3'
networks:
  default:
    external:
         name: <transparent_network_name>
```

**Comment by jmeberst** [comment]
Just to provide an update, it seems like if I expose port 4022, the debugger is able to occasionally connect to the container. I can also attach the debugger after I start the process in the container through PowerShell and it has no issues.

It seems like the process times out just before the container can start the process to be debugged.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
