### ISSUE TITLE
docker not working with visual studio for Mac - Visual Studio version 7.5.2

### ISSUE THREAD

**Issue by mdonogma** [Microsoft/DockerTools#109]
Docker tools not working with latest visual studio for Mac. version 7.5.2 

Create new mvc .net core project
added docker support
set docker project as startup
run
(attached copy of solution)
[newnetcoremvc.zip](https://github.com/Microsoft/DockerTools/files/2091798/newnetcoremvc.zip)

error
/Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(7,7): Error MSB4057: The target "DockerPrepareForBuild" does not exist in the project. (MSB4057) (docker-compose)

**Comment by dbreshears** [comment]
Thanks for the report.  We will investigate

**Comment by arroyc** [comment]
@mdonogma, Can you please let us know which .net core version you are using while creating the project? Is it .net core 2.1 or 2.0?

**Comment by mdonogma** [comment]
It shouldn’t matter as docker supports both.

The dockerfile in the attached solution should have the version

Sent from Outlook
________________________________

**Comment by mdonogma** [comment]
What is interesting is the same project works with docker on a windows machine. So looks like an issue with dockertools with vs for Mac

Sent from Outlook
________________________________

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
