### ISSUE TITLE
BuildNumber as argument in Dockerfile

### ISSUE THREAD

**Issue by cilerler** [microsoft/DockerTools#111]
I would like to add build number in Dockerfile and want to make sure that it will be supported by DockerTools.  What would be the best practice?

## *.csproj
```xml
  <PropertyGroup>
    <BuildNumber Condition=" '$(BuildNumber)' == '' ">0.0.0</BuildNumber>
    <VersionPrefix>$(BuildNumber)</VersionPrefix>
    <VersionSuffix Condition=" '$(Configuration)' == 'Debug' ">dev</VersionSuffix>
  </PropertyGroup>
```

## Dockerfile
```yaml
# ...
RUN dotnet build MyProject.csproj -c Release -o /app /p:BuildNumber=$BuildNumber
# ...
RUN dotnet publish MyProject.csproj -c Release -o /app /p:BuildNumber=$BuildNumber
# ...
```

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!

**Comment by cilerler** [comment]
I appreciate if you may open it back since I'm still hoping for a response... 😇 Thanks in advance

**Comment by bwateratmsft** [comment]
Hey @cilerler , I'm sorry this wasn't looked at earlier. For this you wouldn't need a build number in the Dockerfile. The "dotnet build" takes that csproj, so it would include any properties in it already, including the build number. No changes should be needed to the dockerfile.

**Comment by cilerler** [comment]
@bwateratmsft thanks for the reply.  Unfortunately it sets to `0.0.0` instead of the number I would like to provide.

**Comment by bwateratmsft** [comment]
@cilerler , where does the true value itself come from? It seems like this should work with the default-scaffolded "dotnet build" (i.e., without having /p:BuildNumber) command in the Dockerfile, as long as an actual value can be obtained either from the .csproj or an accessible .props file.

**Comment by cilerler** [comment]
it can not. Consider a build system _(such as VSTS or lets call it SuperCI for the sake of not talking about how VSTS works)_ has a special way to generate a special number that needs to be set as build number.  It is not known at development time, it is at build time on a CI server and no developer involves. Project file knows how to applied it IF it is provided as an argument. If that parameter will not be received as `dotnet *` argument the value will be `0.0.0` meaning it is a development build.

**Comment by bwateratmsft** [comment]
That makes sense, since VSTS/others would set it as an environment variable, but that variable isn't inherently available in the Docker container.  I'll reopen this issue and we can examine it as a possible enhancement.

**Comment by NCarlsonMSFT** [comment]
To expose an MSBuild property like BuildNumber to your Dockerfile I recommend using [Build arguments](https://docs.docker.com/build/guide/build-args/).

You can add
```Dockerfile
ARG BuildNumber=0.0.0
```
to your Dockerfile to define the argument and
```xml
  <PropertyGroup>
    <DockerfileBuildArguments>--build-arg BuildNumber=$(BuildNumber)</DockerfileBuildArguments>
  </PropertyGroup>
```
to your project file to pass the msbuild property's value to the docker build argument.
