### ISSUE TITLE
Debugger instability when inspecting a DynamicProxy type with high field count

### ISSUE THREAD

**Issue by tsangste** [Microsoft/DockerTools#113]
When using EFCore 2.1 with lazy loading(https://github.com/aspnet/EntityFrameworkCore/issues/10509) and debugging in docker it causes the debugger to become unstable when trying to evaluate/inspect a DynamicProxy type. But when debugging without docker and evaluating/inspecting a DynamicProxy type it seems to work fine.

I am using Visual Studio 2017 15.7.3 and docker-ce 18.03.1.

**Comment by tsangste** [comment]
After some extra investigation it seems that small entities are less prone to this problem and as a entity because larger (i.e. more fields) it seems to increase the waiting time to evaluate/inspect the DynamicProxy type.

The entity that is failing to load has around 100 fields but potentially more as it has an inheritance structure.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
