### ISSUE TITLE
Cleans don't delete contents of <application project folder>\obj\Docker\publish

### ISSUE THREAD

**Issue by sadegr** [Microsoft/DockerTools#114]
Release builds in Visual Studio of projects with Docker support cause the build output files to be copied to obj\Docker\publish (relative to the application project folder) in certain scenarios (this happens when Docker support is added to a new .NET Framework console application, for example, but not with .NET Core console applications). One project type in which this happens is a default .NET framework 4.7.2 console application to which Docker support has been added, with no other changes.

However, running a clean (in Release mode) in Visual Studio of the docker-compose project (.dcproj), the application project, or the solution containing the docker-compose project (.dcproj) and application project, does not cause the contents of obj\Docker\publish to get deleted, while the contents of bin\Release **do** get deleted.

Visual Studio version: Enterprise 2017 (15.7.3)
Docker version: 18.03.1-ce, build 9ee9f40
OS: Windows 10 Enterprise 10.0.16299

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
