### ISSUE TITLE
Support deploying services to swarm from Visual Studio

### ISSUE THREAD

**Issue by sadegr** [Microsoft/DockerTools#115]
This is a feature request, not a bug report. With the Docker Engine on the host running in swarm mode, when building or debugging a docker-compose project (.dcproj), Visual Studio runs `docker-compose` commands to deploy the services defined in the docker-compose.yml file(s).

A message will appear in the Docker output window after Visual Studio calls `docker-compose up`:
```
The Docker Engine you're using is running in swarm mode.
Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.
```

There is no way at this time to force Visual Studio to run `docker stack` commands (instead of `docker-compose` commands) to deploy the services defined in the docker-compose.yml file(s) to a swarm instead of the local node.

The [documentation](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow) notes:
> The docker-compose up and docker run commands (or running and debugging the containers in Visual Studio) are adequate for testing containers in your development environment. But you should not use this approach if you are targeting Docker clusters and orchestrators like Docker Swarm, Mesosphere DC/OS, or Kubernetes. If you are using a cluster like Docker Swarm mode (available in Docker CE for Windows and Mac since version 1.12), you need to deploy and test with additional commands like docker service create for single services. If you are deploying an application composed of several containers, you use docker compose bundle and docker deploy myBundleFile to deploy the composed application as a stack. For more information, see the blog post Introducing Experimental Distributed Application Bundles in the Docker documentation. on the Docker site.

As mentioned, distributed application bundles are an experimental Docker feature; using `docker stack deploy` to deploy services defined in a stackfile, on the other hand, is a mainstream Docker feature. It would be nice if we could select a "deploy mode" setting (one of either "compose" or "stack"/"swarm") in the docker-compose project's Property Pages which would determine which set of commands (`docker-compose` or `docker stack`, respectively) Visual Studio runs when building or debugging the docker-compose project. There are a number of things that may work differently between services deployed in Swarm mode vs. regular "compose" mode, and the only workaround for debugging services deployed in Swarm mode is using the Docker CLI directly to deploy a stack to a swarm and then manually attaching Visual Studio to the remote debugger running in the container using Debug > Attach to Process... in Visual Studio.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!

**Comment by Ankurkh1** [comment]
This seem like logical thing to do as there are a few docker features which only work in swarm mode e.g. secrets and config. 
Having an option of deploying to single node swarm cluster will make debugging experience pretty smooth.
Please consider this!!!

**Comment by PavelSosin-320** [comment]
> This seem like logical thing to do as there are a few docker features which only work in swarm mode e.g. secrets and config.
> Having an option of deploying to single node swarm cluster will make debugging experience pretty smooth.
> Please consider this!!!

There are more than a few features which work in the swarm Entire Docker ioT area is based on heterogeneous swarm: Windows master node + ARM worker nodes. I's exist already a few years. Also local and proxy Docker registries require SWARM ! It takes exactly one minute to install on the laptop and manage personal images:
`C:\Windows\System32>docker service create --name=localregistry --replicas 1 --network=bridge --constraint node.role==manager  -p 5000:5000 --name localregistry registry:2
ok5djrmbawufdodi54rcsjpzv
overall progress: 1 out of 1 tasks
1/1: running   [==================================================>]
verify: Service converged`

**Comment by davhdavh** [comment]
This would also make it much much easier to test deployment issues locally, not to mention make it much more stable to use mixed OS setups
