### ISSUE TITLE
Can't add new folder to docker-compose project

### ISSUE THREAD

**Issue by sadegr** [microsoft/DockerTools#118]
When I right-click on the docker-compose project (.dcproj) icon in the Solution Explorer and select Add > New Folder, the project's title becomes editable, and no new folder gets created in the project. A new folder named "New Folder" will get created in the solution folder, but it won't be added to the project.

**Comment by evilroxx** [comment]
same

**Comment by haniamr** [comment]
This issue is fixed as of Visual Studio 16.3 and above.
