### ISSUE TITLE
docker-compose project failed on build without giving any reasons

### ISSUE THREAD

**Issue by artem-leonov** [Microsoft/DockerTools#120]
I have an issue with building docker-compose project. It just starting to fails on build after a while. In build log no information, but "Done building project "docker-compose.dcproj" -- FAILED.", no messages more about this error. Docker log has no errors too. 
Last time I restored Visual Studio and it resolved issue on short time. I have Visual Studio 15.7.4 and Docker for Windows 18.03.1-ce-win65 (17513).

**Comment by artem-leonov** [comment]
This time restoring of Visual Studio had no effect.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
