### ISSUE TITLE
Multiple docker-compose.yml files

### ISSUE THREAD

**Issue by belchevgb** [Microsoft/DockerTools#121]
Hi all, I have 2 issues.
The first one: I want to have multiple custom named docker-compose files in the .dcproj, for example:
`<ItemGroup>
    <None Include="dev.env" />
    <None Include="docker-compose.first.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.second.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.third.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
  </ItemGroup>`

and this should run: docker-compose -f docker-compose.yml -f docker-compose.first.yml -f docker-compose.second.yml -f docker-compose.third.yml up

The second one: If I have docker-compose.yml in not the same folder as docker-compose.dcproj, the tool can't resolve it. Example:

`<None Include="docker-compose.override.yml">
      <DependentUpon>../docker-compose.yml</DependentUpon>
</None>`

I need to have two or more dcproj files which share one main docker-compose.yml file.
Maybe I'm not doing everything right. If those issues are by design, do you plan for future support.
Thanks.

**Comment by steveoh** [comment]
I've noticed that visual studio will run docker-compose.yml docker-compose.override.yml which is a docker compose convention. They also tack on some stuff from the obj folder. I think your request is still valid. I would like to see docker compose files be configurable per build configuration so debug and release targets can modify the resulting containers.

**Comment by belchevgb** [comment]
Well for the build configurations I've tried to add to the .dcproj docker-compose.vs.debug.yml and it works. I think the same works for  docker-compose.vs.prod.yml but again is strict convention. I think it should be better if the tool uses a pattern for matching compose files like "docker-compose.*.yml".

**Comment by paulostradioti** [comment]
I'm also having this problem. Did anyone find a workaround?

Thank you

**Comment by tomkerkhove** [comment]
This is a big problem, at least we should be able to rename `docker-compose.yml` to something we like or makes more sense and not hardcode this.

Would be great to have this fixed.

**Comment by joetherod** [comment]
seems to working in 15.9

**Comment by haniamr** [comment]
thanks @joetherod for the confirmation!

**Comment by SychevIgor** [comment]
@haniamr so, as I understood- there is no plans to add mentioned improvements to vs2017, right?
agree, dev should use the latest/greatest tools, but there are 2 problems. licencing and vs2019 not yet GA.
