### ISSUE TITLE
Add support for Azure Functions

### ISSUE THREAD

**Issue by NickDarvey** [microsoft/DockerTools#124]
@jeffhollan [said](https://docs.microsoft.com/en-us/azure/vs-azure-tools-docker-edit-and-refresh) that this is your problem. Can we get support for development of Azure Functions in much the same way we can do [ASP.NET Core development](https://docs.microsoft.com/en-us/azure/vs-azure-tools-docker-edit-and-refresh)? Refresh-and-continue and everything?

**Comment by haniamr** [comment]
Thanks for pointing that out, it is definitely under consideration but there isn't a specific date for it as of this moment.

**Comment by espray** [comment]
Azure/Azure-Functions#845
Azure/azure-functions-core-tools#477

[Developer Community -- docker-compose build error: "Value cannot be null. Parameter name: stream"](https://developercommunity.visualstudio.com/content/problem/254807/docker-compose-build-error-value-cannot-be-null-pa-1.html)

**Comment by espray** [comment]
FYI: From VS Support -- We have fixed this issue and it's available in VS 15.9 https://visualstudio.microsoft.com/downloads/ and 16.0 upcoming release. Thank you for your feedback!

![image](https://user-images.githubusercontent.com/5826764/49387192-dc13db80-f6e6-11e8-8be7-c9027b908199.png)

**Comment by dbreshears** [comment]
@espray,  @da1rren  -  sorry for the confusion via the developer community post,  we had another issue that had a similar error.  Our tooling does not support Azure Functions at this time but it is on our backlog and hope to start investigating this soon as we would like to provide support.

**Comment by SpencerWaz** [comment]
@dbreshears 5 months later, any more feedback? How far in the backlog is this? My company would like to adopt containerized Azure Functions.. but it would be nice if it was supported in Visual Studio.

**Comment by bwateratmsft** [comment]
Azure functions are now supported in Visual Studio 16.3 Preview 2, also requiring version 1.9.2 of [Microsoft.VisualStudio.Azure.Containers.Tools.Targets](https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/). Currently only Linux containers are supported, so I am leaving this issue open.

**Comment by cjbush** [comment]
Any idea of a timeframe for when support for this will be added to compose projects?

**Comment by vrao1020** [comment]
Is there an update on when functions will be supported for docker compose in VS 2019? I currently have to create a copy of my compose file and remove functions from the list of containers for VS to build it correctly (no issues when running compose outside VS 2019). 

Is there an alternative approach to make it work without it having to remove functions?

**Comment by NCarlsonMSFT** [comment]
There is currently no plan to add support for functions to compose projects.

There is [workaround](https://github.com/microsoft/DockerTools/issues/141#issuecomment-522822258) which will allow you to have a functions app in your compose project, but the functions app will not getting debugging support, only build and run.

**Comment by germancasares** [comment]
@NCarlsonMSFT There is no way of adding debugging for an azure function container manually or by any other means?

Is there any plans to allow debugging?

**Comment by NCarlsonMSFT** [comment]
@germancasares Currently it is only supported when debugging just the single project in a container, not as part of a compose application.
If you do want to run it as part of a compose app and still get some debugging you should still be able to attach to the dotnet process in the running container using the steps [here](https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger?view=vs-2019#BKMK_Linux_Docker_Attach)
There is no current plan to bring support for Azure Functions to the Compose project, but if there is enough user feedback that it is a desirable feature that could change.

**Comment by espray** [comment]
@NCarlsonMSFT where would we go to up vote  supporting Compose proj?

**Comment by NCarlsonMSFT** [comment]
@espray It would probably be best to create a specific issue for it (with a link to this one). This one originally covered both compose and single project and does not signal the ongoing interest in compose support as strongly. The other option would be to thumbs down the post above about it not being supported, which does send a clear message 😉, but I don't believe gets tracked as well with triage.

**Comment by tomkerkhove** [comment]
> There is no current plan to bring support for Azure Functions to the Compose project, but if there is enough user feedback that it is a desirable feature that could change.

What? That's a pity. The service supports this and works fine without VS; but not inside of it.

This is a blocker for us if you ask me..

**Comment by tomkerkhove** [comment]
Any update on this?

**Comment by andreatosato** [comment]
Thanks @tomkerkhove for bad news :(

**Comment by cjbush** [comment]
> Thanks @tomkerkhove for bad news :(

Looks like it's been added to the product backlog, so hopefully sometime in the not too distant future?

https://developercommunity.visualstudio.com/t/dcproj-wont-accept-azure-functions-project/1460127

**Comment by Sossenbinder** [comment]
Any updates here? It's a bit unfortunate that a .dcproj can't host this - I did not give the workaround a shot yet, but without debugging support it would still not be a nice experience

**Comment by BigMorty** [comment]
There is item on our backlog to support Azure Functions in the Compose tooling. It is not in progress as of today, but it is very high on the list.

**Comment by Sossenbinder** [comment]
Sounds great!

For the time being I came up with the following workaround, in case it might be useful to someone else to get the "proper" debug experience.

1.) In VS, right click on the solution in the solution explorer -> Properties -> Startup Project. Instead of your docker-compose as startup, select multiple startup projects and mark your docker-compose as "Start", as well as your function project.

2.) Create a network like `docker network create networkname`

3.) In the csproj of your func project, add this xml section to the PropertyGroup:

	`<DockerfileRunArguments>--network networkname --network-alias <network alias of your func></DockerfileRunArguments>`

4.) In your docker-compose project, add this section:

```
networks:
  ideamachinenetwork:
    external:
      name: networkname
```

(Note that this is the syntax for docker-compose V2)

5.) For all your services, add this section to connect it through the network:
```

    networks:
      - ideamachinenetwork
```

If you now start, both the func as well as the docker-compose project should run as debug, and they should be connected in a similar fashion as if they were in one docker-compose project

**Comment by ravipal** [comment]
The Azure Functions support is available in the [latest Visual Studio preview](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes) (17.2 Preview 2)
