### ISSUE TITLE
docker-compose.yml contains bad path to Dockerfile

### ISSUE THREAD

**Issue by julKali** [microsoft/DockerTools#129]
When auto-generating the docker-compose.yml, the dockerfile is specified automatically like so:

`dockerfile: [Project Name]\Dockerfile`

With Windows containers this works fine but if you compose this using Linux containers, it fails with "Cannot locate Dockerfile".

Replacing the \ with a / solves the issue.

**Comment by haniamr** [comment]
Hi @julKali,

Thanks for reporting this. Can you please share with me your VS version?
I can't seem to reproduce this issue on the latest versions.

Thanks!

**Comment by wzowee** [comment]
`[Project Name]\Dockerfile` was on linux containers for me up until the latest upgrade to Docker - 18.06.1-ce-win73 (19507)

After this I had to switch `\ to a / and it's working - thanks @julKali lost hours on this prior to reading your issue here.

**Comment by haniamr** [comment]
@wzowee I don't think it would be related to a "Docker for Windows" issue, however that would be a scaffolding problem when creating the project. I can't repro the issue so it'd be helpful if you can share your Visual Studio version.
