### ISSUE TITLE
docker-compose - incompatible - The application is not installed VS2017

### ISSUE THREAD

**Issue by skrusty** [Microsoft/DockerTools#132]
Hi,
Recently I opened a project that uses docker, and all docker support seems to be missing from the project. docker-compose shows incompatible and i am unable to run the project in docker.

I've repaired VS2017, removed and re-installed the docker (container) tooling, and yet still no luck.

![image](https://user-images.githubusercontent.com/8448201/42505786-b5c79b00-8437-11e8-96d4-dad7efc32949.png)

The options to add docker support are there, but that's where it ends.

Docker for Windows is running, and currently in windows container mode.

Any suggestions welcomed.

**Comment by skrusty** [comment]
Hi, i reinstalled everything, and made no different.

Oddly, I then right-clicked on the file, and clicked reload. At which point i got a prompt telling me i needed up update the file. Clicked OK and it all worked. This didn't happen until I clicked reload on the file.

Wasn't obvious at all. But at least it is working now.

Cheers anyway.

**Comment by dbreshears** [comment]
@rahul-atharva , can you please attempt to repair the VS installation.   If you need further help as this seems to be related to a VS setup issue,  please open an issue at https://developercommunity.visualstudio.com/home.

**Comment by jcklinger** [comment]
Had this issue also, right click > reload with dependencies worked for me.  After that never had to do it again for other solutions that had docker-compose in them...  SWEET!

**Comment by Zifah** [comment]
> Had this issue also, right click > reload with dependencies worked for me. After that never had to do it again for other solutions that had docker-compose in them... SWEET!
> 
> Microsoft Visual Studio Community 2022 Version 17.10.0 VisualStudio.17.Release/17.10.0+34916.146 Microsoft .NET Framework Version 4.8.09037

This just fixed the problem for me in Visual Studio 2026. Thanks for this thread.
