### ISSUE TITLE
using docker on a tfs build agent

### ISSUE THREAD

**Issue by mattmeye** [Microsoft/DockerTools#133]
hello,
i want to use docker on a tfs build agent. it is a vm without virtualiziation feature (vm in vm not working).
Actually a solutions with a docker project will only be build when i am logged in on the vm via rdp.

i think docker is not running as a system service.

How can i solve this problem?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please reply with any additional context for our consideration, we are happy to take a look!
