### ISSUE TITLE
visual studio 2017 compose failed, invalid volume specification

### ISSUE THREAD

**Issue by hamed-vojdani** [Microsoft/DockerTools#135]
windows 10 64 bit version 1803( build 17134.5),
VS version 15.7.4,
using docker for windows 18.03.1-ce in windows container mode,
when building docker compose project i got error.
here is VS output image created successfully
but composing failed with this error
` invalid volume specification`

while full console output is :

`1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker ps --filter "status=running" --filter "name=dockercompose644423297204860265_aspnetcoresample_" --format {{.ID}} -n 1
1>ASPNetCoreSample -> D:\ASPNetCoreSample\ASPNetCoreSample\bin\Debug\netcoreapp2.0\ASPNetCoreSample.dll
1>docker-compose  -f "D:\ASPNetCoreSample\docker-compose.yml" -f "D:\ASPNetCoreSample\docker-compose.override.yml" -f "D:\ASPNetCoreSample\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose644423297204860265 --no-ansi up -d --build --force-recreate --remove-orphans
1>Building aspnetcoresample
1>Step 1/3 : FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
1> ---> 52528f923728
1>Step 2/3 : WORKDIR /app
1>Removing intermediate container 397df3e9f11c
1> ---> d4e04d0d81ea
1>Step 3/3 : EXPOSE 80
1> ---> Running in cf68ed89eb94
1>Removing intermediate container cf68ed89eb94
1> ---> f0ad8048f956
1>Successfully built f0ad8048f956
1>Successfully tagged aspnetcoresample:dev
1>Creating dockercompose644423297204860265_aspnetcoresample_1 ...
1>Creating dockercompose644423297204860265_aspnetcoresample_1 ... error
1>ERROR: for dockercompose644423297204860265_aspnetcoresample_1  Cannot create container for service aspnetcoresample: invalid volume specification: '/d/ASPNetCoreSample/ASPNetCoreSample:C:\app:rw'
1>ERROR: for aspnetcoresample  Cannot create container for service aspnetcoresample: invalid volume specification: '/d/ASPNetCoreSample/ASPNetCoreSample:C:\app:rw'
1>Encountered errors while bringing up the project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Building aspnetcoresample
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Creating dockercompose644423297204860265_aspnetcoresample_1 ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Creating dockercompose644423297204860265_aspnetcoresample_1 ... error
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for dockercompose644423297204860265_aspnetcoresample_1  Cannot create container for service aspnetcoresample: invalid volume specification: '/d/ASPNetCoreSample/ASPNetCoreSample:C:\app:rw'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : ERROR: for aspnetcoresample  Cannot create container for service aspnetcoresample: invalid volume specification: '/d/ASPNetCoreSample/ASPNetCoreSample:C:\app:rw'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : Encountered errors while bringing up the project..
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
1>Done building project "docker-compose.dcproj" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========`

here is the content of docker-compose.override.yml file:

version: '3.4'

services:
  aspnetcoresample:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

i added a environment variable COMPOSE_CONVERT_WINDOWS_PATHS=1 and reset system but no success.
thank you for your workaround

**Comment by bwateratmsft** [comment]
This looks like it could be the same as #128, see my response there: https://github.com/Microsoft/DockerTools/issues/128#issuecomment-410750259

**Comment by hamed-vojdani** [comment]
I changed COMPOSE_CONVERT_WINDOWS_PATHS from 1 to 0 and container creation was successful.
thank u very much
