### ISSUE TITLE
Support multiple tags for a docker image

### ISSUE THREAD

**Issue by siebigteroth** [Microsoft/DockerTools#136]
Currently, the publishing profiles for using a custom docker registry, only support "Unique Tagging". When publishing an asp.net core project as docket image to a custom docker registry, a new tag is generated. E.g.:

![image](https://user-images.githubusercontent.com/5673854/43170842-7d142b68-8fa7-11e8-842c-6a4b46b1a3f2.png)

But it should also be possible to add additional tags (e.g. latest). Especially to allow "Stable Tags":
https://blogs.msdn.microsoft.com/stevelasker/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please reply with any additional context for our consideration, we are happy to take a look!
