### ISSUE TITLE
Dockerfile generated with absolute path

### ISSUE THREAD

**Issue by TroelsL** [Microsoft/DockerTools#138]
When enabling docker support (Linux) via the Project menu, I end up with the following Dockerfile:

```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY Devices.Api/Devices.Api.csproj Devices.Api/
COPY c:\Users\MYUSERNAME\Documents\Visual Studio 2017\Projects\smarthome\Devices.Api\Devices.Api\nuget.config Devices.Api/
COPY Interfaces/Devices.Interfaces.LandroidS/Devices.Interfaces.LandroidS.csproj Interfaces/Devices.Interfaces.LandroidS/
COPY Devices.Interfaces/Devices.Interfaces.csproj Devices.Interfaces/
COPY Interfaces/Devices.Interfaces.Ihc/Devices.Interfaces.Ihc.csproj Interfaces/Devices.Interfaces.Ihc/
RUN dotnet restore Devices.Api/Devices.Api.csproj
COPY . .
WORKDIR /src/Devices.Api
RUN dotnet build Devices.Api.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Devices.Api.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Devices.Api.dll"] ~~~~
```

The line

```
COPY c:\Users\MYUSERNAME\Documents\Visual Studio 2017\Projects\smarthome\Devices.Api\Devices.Api\nuget.config Devices.Api/
```

Should be:
```
COPY Devices.Api/NuGet.Config Devices.Api/
```

Obviously, the path greatly depends on the machine building it. I also believe the casing should be correct, as I am building on Linux.

Also, why the
```
COPY . .
```

**Comment by sgreenmsft** [comment]
Thanks for letting us know about this issue path issue.  We have fixed the code and we'll include the fix in an upcoming release of Visual Studio.

Regarding "COPY . ." - in a multistage build, your code is compiled inside of the container.  In an attempt to ensure that all necessary files are present in the container when compilation occurs, we copy the entire contents of the docker build context into the container.  You can, of course, update the dockerfile to copy only specific files if that's better in your scenario.

**Comment by TroelsL** [comment]
@sgreenmsft Excellent response time, thanks. I really like this functionality - it removes much of the tediousness of setting up docker deployment in all the new projects that is the inevitable result of using microservices. With this, setting up deployment with GitLab CI can be done in 2 minutes.

And thanks for the explanation on "COPY . .". It isn't needed in my case, but it doesn't hurt either.
