### ISSUE TITLE
docker-compose failing on ResolveProjectInputAndOutput - Parameter name: path1

### ISSUE THREAD

**Issue by MartyIce** [microsoft/DockerTools#139]
I was attempting to follow the instructions located here to "container enable" a legacy WCF project:

https://github.com/dotnet-architecture/eShopModernizing/wiki/02.-How-to-containerize-the-.NET-Framework-web-apps-with-Windows-Containers-and-Docker

Everything seemed to complete correctly, but when attempting to run my project (where docker-compose is now the startup project), I see the following error in "Output" pane:

```
1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018: The "ResolveProjectInputAndOutput" task failed unexpectedly.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018: System.ArgumentNullException: Value cannot be null.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018: Parameter name: path1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018:    at System.IO.Path.Combine(String path1, String path2)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018:    at Microsoft.Docker.BuildTasks.ResolveProjectInputAndOutput.ResolveRelativeOutputAssemblyPath(TargetOS targetOS, TargetFramework targetFramework, DockerDevelopmentMode developmentMode)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018:    at Microsoft.Docker.BuildTasks.ResolveProjectInputAndOutput.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(80,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
1>Done building project "_______" -- FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========
```

Is there somewhere I can get more diagnostic information as to what's missing?

**Comment by MartyIce** [comment]
Don't know whether it's related, but poking around I see that "DockerComposeProjectPath" is not defined - is this the cause, and if so, where should this be defined?

![image](https://user-images.githubusercontent.com/5083039/43367280-25aea2d8-9310-11e8-9055-f231144568e7.png)

**Comment by viskin** [comment]
In my case, OutputPath is undefined for task DockerResolveProjectInputAndOutput when using configuration name other than Debug or Release.

**Comment by haniamr** [comment]
@MartyIce "DockerComposeProjectPath" should be defined in every project that is containerized as an MSBuild property, something like:
`<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>`

Please verify this property exists and I'll be happy to look further if you still have any issues.

@viskin are you still seeing this issue? I couldn't repro it, if you still see it please share with me the MSBuild detailed logs.

**Comment by kinl99** [comment]
> 
> 
> In my case, $(OutputPath) is undefined for task DockerResolveProjectInputAndOutput when using configuration name other than Debug or Release.

same here, can anyone advice on a workaround?
