### ISSUE TITLE
Debugging fail - 403 Forbidden

### ISSUE THREAD

**Issue by brunis** [microsoft/DockerTools#140]
I dont know how this is possible, my .NET app launches with the default entrypoint:
C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646

Pretty sure that means anon access or any user allowed, but still VS gives me 403 Forbidden

How do i get access to the event viewer, so i can get some useful info?

docker logs <container-id> is useless.

**Comment by haniamr** [comment]
@brunis thanks for reporting, can you please provide repro steps and VS version?
