### ISSUE TITLE
Failed to launch debug adapter

### ISSUE THREAD

**Issue by Krimsar** [Microsoft/DockerTools#142]
Since upgrading to the newest version of Visual Studio 2017, I cannot run newly created .Net Core projects with docker support. I get the following error on two separate machines:

![grafik](https://user-images.githubusercontent.com/3831785/44518060-96984900-a6c9-11e8-88ca-57140a1f74c7.png)

Unfortunately there is no additional information in the output window. Just the successful build:

`1>------ Build started: Project: RedLockTest, Configuration: Debug Any CPU ------
1>docker exec -i 636da0c6267465c3e44406680208387935d1b68df7d08472b9d372fe2d6993af /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
1>RedLockTest -> C:\Users\<myuser>\source\test\RedLockTest\RedLockTest\bin\Debug\netcoreapp2.1\RedLockTest.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
`

Visual Studio 2017 Version: 15.8.1
Docker Version: 18.06.0-ce-win72 (19098)

**Comment by Rocinante89** [comment]
I'm having this exact same error too. I didn't get the message about drive sharing however and I still can't run the project

**Comment by Krimsar** [comment]
@Rocinante89 I think I only got the message when I started VS as Administrator. Maybe that helps?

@bwateratmsft Unfortunately there wasn't. There was no "Debug" in the "Show output from" drop down. Only "Build", "Build Order" and "Package Manager"

After disabling and re-enabling C under docker drive sahres, I can now create and run new docker api projects without admin.

**Comment by bwateratmsft** [comment]
@Krimsar If you see the issue reoccur please let us know. So far I haven't been able to reproduce it on this side.

**Comment by aaronmorgan** [comment]
Had the same problem after previously working fine during the same VS session. Restarting VS didn't correct the problem. 
I was running VS in Admin mode, restarted without Admin mode and the issue came right.

**Comment by Rocinante89** [comment]
In my case I believe it was because I am using the alpine image of aspnetcore and that isn't supported by debugging as of yet

**Comment by cjekin** [comment]
My Windows password had changed, but the Docker drive mapping hadn't. Just unticked the shared drive in settings, applied and reticked. It asked me to re-enter my password. Restart Docker and Visual Studio and the issue resolved.

**Comment by dbreshears** [comment]
I was able to repro this as I changed my password yesterday.   I can confirm that resetting drive sharing, restarting both Docker and VS resolved it for me as well.

**Comment by mtawara** [comment]
I am getting this exact same error too. I have tried everything in these comments, but the error is still occurring.

**Comment by quasipolynomial** [comment]
After restarting VS, Docker (checking and unchecking shared drives) and Windows multiple times this did not work for me.

I was receiving some HRESULT error in VS, after the above prompt.

I then deleted the vsdbg folder (which is used as a volume), then received a new error in VS saying that docker did not have permissions to use a shared drive, then redid the drive sharing and it worked.

**Comment by ildoc** [comment]
- Restarted VS
- Restarted Docker
- Restarted Windows
- Re-installed Docker
- Deleted and re-cloned solution

Deleting vsdbg folder worked for me

docker 18.09.2 build 6247962
visual studio 2019 16.1.6

**Comment by FlorinskiyDI** [comment]
Deleting vsdbg folder also worked for me, without steps in previews comment
- docker desktop Version 2.0.0.3 (31259)
- vs2019 16.1.6

**Comment by CreepyGnome** [comment]
Why was this closed? One person repo'd the issue and it was because they changed their password. Well, that is not the reason for the other people nor the person who open the issue from what I can tell.

I too am using Docker for Windows with Linux containers and I get this issue several times a week and all I do is Restart Docker and it works. No unsharing resharing or anything. 

There seems to be an issue with Visual Studio and how it talks to Docker that gets out of whack and requires Docker to be restarted without any changes. At least on "my box" that is. However looking at how other people resolved it sans the guy who changed his password, they all seem to involve a restarting of docker as the last step after making changes I would suggest that the restart of docker is all the is required in most cases.

**Comment by ahmadalli** [comment]
any update on this? I'm getting the error on vs 16.6.0 and docker desktop 2.3.0.2, engine 19.03.8 with wsl2 backend and restarting docker or removing vsdbg doesn't seem to work

**Comment by pilsdumps** [comment]
I had the same problem with a simple Blazor Webassembly app seemingly related to remote debugging in Chrome though not sure. Only fix I could find was delete and reclone from repos. Visual Studio v. 16.6.1

**Comment by idscom** [comment]
Having the same issue v16.6.2 - tried a reinstall of VS and still having the issue. The same Blazor solution is working fine in VS 16 Preview. So it seems to be a VS issue. And ideas?

**Comment by xela-trawets** [comment]
In my case this caused by a setting for debugging the client browser (which loads the url for the page)

/project/config/debuggerConfiguration-c0c-guid-Stuff-8dc5.json
{"chromiumDebuggerPort":59715}

Renaming that file causes a new one to be created with new and correct high port number

To reproduce just hit the power switch, so things are messed up and stale.
I do this all the time to make my day more fun.

**Comment by jacgandres** [comment]
> In my case this caused by a setting for debugging the client browser (which loads the url for the page)
> 
> /project/config/debuggerConfiguration-c0c-guid-Stuff-8dc5.json
> {"chromiumDebuggerPort":59715}
> 
> Renaming that file causes a new one to be created with new and correct high port number
> 
> To reproduce just hit the power switch, so things are messed up and stale.
> I do this all the time to make my day more fun.

it works for me, thnks

**Comment by ErnanMaisels** [comment]
> In my case this caused by a setting for debugging the client browser (which loads the url for the page)
> 
> /project/config/debuggerConfiguration-c0c-guid-Stuff-8dc5.json
> {"chromiumDebuggerPort":59715}
> 
> Renaming that file causes a new one to be created with new and correct high port number
> 
> To reproduce just hit the power switch, so things are messed up and stale.
> I do this all the time to make my day more fun.

Thanks, bu didn't work for me :(

**Comment by ErnanMaisels** [comment]
In my case, it was helpful to clear cached files
![image](https://user-images.githubusercontent.com/76112655/127106362-5c241e9d-8c0d-45ea-b6d1-2515c42ecd42.png)
