### ISSUE TITLE
No docker-compose project created when enabling docker support on new Project

### ISSUE THREAD

**Issue by wzowee** [Microsoft/DockerTools#146]
When I create a new ASP.Net Core project in Visual Studio Community edition and select to enable docker support there is no docker-compose project created.

This reproduced on 15.8.1, and 15.8.2.

A Dockerfile is generated and placed in the project, but no docker-compose project so no ability to run in Docker Compose.

![image](https://user-images.githubusercontent.com/5781975/44942138-70bc2400-adee-11e8-9403-7c73ed4cc00f.png)

No option to add docker support from the Solution either.

I'm running Docker 18.06.1-ce-win73 (19507) - Stable.

**Comment by bwateratmsft** [comment]
Hey @wzowee, beginning in 15.8 we do not create a docker-compose project by default when you add Docker support (see [here](https://blogs.msdn.microsoft.com/visualstudio/2018/08/14/visual-studio-2017-version-15-8/) for more information). You can still add it by doing Add > Container Orchestrator Support if you really need it, but you can debug with just the single project.
