### ISSUE TITLE
Visual Studio for Mac running / debugging container does nothing

### ISSUE THREAD

**Issue by dzins** [microsoft/DockerTools#153]
VS For Mac V 7.6.10 (build 27)
Docker for Mac V 18.06.1-ce-mac73 (26764) stable channel

Create a new asp.net core web app (mvc)
Right click and add docker support
Build the .net project (this works fine)
Build the docker-compose project (this works fine)

Select Run - > Start Without Debugging or Start Debugging or hit F5 or hit the play button, nothing happens, nothing at all, there is nothing logged anywhere that I can find, nothing in the Build Output, just nothing anywhere.

I tried the suggestions from:
https://docs.microsoft.com/en-us/azure/vs-azure-tools-docker-troubleshooting-docker-errors

adding the nugetfallbackfolder and removing the possible stale debugging folders.

If I go in to the project folder and do docker-compose up it starts the containers and I can access the site.

What am I doing wrong?  Is this just not supported now?

**Comment by bwateratmsft** [comment]
Thanks @dzins , this is a known issue that we are investigating with high priority.  Many folks have reported this so you are not alone.  We are currently tracking it primarily [here](https://developercommunity.visualstudio.com/content/problem/366580/cannot-run-debug-docker-compose-project.html).

**Comment by haniamr** [comment]
This issue is now fixed, please shout out if you're still having problems.
