### ISSUE TITLE
Docker is required even when not part of the build configuration

### ISSUE THREAD

**Issue by mbp** [microsoft/DockerTools#154]
Consider having a solution with a project, that you add Container Orchestrator Support for. A `docker-compose` project is being added. Good.
But what if I don't want to require other users to have Docker installed, to build the solution? I go to Configuration Manager and disable the checkbox on ´docker-compose` in Build column.

However, somehow Docker is still required, because users get this error:

![image](https://user-images.githubusercontent.com/77322/47987170-2cdfe680-e0df-11e8-8eb0-85a89136c650.png)

It does not even start to build. It does not even try to invoke `docker-compose`, the error still pops up.
Is there a way to get around this?

**Comment by bwateratmsft** [comment]
Hey @mbp , unfortunately there's not currently a workaround; however if your project is .NET Core web, you can remove the Docker-Compose project and then do Add > Docker support again. Beginning in 15.8 we have a single-file Docker experience where Compose is not used at all; and as long as Docker is not the active launch profile, it shouldn't be needed at all.

We are aware of this shortcoming in our Compose experience and are hoping to address it soon.

**Comment by mbp** [comment]
Thanks for your reply. We have a mix of both ASP.NET Core and .NET Core Console applications ("background services"), and we would prefer to use the same workflow for both of them. Looking forward to a more unified solution.

**Comment by mbp** [comment]
@bwateratmsft with regards to addressing it soon, can I ask if that means "Add Docker support" (no compose) will also work for non-ASP.NET Core projects?

**Comment by dbreshears** [comment]
@mbp ,  yes, in a future release we plan to add the same single Dockerfile support to .NET core console projects

**Comment by bormm** [comment]
We have a .Net Framework Console Application and the same issue. I would not call this an enhancement its a bug -> Docker is required without building any docker component.

Microsoft should invest a lot of more resources into the docker integration to get it more work reasonable. The only workaround I see is adding an separate solution without the docker parts for all people that do not want to build them.

**Comment by dbreshears** [comment]
@bormm .  Thanks for the feedback and agree on this being a bug.  I tested this on VS 2019 and appears that it has been fixed when choosing not to build the .dcproj in configuration list.

**Comment by dbreshears** [comment]
Closing older issue, appears this was fixed in VS 2019.
