### ISSUE TITLE
Error message when starting project with SSL

### ISSUE THREAD

**Issue by rgcooper2** [microsoft/DockerTools#156]
Whenever SSL is enabled and the project is started, the error message 'Unable to install the ASP.NET Core development certificate tool (dev-certs)." appears.

**Comment by haniamr** [comment]
Thanks @rgcooper2 for reporting this. Which .NET Core version are you using for your app? Also an output of `dotnet --info` would be useful.

**Comment by pratiksanglikar** [comment]
@rgcooper2, Closing this issue since inactivity for a long time.
Please feel free to open a new issue if the problem persists.
