### ISSUE TITLE
Docker Compose (Orchestration support) WCF service project in VS 2017

### ISSUE THREAD

**Issue by sowsan** [microsoft/DockerTools#159]
Not finding the "Add --> container orchestration" support in VS 2017 for a project based out of "wcf service". Its showing up for the "wcf application" though. Any idea how can i add orchestration support for a project "wcf service"?

Version : VS 2017 15.8.9 Ent Edition WCF Server Project based out of .NET framework 4.6

**Comment by haniamr** [comment]
Thanks @sowsan for reporting this. So the project you have is basically a class library (i.e. WCF Service Library), correct?  If that is the case, we do not support class libraries at the moment.
