### ISSUE TITLE
How are "docker run" settings determined? 

### ISSUE THREAD

**Issue by joergjo** [Microsoft/DockerTools#160]
(Windows 10 1809, VS 2018 15.9.3, .NET Core SDK 2.2.100)

I've retrofitted an existing APS.NET Core 2.1 project (now updated to 2.2) to work with the the Docker Tools in VS 2017 15.9.x, i.e.
* include a plain vanilla Dockerfile like the one the Docker Tools create
* added ` <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>`to the `.csproj` file
* included the `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` NuGet package 
* added a certificate using `dotnet dev-certs https --trust -ep "$env:APPDATA\ASP.NET\https\<WebAppProject>.pfx" -p $password` 
* Added `Kestrel:Certificates:Development:Password $password` to my user secrets.

Everything works fine, _except_ that the application is only launched with an HTTP endpoint. After creating a new project with Docker support enabled, I found that this new project is launched with he following `docker run` parameters:
```
-v "C:\Users\<username>\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" 
-v "C:\Users\<username>\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro"
-e "ASPNETCORE_URLS=https://+:443;http://+:80" 
-e "ASPNETCORE_HTTPS_PORT=44330"
-p 51894:80 
-p 44330:443
```
Neither the volume mappings nor `ASPNETCORE_URLS` and `ASPNETCORE_HTTPS_PORT` are included in the generated `docker run` command line created for my project, though. Hence, I can only access my web app through HTTP when debugging.

So... how do the Docker Tools determine which endpoints to expose and which ASP.NET Core enviroment variables to set? What steps am I missing to make this work with HTTPS as well?

**Comment by bwateratmsft** [comment]
@joergjo , are you able to share your CSPROJ file and your Properties\launchSettings.json? Most of the information for the run command is computed from data in those two files. If I had to guess, I suspect the missing piece is in the launchSettings.json.
However, were you unable to do right click project > Add > Docker Support rather than manually configuring those things?

**Comment by joergjo** [comment]
Case closed. While copying and pasting the two files, I also checked the `launchSettings.json` from my working reference project. It turns out you use the HTTP and SSL port specified in `iisSettings` for `docker run` port publishing. Since my project had been set up way back without HTTPS support, `iisSettings.iisExpress.sslPort` was set to 0. After setting it to a valid port, HTTPS worked immediately.

To answer your last question: I already had a Dockerfile, and since the only thing missing was your NuGet package, I just added that manually. I've set up m project to work with both VS 2017 and VS Code, so I'm very careful to understand the magic that VS 2017 invokes. 

Speaking of which:  I've seen there are newer versions of the NuGet package available than the one added to ASP.NET Core 2.2 projects. Which version do you recommend to use?

**Comment by bwateratmsft** [comment]
That makes sense, thanks!

Regarding the version of the Targets NuGet package, it's up to you really. You can upgrade, it should be harmless as long as the major version isn't changed. Worst case, if things do go awry, it's easy to roll back to a stable version.
