### ISSUE TITLE
Developer certificate not found when project file name differs from project assembly name

### ISSUE THREAD

**Issue by mlassbo** [microsoft/DockerTools#162]
The developer certificate file that is generated by DockerTools is named after the Web/Api-project file name, e.g. Api.csproj generates a certificate with filename Api.pfx.

When Kestrel tries to find the developer certificate [it assumes the certificate file name is HostingEnvironment.ApplicationName + ".pfx"](https://github.com/aspnet/AspNetCore/blob/68cc5e7846240bacc146854dfc6a175e30ff0f60/src/Servers/Kestrel/Core/src/KestrelConfigurationLoader.cs). HostingEnvironment.ApplicationName is by default the _assembly name_ of the Web/Api-project.

So.. if the assembly name and the project file name does not match, the developer certificate generated by DockerTools is not found by Kestrel.

I believe it would make more sense if the developer certificate file generated by DockerTools was named after the assembly name of the project instead of the project file name.

There is also [obviously room for improvement in how Kestrel handles developer certificates](https://github.com/aspnet/Docs/issues/6199) and perhaps a more long term solution would be to have both DockerTools and Kestrel be a bit more flexibel/configurable in the naming of the development certificate.

Anyway, thanks for an awesome product and looking forward to read your comments on this! :)

**Comment by dbreshears** [comment]
Fixed some time ago, verified in the latest VS container tooling
