### ISSUE TITLE
Unable to load symbols when debugging via docker

### ISSUE THREAD

**Issue by pthelusma** [microsoft/DockerTools#163]
With an existing dotnet core 2.2 web api application, I am unable to debug the application via Docker in Visual Studio. I am able to do this with a brand new project without an issue. The application runs without an error, but I am noticing that when loading the dll produced by the project, the debug window shows that the dll was built without symbols, but I am not sure how to proceed. I have upgraded to the latest VS (15.9.7), running docker (18.09.1), and dotnet core (2.2.103).

**Comment by dbreshears** [comment]
Closing older issue, this should not be an issue with the latest Visual Studio and supported dotnet core.
