### ISSUE TITLE
An error occurred while attempting to build Docker image.	

### ISSUE THREAD

**Issue by julielerman** [Microsoft/DockerTools#164]
latest VS2017: 15.9.7
ASP.NET and Web Tools 2017: 15.9.04012.0
Docker Desktop 2.0.0.3 (31259) set to Windows Containers
Docker is running
Hyper-V is on

Create new project from ASP.NET Core 2.2 API template with Enable Docker Support checked

This is the default DockerFile code:

```
FROM microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1803 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk-nanoserver-1803 AS build
WORKDIR /src
COPY ["WebApplication1/WebApplication1.csproj", "WebApplication1/"]
RUN dotnet restore "WebApplication1/WebApplication1.csproj"
COPY . .
WORKDIR "/src/WebApplication1"
RUN dotnet build "WebApplication1.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "WebApplication1.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
```
I can debug with WebApplication1 targeted. i can debug with IIS Express targeted. But with Docker targeted I get the error 

An error occurred while attempting to build Docker image.	 File Container.targets line 255

I tried just pulling the image:
docker pull microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1803
also tried 1809
also tried just docker pull microsoft/dotnet:2.2-aspnetcore-runtime

That results in unauthorized: incorrect username or password
I *am* logged in to the docker desktop with my docker account. But it's a public image... 

What am I doing wrong?

I'm not alone: https://github.com/docker/for-win/issues/2825

**Comment by bwateratmsft** [comment]
Hey @julielerman, this Github repo is for the Visual Studio tools for Docker. It looks like this issue is with Docker Desktop, although, different from the one you linked. Can you create an issue there in [https://github.com/docker/for-win](https://github.com/docker/for-win)?

**Comment by julielerman** [comment]
Thanks. Looks like even though I was logged into the docker for destktop app, I had to log in via the CLI
