### ISSUE TITLE
Added a change/release log to Microsoft.VisualStudio.Azure.Containers.Tools.Targets

### ISSUE THREAD

**Issue by vpereira01** [Microsoft/DockerTools#165]
Hi,

Can you please add some kind of change/release log to the Microsoft.VisualStudio.Azure.Containers.Tools.Targets package?

I was just checking my solution for outdated packages and found I have an 1.0.2xxxx version instaled and now a 1.4.4 is available. Checking the NuGet galleray package provides no information on what has changed and how is this package version related/dependent on the Visual Studio version.

Thanks

**Comment by bwateratmsft** [comment]
Created a brief release log. You can see the announcement over in #181.
