### ISSUE TITLE
Generated Dockerfile is placed in wrong directory

### ISSUE THREAD

**Issue by Ryukote** [Microsoft/DockerTools#167]
I don't know if I am in a right place or not, so if I am in a wrong repository please tell me a repository where to submit this issue.

When I add Docker support for my project, Visual Studio generates Dockerfile which is placed in a wrong directory.

In a generated Dockerfile there is a line:

`COPY TestProject/TestProject.csproj TestProject/`

which will try to copy csproj resource from that directory, but the thing is that Dockerfile is placed in the same directory as a TestProject.csproj which will result in error for that line, cause Dockerfile can't find that resource which is logical. There is no directory TestProject/TestProject/TestProject.csproj.

When I place that Dockerfile in the same directory as TestProject.sln, then it will work.

This only happens with manual docker build, but if I set Docker as the startup project and run the app it will work like a charm, which confuse me cause it should not work.

And yes, the same will run and work from Visual Studio if I place Dockerfile in the same directory as TestProject.sln

Easy fix for this is to automatically place that generated Dockerfile in the same directory as a solution file.

**Comment by bwateratmsft** [comment]
The reason it is done this way is because the Dockerfile build context is one level up from the project, at the solution file level. If you alter your "docker build" command that you're using manually to use that one-level-up build context, it will work like it does in VS.

**Comment by Ryukote** [comment]
I got confused from your answer :)
I didn't understand if what I have noticed is valid or not.
The reason I am sometimes doing it manually is because I need to enter environment variable values.
From what I know, I can't do that from Visual Studio.
I mean, I could by modifying Dockerfile and hardcode the values in there, but I want to have image with different values (scenarios), so that is why it is bothering for me to do it like that.
It is not a big deal to transfer Dockerfile one level up in directory path, but I am often annoyed by that (and sometimes I forget to do that).

**Comment by bwateratmsft** [comment]
That makes sense. I think that .env files are supported. In an upcoming version of VS 2019 (unfortunately, not in 16.0, hopefully in 16.1 though), we are adding support for environment variables to be given to the container from the Debug launch profile as well.

**Comment by Ryukote** [comment]
That would be awesome if it will be supported by default in VS 2019. I would have to research about .env files, cause if it is not supported, I will just have to be annoyed till VS 2019 comes out.

**Comment by sgreenmsft** [comment]
Instead of using "docker build ." to build your dockerfile, the command would be:
"docker build -f Dockerfile .."

**Comment by Ryukote** [comment]
What? We were not talking about docker build syntax. And no one said "docker build ."

**Comment by sgreenmsft** [comment]
You're saying that you're moving the Dockerfile from one folder to another and then running docker build, correct?  If so, that's not necessary.  Just provide the solution directory as the build context when calling docker build (e.g. replace the "." with "..")

**Comment by Ryukote** [comment]
Aha. Now I get you :) it never crossed my mind to actually place one more dot.

**Comment by Ryukote** [comment]
From my point of view this issue can be closed, since I can use 2 dots instead of 1 dot to build image that is for my case.

**Comment by pixsaoul** [comment]
Sorry for the inconvenience but I'll still write my message if someone pass by.

I had a similar issue on a vanilla asp.net core project, with having it on the same or on a different folder as the sln.
I could not get how it didn't work on a different folder.

As I was typing my post here, suddenly (after 6 hours of trying to identify the problem) it started working.

I don't know why, I don't know how, but it did.
All I did was create another project that had the same solution folder activated and build it (to see if that was related)

Done with VS 17.2.1
