### ISSUE TITLE
Include instructions for accessing private NuGet repo

### ISSUE THREAD

**Issue by Leon99** [microsoft/DockerTools#168]
See https://github.com/Microsoft/artifacts-credprovider/issues/63#issuecomment-471796987. It would be good if DockerTools analyzed the project and automatically generated the snippet to enable connecting to private repos.

**Comment by bwateratmsft** [comment]
While it is not a complete solution, if there is a "NuGet.config" file present in alongside the project file when you add Docker support, it will include it in the Dockerfile COPY statements.

**Comment by Leon99** [comment]
Thanks @bwateratmsft, good to know. Does it work if NuGet.config is located in the parent (solution's) folder (which is very typical)?

**Comment by bwateratmsft** [comment]
@Leon99 The code to add the NuGet.config to the COPY statements won't look up a level, however, you can manually add a COPY statement here that takes the NuGet.config from the SLN folder and place it alongside the CSPROJ (so that the dotnet restore inside the container can use it).

For example:
`COPY ["MyWebApp/MyWebApp.csproj", "MyWebApp/"]`
`COPY ["NuGet.config", "MyWebApp/"]`

**Comment by StingyJack** [comment]
Any idea when this is going to just get fixed? The project system and VS knows there is a nuget config at the solution level. I just spent an hour trying things and searching before coming across this post.  Even adding that I still get the following when using the publish to container registry wizard in VS for the project...

```
/src/MyWebApp/MyWebApp.csproj : error NU1101: Unable to find package OneOfOurPrivatePackagesHostedOnAzureArtifacts. No packages exist with this id in source(s): nuget.org
```

**Comment by bwateratmsft** [comment]
@StingyJack You need to copy the NuGet.config into the container before restoring. The container is a completely and totally separate environment from your machine and can't possibly know the NuGet config.

```

**Comment by bwateratmsft** [comment]
Can you share the Dockerfile and full output from the publish operation?

**Comment by StingyJack** [comment]
Sanitized Dockerfile
``` dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
COPY ["MyWebApp/MyWebApp.csproj", "MyWebApp/"]
COPY ["NuGet.config", "MyWebApp/"] # Manually addded from the example in this issue
RUN dotnet restore "MyWebApp/MyWebApp.csproj"
COPY . .
WORKDIR "/src/MyWebApp"
RUN dotnet build "MyWebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MyWebApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MyWebApp.dll"]
```

Sanitized log file
```
Skipping target "GenerateStaticWebAssetsManifest" because all output files are up-to-date with respect to the input files.
Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Skipping target "_DiscoverMvcApplicationParts" because all output files are up-to-date with respect to the input files.
Skipping target "CoreGenerateAssemblyInfo" because all output files are up-to-date with respect to the input files.
Skipping target "CoreCompile" because all output files are up-to-date with respect to the input files.
Skipping target "_CreateAppHost" because all output files are up-to-date with respect to the input files.
Touching "c:\Dev\MyWebApp\MyWebApp\obj\Release\netcoreapp3.0\MyWebApp.csproj.CopyComplete".
Adding items with BuildAction=TypeScriptCompile to the same collections that will be populated (with items of other BuildActions) by the GetCopyToOutputDirectoryItems target
Skipping target "_CopyOutOfDateSourceItemsToOutputDirectory" because all output files are up-to-date with respect to the input files.
Skipping target "GenerateBuildDependencyFile" because all output files are up-to-date with respect to the input files.
Skipping target "GenerateBuildRuntimeConfigurationFiles" because all output files are up-to-date with respect to the input files.
MyWebApp -> c:\Dev\MyWebApp\MyWebApp\bin\Release\netcoreapp3.0\MyWebApp.dll
Directory "c:\Dev\MyWebApp\MyWebApp\bin\Release\netcoreapp3.0\refs" doesn't exist. Skipping.
Deleting file "obj\Docker\publish\appsettings.Development.json".
Deleting file "obj\Docker\publish\appsettings.json".
Deleting file "obj\Docker\publish\Elasticsearch.Net.dll".
Deleting file "obj\Docker\publish\MyPrivatePackage1.dll".
Deleting file "obj\Docker\publish\MyPrivatePackage2.dll".
Deleting file "obj\Docker\publish\MyWebApp.deps.json".
Deleting file "obj\Docker\publish\MyWebApp.dll".
Deleting file "obj\Docker\publish\MyWebApp.exe".
Deleting file "obj\Docker\publish\MyWebApp.runtimeconfig.json".
Deleting file "obj\Docker\publish\Nest.dll".
Deleting file "obj\Docker\publish\web.config".
Removing directory "obj/Docker/publish/".
Creating directory "obj/Docker/publish/".
Copying file from "c:\Dev\MyWebApp\MyWebApp\obj\Release\netcoreapp3.0\MyWebApp.dll" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\MyWebApp.dll".
Copying file from "c:\Dev\MyWebApp\MyWebApp\appsettings.json" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\appsettings.json".
Copying file from "c:\Dev\MyWebApp\MyWebApp\bin\Release\netcoreapp3.0\MyWebApp.runtimeconfig.json" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\MyWebApp.runtimeconfig.json".
Copying file from "c:\Dev\MyWebApp\MyWebApp\appsettings.Development.json" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\appsettings.Development.json".
Copying file from "C:\Users\astanton\.nuget\packages\elasticsearch.net\6.8.3\lib\netstandard2.0\Elasticsearch.Net.dll" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\Elasticsearch.Net.dll".
Copying file from "c:\Dev\MyWebApp\MyWebApp\bin\Release\netcoreapp3.0\MyWebApp.deps.json" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\MyWebApp.deps.json".
Copying file from "C:\Users\astanton\.nuget\packages\MyPrivatePackage1\1.3.0.1\lib\netstandard1.1\MyPrivatePackage1.dll" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\MyPrivatePackage1.dll".
Copying file from "C:\Users\astanton\.nuget\packages\MyPrivatePackage2\1.0.0.4\lib\netstandard2.0\MyPrivatePackage2.dll" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\MyPrivatePackage2.dll".
Copying file from "C:\Users\astanton\.nuget\packages\nest\6.8.3\lib\netstandard2.0\Nest.dll" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\Nest.dll".
Copying file from "c:\Dev\MyWebApp\MyWebApp\obj\Release\netcoreapp3.0\MyWebApp.exe" to "c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\MyWebApp.exe".
MyWebApp -> c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\
No web.config found. Creating 'c:\Dev\MyWebApp\MyWebApp\obj\Docker\publish\web.config'
docker-compose  -f "c:\Dev\MyWebApp\docker-compose.yml" -f "c:\Dev\MyWebApp\docker-compose.override.yml" -p dockercompose6603008454795844700 --no-ansi build MyWebApp
Building MyWebApp
Step 1/17 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
 ---> 930743cb4e19
Step 2/17 : WORKDIR /app
 ---> Using cache
 ---> 24000994bfd8
Step 3/17 : EXPOSE 80
 ---> Using cache
 ---> d9e16143e853
Step 4/17 : EXPOSE 443
 ---> Using cache
 ---> eabbbafdd677
Step 5/17 : FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
 ---> 170a7f2ec51a
Step 6/17 : WORKDIR /src
 ---> Using cache
 ---> 723b938fcf0d
Step 7/17 : COPY ["MyWebApp/MyWebApp.csproj", "MyWebApp/"]
 ---> e3dda75f6212
Step 8/17 : RUN dotnet restore "MyWebApp/MyWebApp.csproj"
 ---> Running in 0037f21e993e
/src/MyWebApp/MyWebApp.csproj : error NU1101: Unable to find package MyPrivatePackage2. No packages exist with this id in source(s): nuget.org
/src/MyWebApp/MyWebApp.csproj : error NU1101: Unable to find package MyPrivatePackage1. No packages exist with this id in source(s): nuget.org
  Restore failed in 2.34 sec for /src/MyWebApp/MyWebApp.csproj.
Service 'MyWebApp' failed to build: The command '/bin/sh -c dotnet restore "MyWebApp/MyWebApp.csproj"' returned a non-zero code: 1
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(127,5): Error DT1001: Service 'MyWebApp' failed to build: The command '/bin/sh -c dotnet restore "MyWebApp/MyWebApp.csproj"' returned a non-zero code: 1
```

**Comment by bwateratmsft** [comment]
Thanks. Can you try doing Clean, then Publish again? At the time it built last the Dockerfile may not have had the `COPY ["NuGet.config", "MyWebApp/"] # Manually addded from the example in this issue` step, as it was skipped in this `docker build` output.

**Comment by moisoiu** [comment]
Or even better just do it like this 

Before add this line
`
COPY nuget.config ./`

and after that at Restore add the line from below

`RUN dotnet restore "MyWebApp/MyWebApp.csproj"  --configfile nuget.config`

**Comment by StingyJack** [comment]
Sorry, I've confused things just a bit by renaming the original dockerfile that had the edit in it (and that was still open in the editor). The regenerated dockerfile that had been getting executed did not that the COPY in it. Adding the COPY command to the correct dockerfile and republishing gives me a different error. 

```
Step 8/18 : COPY ["NuGet.config", "MyWebApp/"] # Manually addded
Service 'MyWebApp' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder226796934/NuGet.config: no such file or directory
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(127,5): Error DT1001: Service 'MyWebApp' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder226796934/NuGet.config: no such file or directory
```

@moisoiu  - i dont understand where you mean for me to add that COPY statement in the file

**Comment by moisoiu** [comment]
@StingyJack  I bolded what you need to do 


`FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /src
**COPY nuget.config ./**
COPY ["MyWebApp/MyWebApp.csproj", "MyWebApp/"]
COPY ["NuGet.config", "MyWebApp/"] # Manually addded from the example in this issue
**RUN dotnet restore "MyWebApp/MyWebApp.csproj" --configfile nuget.config**
COPY . .
WORKDIR "/src/MyWebApp"
RUN dotnet build "MyWebApp.csproj" -c Release -o /app/build`

**Comment by bwateratmsft** [comment]
It looks like that `COPY` failed:
1. Most likely: case-sensitivity. `COPY` is case sensitive even on Windows; owing to the fact that Docker is actually running in a Moby VM (also why that root path "/var/lib/docker/tmp/docker-builder226796934/" is not a Windows path). Check that the casing of NuGet.config exactly matches what's in the `COPY` statement. In contrast, MSBuild is not case-sensitive about NuGet.config (even on Linux IIRC), so it still works when building locally.
1. Is the NuGet.config present at the root of the build context (one level up from MyWebApp.csproj)?
1. Less likely: NuGet.config (or, *.config, etc.) was part of .dockerignore. It's not scaffolded that way by default but if it was modified that could be the case.

**Comment by StingyJack** [comment]
If you had told me before Y2K that non-legacy *nix filesystems would stilI be case sensitive in 2020, I would not have believed it. The IT community still tolerating such a needless expense like a case sensitive file system for this long is just embarrassing.

Recasing the filename fixed that problem, but now it cant auth to azure artifacts. I dont think I care about that at this point because this dockerfile is only for debugging the app, and I dont need to debug an app in a container that I can run locally without the container (unless you can convince me otherwise).  I'd rather use msbuild to build (since it can build this and the other projects in the solution) and have a dockerfile for packaging that output. 

Thanks for the assistance though, I do appreciate not being stuck for days/weeks on docker related issues.

**Comment by moisoiu** [comment]
@StingyJack read this and good luck https://github.com/microsoft/artifacts-credprovider/issues/63

**Comment by flcdrg** [comment]
How does this work when running in Visual Studio? My application is using Azure Artifacts feeds that require a PAT (personal access token)

Is there a way to pass in a PAT or prompt for credentials that can be used by docker build / docker-compose build?

**Comment by StingyJack** [comment]
@flcdrg  VS should use your current credentials to access Azure DevOps resources. (Except where there is an explicit login like SQL connections.)

**Comment by flcdrg** [comment]
Even from a build running inside a container?

**Comment by StingyJack** [comment]
@flcdrg sorry wasn't thinking of that case, I turned that all off because development debugging with a whole container seemed unnecessary for me. The link that @moisoiu shared above may work for you if something like an environment variable doesn't.

**Comment by dbreshears** [comment]
Instructions are here https://github.com/dotnet/dotnet-docker/blob/main/documentation/scenarios/nuget-credentials.md for this.  Closing as this is stale
