### ISSUE TITLE
Unable to start debugging Docker container

### ISSUE THREAD

**Issue by PawLove** [Microsoft/DockerTools#17]
Hi! I'm trying out the Visual Studio 2017 Community and ASP.NET Core web app and get a prompt stating "Unable to start debugging. Unable to establish a connection to VSDBG. Debug output may contain more information."

Output Windows shows the following:

Starting: "docker" exec -i dd11077d4248 /clrdbg/vsdbg/vsdbg --interpreter=mi
rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"/clrdbg/vsdbg/vsdbg\": stat /clrdbg/vsdbg/vsdbg: no such file or directory"
"docker" exited with code 126 (0x7E).

I saw that a similar problem was being discussed
https://github.com/dotnet/dotnet-docker/issues/162
But the solution did not help.

## Steps to reproduce the issue
1.Open VS 2017 Community
2.Create new ASP.NET Core Web App
3.Debug with Docker

## Expected behavior
Should run app in container and allow breakpoints, etc.

## Actual behavior
It prompts with error mentioned above. It does appear to deploy and run a container.

## Output of `docker version`
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true

## Output of `docker info`
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: 2NIF:L7XL:JNC7:UIWV:VCGX:KBZU:MITL:43VJ:X3VR:DWKL:BZAO:TXP6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 32
 System Time: 2017-05-22T17:19:35.5988348Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by stepandohnal** [comment]
See output from build if there are not any errors.

**Comment by ivan-danilov** [comment]
Same issue here

**Comment by radulacatus** [comment]
i had the same issue
for me it worked running docker for windows as admin

**Comment by Emill** [comment]
I installed vs2017 update 3 preview and now it works.

**Comment by pwasiewicz** [comment]
Same here. But none of both helped: running doker daemon as admin nor installing vs2017 preview 3.

**Comment by kenpavia** [comment]
I was getting this error while on a vpn.  I jumped off the vpn and the debug error went away (after a reboot).  Now, I have to figure out why being on a vpn causes the problem.

**Comment by liqdfire** [comment]
I have my machine joined to an Azure AD, and my windows login is my AAD account, not a local account.
I had to create a local user account for sharing drive in docker; however, the docker tools in VS2017 use the profile directory of the logged in user as the path for clrdbg and .nuget, which the local account would not have access to.

See this issue for other symptoms
https://github.com/docker/for-win/issues/898

To resolve it, I have to give the local user account that I am using to share drive in docker, read access to my logged in user profile directory. You will need read and write if you are using the default git repo folder of source\repos under y our profile directory.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
