### ISSUE TITLE
How docker compose project name is generated

### ISSUE THREAD

**Issue by brunobertechini** [microsoft/DockerTools#171]
Hello, I would like to know how this parameter (compose project name) is generated.

-p dockercompose12415008673026106123

Also, is it stored/configured some how?

**Comment by bwateratmsft** [comment]
The project name is composed of two parts.  In your example,
dockercompose : this is the file name without extension of the dcproj (the dash is removed--see below)
12415008673026106123: this is a non-cryptographic hash of the workspace directory; i.e. the location of the dcproj

The two are concatenated, and then non-alphanumeric characters (like the dash) are removed.

This value is not configurable.

**Comment by stromsky** [comment]
Any plans to make it configurable?

**Comment by bwateratmsft** [comment]
Yes, we are actually working on that now for 16.4. By default we will be using the project name (sanitized for spaces/alphanumeric/etc.) as the container name, but you can override it by providing a container name in docker-compose.yml or docker-compose.override.yml.

**Comment by stromsky** [comment]
It would be more convenient to be just able to specify explicitly what value should be passed to `docker-compose` `-p` argument. This is used as a prefix not just for container names, but also volumes and networks. 

In my case, constant network name across multiple development machines is what I am after. For now I've ended up with external network which must be created manually (not an ideal solution).

**Comment by caseycesari** [comment]
Hello. Any updates on this? I'd also like to be able to configure this value (and have it use the values specified in the docker-compose file).

**Comment by mrjrt** [comment]
I've just discovered I can't have two stacks talking to each other (or indeed, a debug one talking to a non-debug one) using the automatic projectname-based network, which is a pain, as it means adding in hard-coded ones. Please consider a configurable property in the dcproj.

**Comment by BitzArt** [comment]
Would like to have docker-compose project name configurable. We are sharing the project between several developers and having the project have a different name on every developer's device does not allow us to write scripts properly. @bwateratmsft Not seeing this in 16.4 release, am I missing something?

**Comment by dbreshears** [comment]
Added this to our backlog and will look at making this configurable in 16.9

**Comment by pratiksanglikar** [comment]
A fix for this issue has been implemented internally and would be available for download in 16.9.

**Comment by fuzzybair** [comment]
@pratiksanglikar I just updated to Version 16.9.1 and added <DockerComposeUpArguments>-p MyProject</DockerComposeUpArguments> to the dcproj file.  but it still generated  -p myprojectdockercompose12449342703230600049 did this fix not make 16.9 or do you have an example on how to set the name correctly?

**Comment by pratiksanglikar** [comment]
Hi @fuzzybair,
You can specify the project name using property - `<DockerComposeProjectName>my-docker-compose-project</DockerComposeProjectName>`.

**Comment by iambenjamin-developer** [comment]
> Hi @fuzzybair, You can specify the project name using property - `<DockerComposeProjectName>my-docker-compose-project</DockerComposeProjectName>`.

Just to clarify: You should add the new tag in the file  **_docker-compose.dcproj_**  inside of PropertyGroup.
For example:
```
  <PropertyGroup Label="Globals">

    <ProjectVersion>2.1</ProjectVersion>
    <DockerTargetOS>Linux</DockerTargetOS>
    <ProjectGuid>ccbe786b-4cdc-446d-9aeb-23087e50f34d</ProjectGuid>
    <DockerLaunchAction>LaunchBrowser</DockerLaunchAction>
    <DockerServiceUrl>{Scheme}://localhost:{ServicePort}/swagger</DockerServiceUrl>
    <DockerServiceName>miproyecto</DockerServiceName>

    <DockerComposeProjectName>my-docker-compose-project</DockerComposeProjectName>

  </PropertyGroup>
```
