### ISSUE TITLE
How do I add Certificate pfx to my Image?

### ISSUE THREAD

**Issue by abhishek-raj** [microsoft/DockerTools#172]
I want to add an certificate pfx to my Docker Image which authenticates with Azure Keyvault to get some secret values. I imported the certificate using DockerFile into the LocalMachine/My but my dotnet MVC application is not able to access it. It shows a `Keyset does not exist` error. The problem is probably of permissions as the IIS runs with some other Service Account which might not have access to the Private Machine Key.

Is there a way to add the Certificate to the Docker Image?

**Comment by dbreshears** [comment]
This is out of scope for the VS container tooling
