### ISSUE TITLE
Allow dockerizing full .NET Framework Console App

### ISSUE THREAD

**Issue by jakubsuchybio** [microsoft/DockerTools#175]
Hi,
it is kinda weird, that we are allowed to create docker-compose from UI for .NET Framework Console App, but we are not allowed to just dockerize it.

Having support to run just that one Console app with Debugger would be much appreciated.

Thanks!

**Comment by dbreshears** [comment]
Thank you for the feedback as we do rely on it to help prioritize features. We did investigate enabling this but due to the architecture of the C# .Net Framework project system the amount of effort is quite large. As you likely know, we do support this for .NET Core console projects.
