### ISSUE TITLE
Cannot disable Thread Exit Messages in Output window

### ISSUE THREAD

**Issue by mikesigs** [microsoft/DockerTools#176]
This issue affects both Visual Studio 2017 and 2019.

When running our application with docker-compose, the Output window get's filled with `The thread 1234 has exited with code 0 (0x0).` messages. Disabling Thread Exit Messages does not seem to help. Well, not entirely. It does turn off _some_ of the thread exit messages, but not all.

Before disabling Thread Exit Messages

```
The thread 0x2f1 has exited with code 0 (0x0).
The thread 754 has exited with code 0 (0x0).
The thread 0x2f2 has exited with code 0 (0x0).
The thread 755 has exited with code 0 (0x0).
The thread 0x2f3 has exited with code 0 (0x0).
The thread 756 has exited with code 0 (0x0).
The thread 0x2f4 has exited with code 0 (0x0).
The thread 757 has exited with code 0 (0x0).
The thread 0x2f5 has exited with code 0 (0x0).
```

After disabling Thread Exit Messages

```
The thread 758 has exited with code 0 (0x0).
The thread 759 has exited with code 0 (0x0).
The thread 760 has exited with code 0 (0x0).
The thread 761 has exited with code 0 (0x0).
The thread 762 has exited with code 0 (0x0).
The thread 763 has exited with code 0 (0x0).
The thread 764 has exited with code 0 (0x0).
The thread 765 has exited with code 0 (0x0).
```

So the `0xddd` related messages disappear, but the others remain. 

I _think_ the source of the messages is NServiceBus doing frequent peek checks at the SQL-based queues looking for new messages.

I have confirmed this is not going through our Log Provider, since it does not follow the message format of a log message, i.e. no timestamp, log level, etc. So it must be coming directly from the docker output or something.

Here's a gif to show how truly annoying this is. It makes it **very** difficult to see relevant log messages.

![thread-exit-messages](https://user-images.githubusercontent.com/811177/55574335-68500280-56c9-11e9-9511-d03fc447bba8.gif)

**Comment by gregg-miskelly** [comment]
Can you grab a log of the debugger messages being exchanged while this is happening? https://github.com/Microsoft/VSDebugAdapterHost/wiki/Logging

**Comment by mikesigs** [comment]
I created a simple console app to reproduce the issue.
https://github.com/mikesigs/CannotDisableThreadExitMessages

It's very straightfoward. I created a .NET Core Console app using VS 2019.

```csharp
using System.Threading;

namespace CannotDisableThreadExitMessages
{
    internal static class Program
    {
        private static void Main()
        {
            for (int i = 0; i < 10; i++)
            {
                var t = new Thread(DoStuff);
                t.Start();
            }
        }

        private static void DoStuff()
        {
            Thread.Sleep(50);
        }
    }
}
```

I captured two log files. One with the *Thread Exit Messages* enabled, and one with it disabled. The log files look the same, although the output in the console was not. When *Thread Exit Messages* are enabled you see a set of messages per thread exit. With the option _disabled_ you just see one message.

### Log Files
[Thread Exit Messages Disabled](https://raw.githubusercontent.com/mikesigs/CannotDisableThreadExitMessages/master/debug-log-with-thread-exit-messages-disabled.txt)

[Thread Exit Messages Enabled](https://raw.githubusercontent.com/mikesigs/CannotDisableThreadExitMessages/master/debug-log-with-thread-exit-messages-enabled.txt)

**Comment by gregg-miskelly** [comment]
Thanks @mikesigs I see the problem. This is an issue with the cross-platform .NET Core debugger (which my team owns). I will try to fix this for our next version. It updates out-of-band and automatically, so you should see the fix when we next ship.

**Comment by mikesigs** [comment]
Thanks @gregg-miskelly! Looking forward to it :)

Should this issue be moved to the .NET Core Debugger repo?

**Comment by gregg-miskelly** [comment]
If there was one, yes. But the .NET Core Debugger is a closed source product. So there isn't really a good place to leave this.

**Comment by petrnymsa** [comment]
Just to note: VS 2019 Community,version 16.1.3 still relevant

**Comment by bwateratmsft** [comment]
This should be fixed now in the latest releases of VSDBG which will be automatically downloaded (it may already have been).
