### ISSUE TITLE
Windows 7 - Docker Toolbox and Virtualbox - Unable to mount volume

### ISSUE THREAD

**Issue by pleandre** [microsoft/DockerTools#177]
Hello All,

When I try to run the sample ASP.Net Core Docker application with Visual Studio plugin on Windows 7 / Docker Toolbox / Virtual Box, Docker seems unable to mount the volume.

Build output:
```
1>docker run -dt -v "C:\Users\pleandre\vsdbg\vs2017u5:/remote_debugger:rw" -v "C:\Workspace\tests\dotnetcore-docker-webapi:/app" -v "C:\Users\pleandre\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" -v "C:\Users\pleandre\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Program Files (x86)\NuGet\Packages:/root/.nuget/fallbackpackages" -v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages2" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=https://+:443;http://+:80" -e "ASPNETCORE_HTTPS_PORT=44337" -e "NUGET_PACKAGES=/root/.nuget/fallbackpackages" -e "NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages;/root/.nuget/fallbackpackages2" -p 62930:80 -p 44337:443 --entrypoint tail dotnetcore-docker-webapi:dev -f /dev/null
1>docker: Error response from daemon: invalid volume specification: 'C:\Users\pleandre\vsdbg\vs2017u5:/remote_debugger:rw'.
```

I have shared my C drive by changing the settings of my Docker machine in Virtual Box.
After that, I can make the command above work if I replace all the volume paths
C:\Workspace\....
by /c/Workspace/

My question is, is there any way to automatically have all paths changed from Windows to Unix style with Visual Studio plugin when I click on the run button  ?

I guess if you run docker with Hyper V the paths should stay in Windows style, and if you run it in Virtual Box with the Boot2Docker.iso image / mapping your C drive the paths should switch to Unix style.
For docker compose I think there could be a solution with environment variable "COMPOSE_CONVERT_WINDOWS_PATHS" but for docker run command it doesn't seems available.

Did anyone face the same issue ?
Thanks a lot,
Kind regards,
Pierre

**Comment by sgreenmsft** [comment]
Hi pleandre.  Unfortunately at this time the VS container tools require Docker Desktop.

I suppose as an (extremely ugly) workaround for fixing these paths you could create a wrapper for docker.exe -- that is, write a docker.bat or a docker.exe that takes the incoming arguments, finds the Windows-style paths, converts them to Unix-style, and then calls the real docker.exe.  You could then put that in your PATH somewhere ahead of the real docker.exe's folder and VS would execute your script instead of docker.exe.

**Comment by pleandre** [comment]
Hi sgreenmsft,

Thanks a lot for your suggestion, I will try to create a wrapper.
In the future it would be nice to have a way to switch from Windows to Linux path style, maybe in the  "Container.targets" file provided by VS Container tool using a MSBuild parameter.

e.g. adding something similar to bellow code to Container.targets
<PropertyGroup Condition=" '$(DockerPathFormat)' == 'Unix' ">
    <DevEnvDir>$([System.String]::Copy('/%(Filename)').Replace(':', '').Replace('\\', '/'))</DevEnvDir>
</PropertyGroup>

I just wrote the code above quickly and didn't check the syntax or if DevEnvDir was the proper variable but I think it should be possible.

This way we could call dotnet build /p:DockerPathFormat=Unix and have the plugin work with non Hyper-V systems.

Best regards,
Pierre

**Comment by pleandre** [comment]
Hi sgreenmsft,

Thanks a lot for your suggestion, I will try to create a wrapper.
In the future it would be nice to have a way to switch from Windows to Linux path style, maybe in the  "Container.targets".

e.g. adding something similar to bellow code to Container.targets
```xml
<PropertyGroup Condition="'$(DockerPathFormat)' == 'Unix'">
    <DevEnvDir>$([System.String]::Copy('/%(DevEnvDir)').Replace(':', '').Replace('\\', '/'))</DevEnvDir>
</PropertyGroup>
```
Or add an option to task ```Microsoft.VisualStudio.Containers.Tools.Shared.PrepareForLaunch```

I just wrote the code above quickly and didn't check the syntax or if DevEnvDir was the proper variable but I think it should be possible.

This way we could call ```dotnet build /p:DockerPathFormat=Unix``` and have the plugin work with non Hyper-V systems.

I can see this target file is included in NuGet package ```Microsoft.VisualStudio.Azure.Containers.Tools.Targets```
I think a clean solution would be either to change this package and release a new version or create a new package for this purpose.

Best regards,
Pierre

**Comment by pleandre** [comment]
Hello @sgreenmsft,

As you proposed I created a cmd file to wrap Docker and override volume paths:
https://gist.github.com/pleandre/fd27115675ddd85169b8d79a2c50944d

Unfortunately, Visual Studio doesn't seems to pick it up even when setting it higher in the path than the original Docker.

Also the solution above with msbuild targets cannot work as most volume paths are defined in the closed source code from ```Microsoft.VisualStudio.Containers.Tools.Shared.PrepareForLaunch``` and it doesn't seems possible to override them easily.

Could you in a future release include an option to change the volume path from windows to unix ?

Thank you,
Pierre

**Comment by pleandre** [comment]
Hello @sgreenmsft,

As you proposed I created a cmd file to wrap Docker and override volume paths:
https://gist.github.com/pleandre/fd27115675ddd85169b8d79a2c50944d

Unfortunately, Visual Studio doesn't seems to pick it up even when setting it higher in the path than the original Docker.

Also the solution in my previous comment with msbuild targets cannot work as most volume paths are defined in the closed source code from ```Microsoft.VisualStudio.Containers.Tools.Shared.PrepareForLaunch``` and it doesn't seems possible to override them easily.

Could you in a future release of [Microsoft.VisualStudio.Azure.Containers.Tools.Targets](https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/) include an option to change the volume path from Windows to Unix ?

Thank you,
Pierre

**Comment by pleandre** [comment]
I made it work using docker compose. Only standard docker doesn't work.
