### ISSUE TITLE
Alpine 3.9 AspNetCore 2.2.4 "The debug adapter exited unexpectedly"

### ISSUE THREAD

**Issue by valeriob** [Microsoft/DockerTools#179]
Hi,
to reproduce the problem, create an aspnetcore application targeting 2.2, add docker support, switch to apline images FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine3.9 AS base

put a break point, when the process reaches the breakpoint it crashes, if you do not put any breakpoint it works.

**Comment by sgreenmsft** [comment]
Support for debugging alpine images is included in VS2019.  In VS2017 there are some manual steps and workarounds required to get alpine debugging working.

@bwateratmsft - Could you provide the necessary steps for VS2017?

**Comment by valeriob** [comment]
oh i'm sorry, i'm on visual studio 16.0.1.
But rebuilding the image made it work, sorry for bothering.

**Comment by bwateratmsft** [comment]
@sgreenmsft @valeriob I'll provide the VS2017 steps for posterity.

1. Change your runtime and SDK image names to Alpine ones, i.e. from `microsoft/dotnet:2.1-aspnetcore-runtime` to `mcr.microsoft.com/dotnet/core/aspnet:2.1-alpine`, and `microsoft/dotnet:2.1-sdk` to `mcr.microsoft.com/dotnet/core/sdk:2.1-alpine`. (@valeriob has already done this)
2. In the project file or NuGet package manager, ensure the reference to **Microsoft.VisualStudio.Azure.Containers.Tools.Targets** is to version **>= 1.4.10**.
3. For easiest experience, hit F5 now. It will build your Docker image, but debugging will not work. **Importantly, though, it will download the Alpine VSDebug to a subpath under the usual location.** In the Build output window, you should see something like `1>Info: Successfully installed vsdbg at 'C:\Users\UserName\vsdbg\vs2017u5\linux-musl-x64'`. You can skip this step if you already have the Alpine debugger downloaded elsewhere.
4. In your project file, add the following property to a PropertyGroup:
`<ContainerVsDbgPath>$(UserProfile)\vsdbg\vs2017u5\linux-musl-x64</ContainerVsDbgPath>`
If you're using a custom path for the Alpine debugger, use that path here instead.
5. F5 and enjoy!
