### ISSUE TITLE
Cannot run Docker in debug mode

### ISSUE THREAD

**Issue by chrisahardie** [Microsoft/DockerTools#18]
I have created a brand new Web API .Net Core application. Without touching anything, if I attempt to debug with Docker, I get the following message:

>WARNING: The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use NETStandard 1.0.0-rc3-23829 or newer. This may be expected if the target process did not run .NET code.

My Dockerfile is as follows:

```
FROM microsoft/aspnetcore:1.1
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "WebApplication1.dll"]
```

In the Output window, I get the following:

```
--------------------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with Visual Studio
Code, Visual Studio or Visual Studio for Mac software to help you develop and
test your applications.
--------------------------------------------------------------------------------
realpath(): Invalid argument
realpath(): Invalid argument
Error: assembly specified in the dependencies manifest was not found -- package: 'system.diagnostics.stacktrace', version: '4.3.0', path: 'lib/netstandard1.3/System.Diagnostics.StackTrace.dll'
The program '' has exited with code 140 (0x8c).
```

My image is created:
```
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
webapplication1        dev                 bb0b993853af        5 minutes ago       305 MB
```

It appears I can't attach my debugger to my container - anyone have any thoughts as to why?

Thanks!

**Comment by dazhao-msft** [comment]
Looks like your base image is in a strange stage. Please run 'docker pull microsoft/aspnetcore:1.1' to force update it on your local machine and see if it works. Also please share the VS version and Docker for Windows version so we may have a better idea about what's wrong.

**Comment by rukstar007** [comment]
I have the same issue, the output window message is below:
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
realpath(): Stale file handle
realpath(): Invalid argument
realpath(): Invalid argument
realpath(): Invalid argument
Error: assembly specified in the dependencies manifest was not found -- package: 'Microsoft.ApplicationInsights.AspNetCore', version: '2.1.0', path: 'lib/netstandard1.6/Microsoft.ApplicationInsights.AspNetCore.dll'
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[109] dotnet' has exited with code 140 (0x8c).
The program '' has exited with code 140 (0x8c).

I can pull the images from the docker

PS C:\WINDOWS\system32> docker pull microsoft/aspnetcore:1.1
1.1: Pulling from microsoft/aspnetcore
Digest: sha256:b48590ebcbe963d901158998f59ea1cbf2fa0517623d13540b8c41c2fbc101a5
Status: Image is up to date for microsoft/aspnetcore:1.1
PS C:\WINDOWS\system32> docker images
REPOSITORY             TAG                 IMAGE ID            CREATED             SIZE
identity               dev                 9acf9f3e30e9        21 hours ago        333MB
microsoft/aspnetcore   2.0                 709d186c3bf0        22 hours ago        299MB
microsoft/aspnetcore   1.1                 0e0ee3cea478        22 hours ago        333MB
hello-world            latest              f2a91732366c        4 weeks ago         1.85kB
microsoft/aspnetcore   2.0.0               9ef915cc938f        5 weeks ago         280MB
d4w/nsenter            latest              9e4f13a0901e        15 months ago       83.8kB
PS C:\WINDOWS\system32>
 
How can i fix this ?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
