### ISSUE TITLE
Cannot start Docker debug with VS2017 15.39.11

### ISSUE THREAD

**Issue by tutul2010** [microsoft/DockerTools#182]
Hi All

I am running with windows docker on windows server 2016 (64 bit) with docker enable.
I created a traditional mvc web app with 4.6.1 frmwrk(Vs2017 IDE).It is not running 
Below error is coming
![error1](https://user-images.githubusercontent.com/13733464/56092879-a0342280-5edf-11e9-938e-85b88d751129.JPG)

docker file are  below
![docker-compose](https://user-images.githubusercontent.com/13733464/56092884-ad511180-5edf-11e9-8bf2-18b0e94a4617.JPG)
![docker-compose overrides](https://user-images.githubusercontent.com/13733464/56092885-ade9a800-5edf-11e9-89f5-e2717df03844.JPG)

Pls suggest ..what to do for fix..
Thanks,

**Comment by dbreshears** [comment]
@tutul2010.   I walked through the same on latest 15.9 and didn't encounter any issues.  Can you share the ActivityLog.xml that it is pointing too.

**Comment by tutul2010** [comment]
Thanks @dbreshears  for your replay...
Here is mine ActivityLog.xml  as attachment .
[ActivityLog.txt](https://github.com/Microsoft/DockerTools/files/3081306/ActivityLog.txt)

one thing , for dotnet-core app ,it is working fine with images and windows container.
But normal mvc app(dotnet 4.6.1 framewrk) gave exception.

 Thanks,

**Comment by dbreshears** [comment]
Hmm.. Seems to be related to the error list and an exception in the shell getting the build order list in response to task list changes.   Not anything we have seen specific to being "dockerized". Does this occur if in a non-dockerized 4.6.1 MVC project?  

Does this work 

1. Create a non-dockerized 4.6.1 MVC project
2. F5 and close browser
3. Right click and "Add Container Orchestration " from the Webapplication context menu and choose Docker Compose
4. Build or F5

Did you recently upgrade and can you try to repair VS?

**Comment by tutul2010** [comment]
Thanks @dbreshears for your replay...
I created a mvc app on . NET framework 4.6.1 without docker by vs2017-community IDE and it is running fine.
When i clicked at solution and looking for docker support for app , it is not showing .I don't know why?
![dockerPlugin](https://user-images.githubusercontent.com/13733464/56227288-c221d680-6092-11e9-9afa-73b905787e7e.jpg)

Should i repair VS2017 again or upgrade or need to install other plugin?
Thanks,

**Comment by sgreenmsft** [comment]
@tutul2010, You'll need to click "Container Orchestrator Support" and choose "Docker-Compose"

**Comment by tutul2010** [comment]
Thanks @sgreenmsft  for your replay...
I did what u told and got an error as below. Mvc App is not running with docker support.
![dockerPlugin02](https://user-images.githubusercontent.com/13733464/56228198-d9fa5a00-6094-11e9-94cd-d00dfa9a1285.JPG)
Below is my OS docker version info..
![doker-versionFull](https://user-images.githubusercontent.com/13733464/56228279-1463f700-6095-11e9-8ce9-a3c5bb0724a0.JPG)
Any thing am i missing for .NET app with docker?

Thanks,

**Comment by sgreenmsft** [comment]
For Windows Server you'll need to install Docker-Compose separately.  Installation instructions are available here: https://docs.docker.com/compose/#install-compose

**Comment by tutul2010** [comment]
Thanks @sgreenmsft for your replay...
I am installing that for win-server 2016 OS at vm and let u know

**Comment by tutul2010** [comment]
Thanks @sgreenmsft .
 now i can create a docker of  .net 4.6 app and run at win container.
Thanks,

**Comment by pratiksanglikar** [comment]
@tutul2010 , I believe the solution worked for you, so closing this issue.
Please feel free to open another issue if the problem persists.
