### ISSUE TITLE
Unable to debug Docker container with custom image

### ISSUE THREAD

**Issue by m0a0k0s** [Microsoft/DockerTools#183]
Not possible to start docker project debug from visual studio with custom source image from private repository. DockerFile

FROM gitlab_registry_path
ARG source
WORKDIR /app
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "host.dll"]

Result: Operation aborted 0x80004004 (E_ABORT) private
VS 15.9.11

last event in docker
container exec_create: /remote_debugger/vsdbg --interpreter=vscode ad820b6d75f7ebf2663ab53608efff45d6a932b3f52eddeb8b07f45f1b1992aa (com.docker.compose.config-hash=4251d6addffad808e26bebaa87c3cc8eddbd0c80654bb9012a5fb14421f3ecc0, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=dockercompose15537581942804585634, com.docker.compose.service=host, com.docker.compose.version=1.23.2, com.microsoft.visualstudio.debuggee.arguments= --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.1/Host.dll, com.microsoft.visualstudio.debuggee.killprogram=/bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi", com.microsoft.visualstudio.debuggee.program=dotnet, com.microsoft.visualstudio.debuggee.workingdirectory=/app, execID=582b7d1b965bf50a0d5212875d32cf8970f5341a8a945995cc51214300728294, image=host:dev, name=dockercompose15537581942804585634_host_1)

**Comment by bwateratmsft** [comment]
@m0a0k0s What is this image based from? What is the behavior--does it seem to do nothing, or does it show an error, etc.?

**Comment by m0a0k0s** [comment]
This image was created from standard microsoft .NET Core Runtime image with several files added, after running docker-compose project with F5 build process completes successfully, debug process find appropriate container id and then shows message box with error "Operation aborted 0x80004004 (E_ABORT)"

**Comment by bwateratmsft** [comment]
Based on the kill command it looks like a Linux image, which one in particular is it based from?

**Comment by m0a0k0s** [comment]
Tried with both:
microsoft/dotnet:2.1-aspnetcore-runtime
microsoft/dotnet:2.1-sdk

**Comment by bwateratmsft** [comment]
This Dockerfile looks like one created for .NET Framework, not .NET Core. For instance, here's a .NET Core one:
```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY WebApplication3/WebApplication3.csproj WebApplication3/
RUN dotnet restore WebApplication3/WebApplication3.csproj
COPY . .
WORKDIR /src/WebApplication3
RUN dotnet build WebApplication3.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish WebApplication3.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "WebApplication3.dll"]
```
And here's a .NET Framework one:

```
FROM microsoft/aspnet:4.7.2-windowsservercore-1803
ARG source
WORKDIR /inetpub/wwwroot
COPY ${source:-obj/Docker/publish} .
```
First, can you ensure your project is actually a .NET Core project (what's inside the <TargetFramework> or <TargetFrameworks> property in the csproj)? .NET Framework projects cannot run on Linux containers.
Second, if it is a .NET Core project, can you change your Dockerfile to more closely resemble the one above, and see what happens?

**Comment by m0a0k0s** [comment]
Yes, project is .NET Core, have just used this type of DockerFile style. Tried with .NET Core docker file same result, when use microsoft image vs debugging works, when use custom image debug failed. Manually running with docker-compose up works with any base image.

**Comment by bwateratmsft** [comment]
In that case, something about your image is either preventing the debugger from launching, or is crashing it. Are you able to share how that image gets built?

**Comment by m0a0k0s** [comment]
this is a source DockerFile for creating image 

FROM alpine:3.9

ARG VERSION

ENV DOTNET_RT_VERSION=${VERSION} \
    DOTNET_RUNNING_IN_CONTAINER="true" \
    HOME="/root" \
    ASPNETCORE_URLS="http://+:80" \
    DOTNET_CLI_TELEMETRY_OPTOUT="false" \
    DOTNET_USE_POLLING_FILE_WATCHER="true" 
  
    
RUN apk update && \
    apk add --no-cache bash curl openssl libc6-compat libcurl libgcc krb5-libs icu-libs lttng-ust-dev libstdc++ libunwind libuuid zlib libintl && \
    curl -sSL https://dot.net/v1/dotnet-install.sh | /bin/bash /dev/stdin --version $DOTNET_RT_VERSION --shared-runtime && ln -s /root/.dotnet/dotnet /usr/bin/dotnet

WORKDIR /app

ADD wait-for-it.sh ./

**Comment by bwateratmsft** [comment]
> FROM alpine:3.9

There's the problem. Alpine debugging is not supported in 15.9.11. You will need to upgrade to VS2019, or, [here](https://github.com/Microsoft/DockerTools/issues/179#issuecomment-482178661) are some steps that might help for VS2017.

**Comment by m0a0k0s** [comment]
Thank you for information, I will upgrade to new version.
