### ISSUE TITLE
Cannot start Docker debug with VS2019 in china

### ISSUE THREAD

**Issue by sunliusi** [microsoft/DockerTools#186]
I can't start docker with vs2019.
Debug form GetVsDbg.ps1, i can't download vsdbg from https://vsdebugger.azureedge.net/  in china. 
Is there any other way to do it.

**Comment by sgreenmsft** [comment]
I'm not sure how to download vsdbg in China, but would it be possible to switch to using Windows containers instead of Linux containers?  The Windows containers do not require downloading vsdbg.

**Comment by lv-conner** [comment]
we can down the required zip file .it cause vs wait in here and can not skip. that was stupid。

**Comment by nocanstillbb** [comment]
Determining user folder on remote system...
Checking for existing installation of debugging tools...
Downloading debugger launcher...
Creating debugger installation folder: /root/.vs-debugger
Copying debugger launcher to /root/.vs-debugger/GetVsDbg.sh
Ensuring script exists after copying...
Downloading debugger components...
Output: Info: Previous installation at '/root/.vs-debugger/vs2019' not found
Info: Using vsdbg version '16.3.10904.1'
Using arguments
    Version                    : 'vs2019'
    Location                   : '/root/.vs-debugger/vs2019'
    SkipDownloads              : 'false'
    LaunchVsDbgAfter           : 'false'
    RemoveExistingOnUpgrade    : 'false'
Info: Using Runtime ID 'linux-x64'
Downloading https://vsdebugger.azureedge.net/vsdbg-16-3-10904-1/vsdbg-linux-x64.zip
ERROR: Command 'unzip' not found. Install 'unzip' for this script to work.
Failed: Execution of command '/bin/sh "/root/.vs-debugger/GetVsDbg.sh" -v vs2019 -l "/root/.vs-debugger/vs2019" -a "/remote_debugger"' on remote system failed with return code: 1
程序“[1] dotnet”已退出，返回值为 -1 (0xffffffff)。

**Comment by nocanstillbb** [comment]
Determining user folder on remote system...
Checking for existing installation of debugging tools...
Downloading debugger launcher...
Creating debugger installation folder: /root/.vs-debugger
Copying debugger launcher to /root/.vs-debugger/GetVsDbg.sh
Ensuring script exists after copying...
Downloading debugger components...
Output: Info: Previous installation at '/root/.vs-debugger/vs2019' not found
Info: Using vsdbg version '16.3.10904.1'
Using arguments
    Version                    : 'vs2019'
    Location                   : '/root/.vs-debugger/vs2019'
    SkipDownloads              : 'false'
    LaunchVsDbgAfter           : 'false'
    RemoveExistingOnUpgrade    : 'false'
Info: Using Runtime ID 'linux-x64'
Downloading https://vsdebugger.azureedge.net/vsdbg-16-3-10904-1/vsdbg-linux-x64.zip
ERROR: Command 'unzip' not found. Install 'unzip' for this script to work.
Failed: Execution of command '/bin/sh "/root/.vs-debugger/GetVsDbg.sh" -v vs2019 -l "/root/.vs-debugger/vs2019" -a "/remote_debugger"' on remote system failed with return code: 1
程序“[1] dotnet”已退出，返回值为 -1 (0xffffffff)。

**Comment by sunliusi** [comment]
The problem is still here.
Could you consider setting up a mirror server in China.
