### ISSUE TITLE
Not respecting the default browser setting in windows.

### ISSUE THREAD

**Issue by OpusKrokus** [microsoft/DockerTools#189]
I generally set the default browser on my development machine to match what my customer uses/requires to make testing and debugging more efficient (make it work there first, and then test the other browsers).  However, when trying to debug container based web apps in VS2019 (F5 or the debug button in the IDE), it refuses to launch anything but Edge, and I cannot find any documentation on how to change the behavior.  I can work around this by launching the preferred browser and load the URL presented in Edge, but this can be pretty tedious when trying to make a lot of quick edits and check the results  My understanding is that it is supposed to launch the default browser set in Windows.

I am pretty sure I am doing something wrong, but I have no idea how to find out what it is.

**Comment by bwateratmsft** [comment]
@OpusKrokus Which version of Visual Studio are you using? For me it correctly uses my default.

**Comment by OpusKrokus** [comment]
VS 2019 v16.1.0
I feel like it is some setting on my end that is goofed up, but I am unsure.  The debug button is set to Docker

**Comment by bwateratmsft** [comment]
So, I noticed something. On my system, Chrome is the default browser. In the below screenshot, I chose Edge as the browser to launch. When launching IIS Express, or the program directly, it opens in Edge, but Docker still uses Chrome (the Windows default).

![image](https://user-images.githubusercontent.com/36966225/58333161-d5029600-7e0a-11e9-928b-310ef7276072.png)

Is it possible that you have Chrome chosen for that setting (hence, launching directly does Chrome, respecting that setting), but Edge is actually the Windows default?

In any case, I'll open a bug, we want Docker to follow the browser option chosen in that dropdown.

**Comment by OpusKrokus** [comment]
Thanks so much!

**Comment by OpusKrokus** [comment]
So... One more note.  If I set it in the menu you mention above, it opens correctly for everything but Docker.  Docker _still_ opens it in Edge.  It also opened in Edge when I clicked on the "More Emulators..." option in the same menu.

Again, I really appreciate you guys looking into this!

**Comment by bwateratmsft** [comment]
@OpusKrokus We've implemented a fix for both single-Dockerfile and docker-compose projects, and are tentatively planning to release it in 16.2 Preview 3. For Compose it's a little more awkward to configure the browsers, as you have to switch the startup project to your web app, configure the browsers, then back to the docker-compose project, but that's out of our control unfortunately. :)

**Comment by dbreshears** [comment]
This should be fixed. Closing
