### ISSUE TITLE
Need to set a constant url:port under debug for other services that must have a known address

### ISSUE THREAD

**Issue by SteveLasker** [Microsoft/DockerTools#19]
When building and debugging clients that connect to services, the clients often need to know the URL, even if it's localhost:8080 to enable client connectivity. 
The current tools use the dynamic port syntax -P to dynamically find an available port. This works will when everything runs in a container as docker network discovery kicks in. However, when attempting to connect outside the docker DNS, the address must be known.
In the development environment, we need a way to allocate a known address:port that can be set on the project, checked into scc, and known by other clients in the solution, or outside the solution for a known address. 
This follows the IISExpress pattern and we may have made this too flexible in our current tools. 
If another container is running on that port, we would docker rm -f that container as we assume the current VS instance is the controlling scenario.

**Comment by dazhao-msft** [comment]
For ports, you always can specify a specific host port in docker-compose.*.yml. The recommended place is docker-compose.override.yml, which is targeting local development scenario.

https://docs.docker.com/compose/compose-file/#ports

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
