### ISSUE TITLE
List Docker Images on local machine

### ISSUE THREAD

**Issue by olegburov** [microsoft/DockerTools#190]
Would be handy if Visual Studio Container Tools Extensions could list Docker Images on local machine. Just like [Docker](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker) extension for VS Code does:

![Docker-Extension](https://user-images.githubusercontent.com/2487951/59073527-60087500-887c-11e9-8133-e6ce75d5b234.PNG)

**Comment by BigMorty** [comment]
Thanks @olegburov for your feedback, this is very high on our list of features we want to add.

**Comment by pratiksanglikar** [comment]
Hi @olegburov, images can now be viewed in the latest release of Containers Tools Window.
