### ISSUE TITLE
In Docker Compose, any way to exempt a dockerfile from debugging?

### ISSUE THREAD

**Issue by dvalovage** [microsoft/DockerTools#192]
I'm a bit new to Docker, so maybe the answer is obvious and I just missed it. I have a Docker Compose file with two services with Dockerfiles. One is ASP.NET Core, the other is an Angular website.

The ASP.NET Core works fine by itself, but with the Angular Dockerfile it throws an error "launch: program '' does not exist."

It seems that the debugger keys off of the existence of a Dockerfile to generate the extra YAML code in docker-compose.vs.debug.g.yml and attempt debugging. Is there any flag or way to exempt the service in a Docker Compose file from debugging?

Here's the Dockerfile for the Angular website:
`FROM node:8.16.0-jessie AS base`

`WORKDIR /app`

`ENV PATH /app/node_modules/.bin:$PATH`

`COPY package*.json /app/`
`RUN npm install`
`RUN npm install -g @angular/cli`

`COPY . /app`

`EXPOSE 4200 49153`

`CMD ng serve --host 0.0.0.0 --port 4200 --disableHostCheck=true --poll 1 --proxy-config proxy-config.json`

**Comment by sgreenmsft** [comment]
The first thing that comes to mind would be to move the Angular project's Dockerfile into a separate folder so that it's not next to the csproj file.  Admittedly not an ideal solution.  =^/

**Comment by dvalovage** [comment]
Ah that did it. Strange!

Thank you for the help.
