### ISSUE TITLE
Test Project Debugging - Failed to Launch Debug Adapter

### ISSUE THREAD

**Issue by 2Dews** [microsoft/DockerTools#194]
I can run and debug my api project in the container but when I try to debug my unit tests in the container I get a "Failed to launch debug adapter. Additional information may be available in the output window. Value cannot be null. Parameter name: value" message. The build output shows a successful build, the container tools output shows a successfully started container, but the test output says , Failed to launch testhost with error: System.AggregateException. 

Here is the full error message. 
[testerror.txt](https://github.com/microsoft/DockerTools/files/3303473/testerror.txt)

I have Docker support in my unit test project and start debugging the tests from Test Explorer with the debug profile set to Docker.

**Comment by bwateratmsft** [comment]
Hello @2Dews , at the moment test projects are not supported for containerization. It is on our radar though for future features.

**Comment by rudeGit** [comment]
But this video shows exactly that: https://www.youtube.com/watch?v=Tlswgxl_Xyk (from April 2019, which is earlier than this thread post).

Is there a difference in the setup in the video?

**Comment by BigMorty** [comment]
Hello @2Dews & @rudeGit! I am the PM for the Visual Studio family of container tools. The video you referenced does show containerizing a test project but I think the better way to run tests in a container is described in this article by Richard Lander - https://github.com/dotnet/dotnet-docker/blob/master/samples/dotnetapp/dotnet-docker-unit-testing.md

**Comment by dbreshears** [comment]
Here is a relevant link https://learn.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022#local-container-connections for this.  Closing this.
