### ISSUE TITLE
"error CTP1001: An error occurred while attempting to build Docker image." with multiple level project directories

### ISSUE THREAD

**Issue by JasonHaley** [microsoft/DockerTools#195]
I know the "error CTP1001: An error occurred while attempting to build Docker image." surfaces in different scenarios, but mine also has the "COPY failed: stat /var/lib/docker/tmp/docker-builderxxx/xxxxxx.csproj: no such file or directory" the line above that error.

I have tracked down the problem being the multiple directories my solution/project has and the context that is being passed into the container tooling.

My solution directory is like this:
/
    Solution1.sln
    /SubDir
         /WebApp
              WebApp1.csproj
              Dockerfile

In the Container.targets file Line 16, the DockerDefaultContext is set:
`<DockerDefaultContext Condition="'$(DockerDefaultContext)' == '' And '$(TargetFrameworkIdentifier)' != '.NETFramework'">..</DockerDefaultContext>`

If I change that to "../.." like this:
`<DockerDefaultContext Condition="'$(DockerDefaultContext)' == '' And '$(TargetFrameworkIdentifier)' != '.NETFramework'">../..</DockerDefaultContext>`

My image builds fine in VS.

Is there a location in VS that I can set the value for $(DockerDefaultContext)? I think it would need to be at the project level somewhere. Any way I can put that in the csproj file and have the Container Tools pick it up?

Due to other projects in the solution being dependencies of the WebApplication (shown above), I need the context being passed in to Docker build be 1 level up.

**Comment by bwateratmsft** [comment]
Hey @JasonHaley, for this scenario you need to add the following property to a PropertyGroup in WebApp1.csproj:

`<DockerfileContext>..\..</DockerfileContext>`

It's preferred to use this instead of `DockerDefaultContext`, although it would also technically work.

We've already implemented a fix in future versions of VS so that it will automatically scaffold in this property when in your scenario.

**Comment by JasonHaley** [comment]
Sweet! I'll give that a try - that will help a ton!

**Comment by JasonHaley** [comment]
Adding it to the property group in the csproj file:
```
<PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>ed553117-7172-4673-8295-1404be73f0bb</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>
```
Works for the "Build Docker Image" on the context menu and the start debugging Docker in VS 2019.
Also works for VS 2017 using the start debugging Docker button.

**Comment by bwateratmsft** [comment]
Glad it worked! I'll close this issue.
