### ISSUE TITLE
RUN apt-get update not wokring

### ISSUE THREAD

**Issue by porscheme** [microsoft/DockerTools#196]
Platform: Windows10 VSTS2017
Docker container for Linux

RUN construct wasn't picking Linux commands for execution. For example, in my  below very simple dockerfile 'RUN apt-get update' was not run.

FROM mcr.microsoft.com/dotnet/core/sdk:3.0-alpine3.9 AS build
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-alpine AS runtime

RUN apt-get update

WORKDIR /src
COPY ["TestWebApp/TestWebApp.csproj", "TestWebApp/"]
RUN dotnet restore "TestWebApp/TestWebApp.csproj"
COPY . .
WORKDIR "/src/TestWebApp"
RUN dotnet build "TestWebApp.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "TestWebApp.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TestWebApp.dll"]

**Comment by bwateratmsft** [comment]
@porscheme In Debug mode, only the "base" stage is run, which it seems you removed. I'd regenerate your Dockerfile back to how it was, and then add the apt-get update command in the base stage.

**Comment by sgreenmsft** [comment]
To clarify -- in Debug mode the first stage (and only the first stage) defined in the Dockerfile is built.  The name of the stage doesn't matter.  It doesn't have to be named "base."  So if you have a Dockerfile like so:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS myfirststage
EXPOSE 8080
WORKDIR /app
FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS mysecondstage
WORKDIR /src
```

Then when debugging in Visual Studio, only the first three lines are run.

**Comment by sgreenmsft** [comment]
Additional note:  In single-project (i.e. non-compose) scenarios, the property <DockerfileFastModeStage> can be added to your csproj file to tell Visual Studio which build stage should be built for F5, like so:
```
<PropertyGroup>
    <DockerfileFastModeStage>mysecondstage</DockerfileFastModeStage>
</PropertyGroup>
```
