### ISSUE TITLE
Containers window doesn't save layout

### ISSUE THREAD

**Issue by ProH4Ck** [microsoft/DockerTools#199]
If I resize "Containers" window using splitter between left and side panels after Visual Studio restart the setting is not saved.

Every time I start Visual Studio I need to resize this window in order to see the name of my containers (docker compose add a huge prefix ☹)

![image](https://user-images.githubusercontent.com/8057670/60525656-17af6c00-9cef-11e9-912d-b7444103d0f6.png)

**Comment by dbreshears** [comment]
Thanks for the feedback.  We will look into getting a fix for this in a future update

**Comment by haniamr** [comment]
This issue is now fixed in the latest release on the marketplace and Visual Studio 6.4 Preview 2.
