### ISSUE TITLE
Support reading environment variables from .env file

### ISSUE THREAD

**Issue by odannyboy000** [Microsoft/DockerTools#20]
I want to be able to read from a .env file.

Docker, by convention, looks for a .env file in the current **execution folder**. DockerTools does not run from root, and also does not allow you to specify where to execute from.

An alternative would be to allow me to add an additional docker-compose override file and have it passed along with the provided override files.

**Comment by dazhao-msft** [comment]
There is already a docker-compose.override.yml file in the docker-compose.dcproj. Can you add the .env file to it?

**Comment by dazhao-msft** [comment]
You can reference an env file in docker-compose.override.yml:

https://docs.docker.com/compose/compose-file/#env_file

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
