### ISSUE TITLE
Keep directories on top when sorting by name.

### ISSUE THREAD

**Issue by olegburov** [microsoft/DockerTools#200]
When viewing files, I would like directories to be on top when sorting by name. Just like on Windows in File Explorer.

![Files](https://user-images.githubusercontent.com/2487951/61150388-31437700-a498-11e9-849c-ccca664de2b2.JPG)

**Actual result**

- `inetpub`
- `License.txt`                <= File gets listed with directories
- `Program Files`
- `Program Files (x86)`
- `ProgramData`
- `ServiceMonitor.exe` <= File gets listed with directories
- `Users`
- `Windows`

**Expected result**

- `inetpub`
- `Program Files`
- `Program Files (x86)`
- `ProgramData`
- `Users`
- `Windows`
- `License.txt`                  <= File gets listed after directories
- `ServiceMonitor.exe`    <= File gets listed after directories

**Comment by haniamr** [comment]
Thanks for the feedback, @olegburov. We will look into getting a fix for this in a future update.

**Comment by haniamr** [comment]
This issue is now fixed in the latest release on the marketplace and Visual Studio 6.4 Preview 2.
