### ISSUE TITLE
VS2019 docker image build for debug is not accessible by IP:port

### ISSUE THREAD

**Issue by OlegPNN** [microsoft/DockerTools#201]
Hello in Microsoft Docker community.
Under Windows 10 pro and  Microsoft Visual Studio Community 2019 v  16.1.6 + 
ASP.NET and Web Tools 2019   16.1.429.50124 i have build self hosted HelloWorld  .Net Core application to run under Kestrel. With Docker support. You can find sources under https://github.com/OlegPNN/ASP.NET-core-docker-
It runs perfectly in self hosted configuration under 80 and 443.

I have docker desktop (community edition v 18.09.2) and Hiper-V enabled (active) under Windows 10. When I start debug in Docker configuration:
- studio is composes and runs sucessfully image (if something is wrong, like certificate path and pwd. I'm getting in debug exception when image is starting
- I can't get any of response from image ip and port (both 8080 mapped to 80 and 443) when trying to reach this image from my PC (ERR_CONNECTION_TIMED_OUT)

I did checked all workaround based on this repo issues and other sources.
docker ps       show me image is running normally

CONTAINER ID        IMAGE               COMMAND                    CREATED              STATUS              PORTS                                        NAMES
53855b613563        helloworldapi:dev   "C:\\remote_debugger\\…"   About a minute ago   Up About a minute   0.0.0.0:443->443/tcp, 0.0.0.0:8080->80/tcp   stoic_fermi

docker exec 53855b613563 ipconfig confirms IP under which docker container is running
I can ping this address and tracert to this api show me the container id (53855b613563) as endpoint
but get http://172.23.82.133:8080/ or https://172.23.82.133 do not return any of response.
docker run commands loks like:
docker run -dt -v "C:\Users\Profile\onecoremsvsmon\16.0.29009.5:C:\remote_debugger:ro" -v "C:\Olegus\Projects\HelloWorld\HelloWorld\HelloWorldAPI:C:\app" -v "C:\Users\Profile\AppData\Roaming\Microsoft\UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro" -v "C:\Users\Profile\AppData\Roaming\ASP.NET\Https:C:\Users\ContainerUser\AppData\Roaming\ASP.NET\Https:ro" -v "C:\Users\Profile\.nuget\packages\:c:\.nuget\fallbackpackages2" -v "C:\Program Files\dotnet\sdk\NuGetFallbackFolder:c:\.nuget\fallbackpackages" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "ASPNETCORE_ENVIRONMENT=Development" -e "NUGET_PACKAGES=c:\.nuget\fallbackpackages2" -e "NUGET_FALLBACK_PACKAGES=c:\.nuget\fallbackpackages;c:\.nuget\fallbackpackages2" -p 8080:80 -p 443:443 --entrypoint C:\remote_debugger\x64\msvsmon.exe helloworldapi:dev /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646 

May be something wrong is with app within container and it crashes at runtime without any response, may be problem is in remote debugger passed to attach.

**Comment by bwateratmsft** [comment]
The ports you've mapped from (443, 8080) are the port to query on the host (localhost) for the container, not the container itself. So, "http://localhost:8080", "https://localhost", and "https://172.23.82.133" are correct, but "http://172.23.82.133:8080" will not respond to anything (it would be asking the container for its port 8080, which isn't exposed to anything).

Visual Studio does not actually start the ASP.NET Core app within the container until you do F5 or Ctrl + F5. It uses msvsmon (Windows containers) or vsdbg (Linux containers) to start the app, which is why the entrypoint is not the app itself. Otherwise, it would not be able to attach during startup, and issues during startup would not be debuggable.

When you F5, what errors do you see, either from VS or from the browser?

**Comment by OlegPNN** [comment]
Looks, like I've found a root of this problem, but can't understand how to solve it.
It's about to debug docker configuration with self signed certificate when VS2019 creates ASP .Net core application https://docs.microsoft.com/en-us/visualstudio/containers/media/overview/vs-2019/enable-docker-support-visual-studio.png?view=vs-2019 from template.
1. From every beginning it is possible debug under Docker as well as under self hosted configuration. Like https://172.23.91.130/api/values or  https://localhost:5001/api/values ...just browser reports security connectoin is not established.
2. When I just adding .UseKestrel()  it is still possible to debug under 2 configuration, just Kestrel reports exception that certificate wasn't applied.
3. When I'm registered self signed sertificate and added key Kestrel:Certificates:Development:Path to secret Kestrel it din't reports any security issues under SelfHosted debug, but stop working under Docker debug. When run Docker debug I'm getting  exception at runtime Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.
4. From other side when I put to IWebHostBuilder CreateWebHostBuilder method
             .UseKestrel(
                (context, options) =>
                {
                    if (context.HostingEnvironment.IsDevelopment())
                    {
                        var pwd = context.Configuration.GetValue<string>("Kestrel:Certificates:Development:Password");
                        var certpath = context.Configuration.GetValue<string>("Kestrel:Certificates:Development:Path");
                        options.Listen(IPAddress.Loopback, 443, listenOptions =>
                        {
                            listenOptions.UseHttps(certpath, pwd);
                        });
                    }
                    options.Listen(IPAddress.Loopback, 80);
                }
                )
            .UseStartup<Startup>()
            .ConfigureAppConfiguration(
                    (builderContext, configurationBuilder) =>
                    {
                        Console.WriteLine("Adding configuration");
                        IHostingEnvironment env = builderContext.HostingEnvironment;
                        configurationBuilder.Sources.Clear();
                        configurationBuilder.AddEnvironmentVariables();
                        if (env.IsDevelopment())
                        {
                            var appAssembly = Assembly.Load(new AssemblyName(env.ApplicationName));
                            if (appAssembly != null)
                            {
                                configurationBuilder.AddUserSecrets(appAssembly, optional: true);
                            }
                        }
                    });
docker debug is starting perfectly, but no response in poput browser or any other tool on https://172.23.91.130/api/values. Self hosted configuration is starting and working perfectly. 
p.s. Looks I'm wrongly configure Kestrel with certificate data for Docker in this case

**Comment by bwateratmsft** [comment]
Ah, I see. Adding SSL to an already-scaffolded application is tough, and it gets more complicated with containers.

I'd suggest creating a new ASP.NET Core web app, ensuring that "Use HTTPS" is checked, add Container Orchestrator Support > Docker Compose to it, F5 it at least once, and then compare to your app. In particular, look at:

Properties\launchSettings.json
docker-compose.yml
docker-compose.override.yml
Dockerfile
docker-compose.dcproj
YourProject.csproj
Startup.cs
Program.cs

The issue may be clearer when seeing the differences between a freshly created app and the existing one.

**Comment by bwateratmsft** [comment]
Also, I can take a look at your source @OlegPNN but the link in your original comment seems to be broken: https://github.com/OlegPNN/ASP.NET-core-docker-

**Comment by OlegPNN** [comment]
Thank you Brandon. I've found a combination when web app with self signed ssl sertificte keeps working in remote debug  work under docker image created by VS2019. My mistake wfs I've put a lot of code (related with ssl) and then tried to run it under docker image.

**Comment by SidShetye** [comment]
For anyone coming here with a similar issue, one issue was that we had customized our solution, so our `Program.cs` needed a switch from `IPAddress.Loopback` to `IPAddress.Any`

```
.ConfigureWebHostDefaults(webBuilder =>
{
    webBuilder.UseStartup<Startup>();
    webBuilder.ConfigureKestrel((hostContext, opt) =>
    {
        if (hostContext.HostingEnvironment.IsDevelopment())
        {
            opt.Listen(IPAddress.Any, // <== FIX HERE
                       443, 
                       listenOptions =>  { <snip> }
             );
        }
    });
});
```

Side note, VS2019 made it very trivial to enable Docker support for our application while pulling in best practices of build vs run image. Tooling and azure infrastructure around this is too new for us to use in production but it's good in dev so far.
