### ISSUE TITLE
How to map a port to the running container?

### ISSUE THREAD

**Issue by hannesne** [microsoft/DockerTools#206]
I am trying to map a port when I debug a local container. From the commandline I would add -p 8883:8883 to the commandline. How do I set this when using the container tools?

I've tried to add 
<PropertyGroup>
    <DockerfileRunArguments>-p 8883:8883</DockerfileRunArguments>
</PropertyGroup>
to me csproj, but it's not working.

**Comment by hannesne** [comment]
Cool thanks, I'll give that a try. It's for communication on a TCP socket, so the project file should work. Can I suggest we change the launchsettings port mapping to accept an array of "port:port" settings for port mapping?

**Comment by AndyVulhop** [comment]
I'll second @hannesne. It's pretty painful to get VS to map the correct ports if you aren't running on 80 or 443 (which is best practice to avoid if you aren't running as root on linux containers, since ports < 1024 require superuser). This seems like a concern for the launchSettings.json file.

**Comment by crhistianramirez** [comment]
What are the steps required for VS to listen to another port (besides 80 or 443) ?

**Comment by MHacker9404** [comment]
Wouldn't this be the ASPNETCORE_URLS environmental setting?

**Comment by dbreshears** [comment]
Closing stale issue and looks like this was addressed with dockerfilerunarguments
