### ISSUE TITLE
Support ability to override the docker compose Entrypoint at debug time

### ISSUE THREAD

**Issue by KSchlobohm** [microsoft/DockerTools#207]
When using Visual Studio Container tools a  docker-compose.vs.debug.g.yml file will automatically be generated for projects that use a docker-compose approach so that the Container Tools can mount the debugger in the container.

This feature also overrides the entrypoint which limits developer options. Instead, it would be better if the last file used in the docker-compose arguments was the docker-compose.override.yml shown in the Visual Studio solution.

This enables developers to replace the entry point and do important dev-only tasks during their debug experience. As an example, I was trying to setup my local container development using self-signed certificates. I found that when making an API call from a webapp the certificate validation process did not trust the self-signed certs by default because they have to be registered with the client container. To do this, I needed to run "update-ca-certificates" and start my container. But since this certificate was a self-signed one, this isn't something I want to include in my dockerfile that will build the production image. Instead, this is something I wanted to put into an override. The desired solution would be to override the entrypoint.

entrypoint: "sh -c 'update-ca-certificates && tail -f /dev/null'"

But this is not currently possible, as the docker-compose.vs.debug.g.yml file overrides the entrypoint and is passed into the docker-compose command after my docker-compose.override.yml file.

**Comment by KSchlobohm** [comment]
Thanks @sgreenmsft, that works like a charm! I didn't see that in the docs for [Building Containerized apps](https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019). Is that covered in a section I missed?

Also, when I tried to add the debug override you mentioned I had to do it by making a new text file from an Explorer Window. My muscle memory wanted to find the option to add this by right clicking on the existing docker-compose.yml file (similar to the experience with web.config an adding additional transforms). It would be even more convenient if that file was included by default.
![image](https://user-images.githubusercontent.com/23503973/63946287-7d437e80-ca3a-11e9-8bdf-bf34dbc4548d.png)

Another thing that was odd was that when I tried to add new items to the docker-compose project was that my list of templates was empty. We seem to have override and environment files that make sense to be listed here but even the txt file template would make it easier to add these files. Did I need to install an extension? (using Visual Studio 2019 4.8.03752)
![Add new items to the Docker-compose project](https://user-images.githubusercontent.com/23503973/63946634-06f34c00-ca3b-11e9-86a5-9316ee08e01d.jpg)
![No file templates shown when adding files to the Docker-compose project](https://user-images.githubusercontent.com/23503973/63946642-09ee3c80-ca3b-11e9-9638-0aedad016ada.jpg)

**Comment by KSchlobohm** [comment]
Updated the title of the ticket to help with search results.

The ability to override the entry point is supported by editing the docker-compose.vs.debug.yml file so I'm closing this issue/feature request.

**Comment by Morgma** [comment]
@KSchlobohm is this issue truly resolved? I found that docker-compose.vs.debug.yml is not taken up by the VS debugger, and any changes made directly to obj\Docker\docker-compose.vs.debug.g.yaml will be overridden during build of the .dcproj. In my case, I'd like to change the volume mapping so that my source goes into different directory than c:\inetpub\wwwroot, but so far, haven't been able to make it stick.

**Comment by KSchlobohm** [comment]
Hi @Morgma, yes this issue is closed. You can provide override settings to your containers by using the following approach. As you noted, you should not alter the "obj\Docker\docker-compose.vs.debug.g.yaml" file which is produced by visual studio to handle attaching the debugger.

https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019#docker-compose-file-labels

Here's a quick and simple demo using an environment variable that is displayed in a razor page.

https://github.com/KSchlobohm/DockerWebAppWithDebugOverride

If you run into trouble with this approach you may need to "right click+clean" the Docker compose in Visual Studio to trigger a rebuild of the container.

**Comment by KSchlobohm** [comment]
@Morgma, please also note that if you're trying to perform a multi-stage dockerfile build that Visual Studio defaults to the "Fast mode" build. If you want to disable the performance optimization you'll need to edit the project file.

> In **Fast** mode, Visual Studio calls `docker build` with an argument that tells Docker to build only the `base` stage. Visual Studio handles the rest of the process without regard to the contents of the Dockerfile. So, when you modify your Dockerfile, such as to customize the container environment or install additional dependencies, you should put your modifications in the first stage. Any custom steps placed in the Dockerfile's `build`, `publish`, or `final` stages will not be executed.

https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#debugging

**Comment by babakansari** [comment]
What is the usage of `docker-compose.override.yml` if it just override `docker-compose.yml` settings?

**Comment by ravipal** [comment]
@babakansari, Please see - https://docs.docker.com/compose/extends/, the `docker-compose.override.yml` is typically used for development configurations and useful even in non-VS experience, but the `docker-compose.vs.*` files are specifically for customizing Visual Studio experience.
