### ISSUE TITLE
Update dockerfile when the project target is changed

### ISSUE THREAD

**Issue by KSchlobohm** [microsoft/DockerTools#208]
While following our latest documentation for configuring Kestrel I realized the extension method ConfigureKestrel was added in ASP.NET Core 2.2 which was not included by default with Visual Studio 2019. After install I had to change my target framework and that's when things became odd.

From Visual Studio, while running with docker compose, I found that the breakpoint in my "Hello world" ASP.NET Core project could no longer be reached. Visual Studio warned me that the source file was found in the DLL but that the current source code is different from the version built into the dll. I found that the way to fix this was to correct my Dockerfile.

`FROM mcr.microsoft.com/dotnet/core/aspnet:2.1-stretch-slim AS base`
-needed to become-
`FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base`

The desired solution would be that Visual Studio makes this change for me so that it just works, or that Visual Studio can show me a warning/error at build time so that I can resolve this issue.

**Comment by BigMorty** [comment]
Thanks Ken, I have added an item to our backlog so that we warn users when we can identify that the base .NET images being used in the Dockerfile don't match the version of .NET of the project.
