### ISSUE TITLE
MSBUILD switch to ignore building dcproj when building inside a Windows container

### ISSUE THREAD

**Issue by pbering** [Microsoft/DockerTools#21]
Hi, I would like to build my solutions inside a build container (aka the "Docker builder pattern"). I would like to just call `MSBUILD mysolution.sln /p:Configuration=Release` but that trigger the build of the dcproj which will try do call docker inside my container (as far as I know we can't run docker in docker with Windows containers yet).

Is there a MSBUILD parameter I can set so the dcproj is skipped or do I need to build each of my csproj individually?

**Comment by dazhao-msft** [comment]
This is not supported by the tools currently. The team is working on a better solution now.

**Comment by pbering** [comment]
Thanks, which solution are they working on? For skipping dcproj projects or running docker inside docker on Windows, or something else?

**Comment by hbulens** [comment]
Is there any feedback on this one?
