### ISSUE TITLE
Permit supplementary Dockerfile projects with docker-compose

### ISSUE THREAD

**Issue by xemed-ahope** [microsoft/DockerTools#212]
Please consider adding a means of including "supplementary" Dockerfile projects. Right now, any project type having a Dockerfile at a normal location but lacking explicit debugging support causes an error, as detailed in #141. Some projects can go without debugging support. Take for example `Microsoft.Build.NoTargets`. (full example adapted from @da1rren's [here](https://github.com/xemed-ahope/ValueCannotBeNullStream) ). The workaround suggested by @sgreenmsft (putting the  Dockerfile in a subdirectory) is effective, but not obvious.

```
error CTC1030: Value cannot be null. 
error CTC1030: Parameter name: stream
```

**Comment by pratiksanglikar** [comment]
A fix for this issue has been released.
Please download the latest VS version from - https://visualstudio.microsoft.com/downloads/

You can now specify the projects to ignore using the MSBuild property - `<DockerComposeProjectsToIgnore>`
This MSBuild property can be specified in dcproj and it contains the ; separated list of all the projects that need to be ignored.

Projects can either be specified as absolute paths or relative paths from the solution directory.
