### ISSUE TITLE
How to handle cached base images?

### ISSUE THREAD

**Issue by cskwrd** [microsoft/DockerTools#214]
As we know dotnet core 3.0 was released a week ago. When this happened, the `3.0-buster-slim` image VS had included as the base image for running an app in a container broke. I was shown an error saying that `3.0.0` couldn't be found, only `3.0.0-preview7...`. If i specify `--pull` as a value for `DockerfileBuildArguments` in my project file the issue is resolved.

I am still very new to docker, so I am having trouble figuring out how we are supposed to handle a caching issue like this using DockerTools. It doesn't seem like leaving `--pull` in my project file is the answer.

For what it's worth, Tools -> Options -> Container Tools -> Single Project -> Pull required Docker images on project open is set to `True`.

**Comment by bwateratmsft** [comment]
Using `--pull` is one option; you can also periodically pull the latest manually. In 16.4, we will have another option in Options > Container Tools that will also take care of this--"Pull updated Docker images on project open", with options to pull none, .NET Core only, or all (i.e. .NET Core and .NET Framework).

**Comment by cskwrd** [comment]
Is that different than the setting I referenced above?

**Comment by bwateratmsft** [comment]
Yes, it will be a new setting in 16.4. The existing setting will have the same effect--pulling images that are _missing_, but the new setting is for re-pulling images that aren't missing.

**Comment by cskwrd** [comment]
Awesome, thank you very much!
