### ISSUE TITLE
Add support for DotNetCore 3.0 Worker template

### ISSUE THREAD

**Issue by kdcllc** [microsoft/DockerTools#216]
DotNetCore 3.0 added a new MSBuild template `<Project Sdk="Microsoft.NET.Sdk.Worker">` and the Docker tooling doesn't support this type of project at this time. Our team can benefit from having support for the Dockernization of this template.

**Comment by kdcllc** [comment]
@bwateratmsft, this is strange but after I upgraded VS.NET 2019 16.3.5 this project now has the options to start in Docker. Here is the reference https://github.com/kdcllc/K8.DotNetCore.Workshop/blob/master/src/K8.LongProcess/K8.LongProcess.csproj

Thanks for looking into it, kdcllc!

**Comment by bwateratmsft** [comment]
Great, glad it's working now!
