### ISSUE TITLE
How to docker-compose using "dotnet watch run" in container

### ISSUE THREAD

**Issue by roussakov** [microsoft/DockerTools#217]
Hi guys, 
I'm trying to set up a docker-compose stack using visual studio 2017 docker tooling.
And unable to find the way how to run the app inside a container using **dotnet watch run**
any suggestions?

Thanks!

**Comment by bwateratmsft** [comment]
@roussakov Unfortunately this isn't possible with the tooling. We use a lot of optimizations in debug mode that are incompatible with `dotnet watch`.

**Comment by amarant** [comment]
@bwateratmsft So does it means that it is impossible to edit a cshtml page and having that change reflected on a refresh with docker-compose ?

**Comment by bwateratmsft** [comment]
@amarant Not necessarily; the edit-refresh scenario is kind of scattered depending on .NET Core version and container OS. @pratiksanglikar  can probably list which ones work.

In debug mode, we map in the source and binaries built on the host. In release mode, source is copied in, and built in the SDK container. So, it would never work in release mode, but can in debug.

**Comment by roussakov** [comment]
@bwateratmsft Thanks a lot for your answer.

**Comment by pratiksanglikar** [comment]
Hi @roussakov ,
Adding to @bwateratmsft , Edit and Refresh works depending on what version of .NET Core you are on.

- .NET Core 2.1 -> Works on both Linux and Windows containers.

- .NET Core 2.2 -> Runtime compilation APIs are obsoleted, it works, but may take multiple refreshes to actually see the changes on both Linux and Windows containers.

- .NET Core 3.0 -> Runtime compilation support is disabled in default templates. To enable it, 
•	Add `Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation` nuget package.
•	In the Startup.cs, add `services.AddRazorPages().AddRazorRuntimeCompilation();`

After making the above-mentioned changes, Edit and refresh works for both Linux and Windows containers.

Also, this would work when editing *.cshtml files but not while editing *.cs files.

**Comment by elietebchrani** [comment]
This solution is working locally, but when publishing to Azure it's not working.
