### ISSUE TITLE
Can I specify a different dockerfile in the launchsettings.json?

### ISSUE THREAD

**Issue by StingyJack** [microsoft/DockerTools#218]
The Dockerfile that is created when adding support for debugging is nice and all, but I'd rather that be called something like "Dockerfile-debug" and have the dockerfile used for packaging the release built and versioned code in the project root as "Dockerfile". 

I dont see any options in the launch settings page for using a different file name. Is there a way to do this?

**Comment by bwateratmsft** [comment]
@StingyJack The Dockerfile that is created automatically is structured in such a way that it works for both debugging and production.

The `base` stage is built for debugging and the binaries themselves are built on the _host_, and volume mapped into that runtime container from the `base` stage.

For production builds, it builds the full Dockerfile, which includes building the binaries in the SDK container, publishing them, and copying the published bits into the runtime container.

**Comment by StingyJack** [comment]
@bwateratmsft the dockerfile is missing the parts where the assemblies are versioned, or where any nuget packages that get built as part of the solution are published, or there the program itself is published as an artifact runnable on its own without a container..

Its neat that you can do all that stuff in the containers, but the dockerfile seems to assume its the only thing getting built. 

I'm still wanting to know about renaming it.

**Comment by NCarlsonMSFT** [comment]
@StingyJack The project property [DockerfileFile](https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2019) can be used for what you want.

**Comment by dbreshears** [comment]
Closing per @NCarlsonMSFT workaround.
