### ISSUE TITLE
Circular dependency error when building for docker

### ISSUE THREAD

**Issue by ahanoff** [Microsoft/DockerTools#22]
Project created with VS2017 for .net core and with docker support contains docker-compose files in the root folder and Dockerfile in the project folder. It's also standard to have Dockerfile in the root, or in the same folder as docker-compose files. Problem occurs when Dockerfile is moved next to docker-compose files and context of docker-compose is set to "."

Why I put it in solution directory? Well, I am using approach with Dockerfile.build and Dockerfile. So, this dockerfile.build file just copies source code, then restore dependencies and finaly creates build artefacts. 
If Dockerfile is in project directory, `dotnet restore` command will not restore dependencies from another projects in solution. So, I placed it in solution directory. And it works fine, images are created successfully.

But I still want to build them and debug from VS. So, I set context in docker-compose file to "." And I got the error in subject. 
Thanks.

I've read [https://developercommunity.visualstudio.com/content/problem/37623/circular-dependency-error-when-building-for-docker.html](https://developercommunity.visualstudio.com/content/problem/37623/circular-dependency-error-when-building-for-docker.html), but it is not really helpful.

**Comment by dazhao-msft** [comment]
This bug has been fixed in VS 2017 15.3 Preview1. You can install it from https://www.visualstudio.com/vs/preview/ to try it out.

**Comment by ahanoff** [comment]
@dazhao-msft well, it solved initial error, but now I got new even less informative: 

> Severity	Code	Description	Project	File	Line	Suppression State
Error		Nullable object must have a value.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	210	

>

**Comment by dazhao-msft** [comment]
Step back a little bit: docker-compose.ci.build.yml in the project is for building the solution in a build container. You can try it out without having to create another Dockerfile.build. On the other side, assuming you copy the entire solution into a build container, you can 'dotnet restore' against the solution to restore packages for all the projects.

If you can share a repro project, the team can take a look at the issue with nullable object. @sgreenmsft

**Comment by ahanoff** [comment]
@dazhao-msft well, I created sample project [https://github.com/ahanoff/aspnet-core-docker](https://github.com/ahanoff/aspnet-core-docker). I don't like idea with another Dockerfile.build file as well. So yesterday I tried multistage dockerfile. [https://github.com/ahanoff/aspnet-core-docker/blob/master/Dockerfile.multistage](https://github.com/ahanoff/aspnet-core-docker/blob/master/Dockerfile.multistage) If I use Dockerfile.multistage in docker-compose.yml, I will get nullable error. For now I decided leave original Dockerfile in project directory and docker-compose and use Dockerfile.multistage in CI as temporary workaround. But would be great to support only one file for everything. Any advice? Thanks

**Comment by dazhao-msft** [comment]
[aspnet-core-docker-master.zip](https://github.com/Microsoft/DockerTools/files/1056852/aspnet-core-docker-master.zip)

I think I figured out what was wrong. VS Docker tools determines if a Docker service is associated with a .NET Core project by checking if Dockerfile and the project file (.csproj) are under the same folder. Moving Dockerfile to parent folder breaks it. 

I modified your repro project to move AspNetCoreDocker.csproj next to .sln as well. The caveat is that you'd have to exclude ClassLibrary1.csproj from AspNetCoreDocker.csproj otherwise the new project system includes everything under the root folder by default. You can take a look just for understanding how tools works.

**Comment by ahanoff** [comment]
@dazhao-msft thank you, it was not obvious how VS Docker tools works. Btw can you please explain why you decided to stick Dockerfle and .csproj together? Just curious. Thanks. 
And don't you plan make tool open-source? I think issue can be closed.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
