### ISSUE TITLE
Build with docker-compose including a static website: The project file was not found

### ISSUE THREAD

**Issue by Pikabanga** [microsoft/DockerTools#221]
Hello!

I have an issue with building in VS2019 with docker-compose.

Docker compose (anonymised naming):
```yml
version: '3.4'

services:

  company.projectname.service.api:
    image: ${DOCKER_REGISTRY-}companyprojectnameserviceapi
    build:
      context: .
      dockerfile: src/Company.ProjectName.Service.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5672:80"
      - "5772:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  company.projectname.webapi:
    image: ${DOCKER_REGISTRY-}companyprojectnamewebapi
    build:
      context: .
      dockerfile: src/Company.ProjectName.Web.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5671:80"
      - "5771:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  company.projectname.web.hub:
    image: ${DOCKER_REGISTRY-}companyprojectnamewebhub
    build:
      context: .
      dockerfile: src/Company.ProjectName.Web.Hub/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5673:80"
      - "5773:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  company.projectname.web:
    image: ${DOCKER_REGISTRY-}companyprojectnameweb
    build:
      context: .
      dockerfile: src/Company.ProjectName.Web/dev.Dockerfile
    ports:
      - "5674:80"
      - "5774:443"
```

The solution structure looks like this, I have marked the projects that are involved in the docker-compose:

![image](https://user-images.githubusercontent.com/22037089/70649510-98cf3f80-1c4d-11ea-89bb-5fa924c6febf.png)

Note that the .Web project is a static website, it's not a .NET project of any kind.

When I build I get this error:

![image](https://user-images.githubusercontent.com/22037089/70649615-d16f1900-1c4d-11ea-8259-5f81af3a3a07.png)

When I remove the company.projectname.web in section  docker-compose everything works fine.

My suspicion is that it expects a .csproj file, and obviously can't find it because it's not a .NET/.NET Core project.

The web project does have this ProjectSection in the solution file that might make it think it's a .NET application:

```
Project("{E24C65DC-7377-472B-9ABA-BC803B73C61A}") = "Company.ProjectName.Web", "src\Company.ProjectName.Web\", "{439DED5F-0924-446D-8BE2-67DB1C24AC30}"
	ProjectSection(WebsiteProperties) = preProject
		TargetFrameworkMoniker = ".NETFramework,Version%3Dv4.0"
		Debug.AspNetCompiler.VirtualPath = "/localhost_62686"
		Debug.AspNetCompiler.PhysicalPath = "src\Company.ProjectName.Web\"
		Debug.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_62686\"
		Debug.AspNetCompiler.Updateable = "true"
		Debug.AspNetCompiler.ForceOverwrite = "true"
		Debug.AspNetCompiler.FixedNames = "false"
		Debug.AspNetCompiler.Debug = "True"
		Release.AspNetCompiler.VirtualPath = "/localhost_62686"
		Release.AspNetCompiler.PhysicalPath = "src\Company.ProjectName.Web\"
		Release.AspNetCompiler.TargetPath = "PrecompiledWeb\localhost_62686\"
		Release.AspNetCompiler.Updateable = "true"
		Release.AspNetCompiler.ForceOverwrite = "true"
		Release.AspNetCompiler.FixedNames = "false"
		Release.AspNetCompiler.Debug = "False"
		VWDPort = "62686"
		SlnRelativePath = "src\Company.ProjectName.Web\"
	EndProjectSection
EndProject
```

But if I remove this section, it's just re-added whenever I build the solution...

Please let me know if you need any additional information!

**Comment by Pikabanga** [comment]
This seems very related: https://stackoverflow.com/questions/52946100/building-dockercompose-project-in-visual-studio-errors-our-when-website-projects

**Comment by pratiksanglikar** [comment]
Hi @Pikabanga , thank you for reporting this issue. We don't support static websites in Docker Compose today.
But this is under consideration for our future roadmap.

**Comment by Pikabanga** [comment]
Well, that explains it! Thanks for the information.

**Comment by pratiksanglikar** [comment]
Hi @Pikabanga , while the actual fix is under consideration, can you please try a workaround mentioned in [this comment](https://github.com/microsoft/DockerTools/issues/141#issuecomment-522822258) ?

**Comment by Pikabanga** [comment]
Well I'll be damned, it worked! Thanks so much, I'm happy with this workaround. You can close this issue if you want.
