### ISSUE TITLE
Cannot start remote debug: 0x80004005

### ISSUE THREAD

**Issue by ktos** [microsoft/DockerTools#222]
I am trying to debug ASP.NET Core 3.0 app running on remote Docker container. I can successfully connect over SSH to remote Docker host and list containers, but when connecting to one I want to debug I got a message:

```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to connect to 'temperaturektosdev_temperatureservice3_1;ssh=ktos@[redacted]'.  Operation not supported. Unknown error: 0x80004005.
---------------------------
OK   
---------------------------
```

This container is started via docker-compose, but I have exactly the same issue when starting it manually. 

docker-compose file:

```
version: '3.4'

services:
  temperatureservice3:
    image: dcr.ktos.dev/temperatureservice3:latest
    environment:
      - ApiKey=${TEMPERATURE_APIKEY}
      - ConnectionStrings:DefaultConnection=${TEMPERATURE_CONNECTIONSTRING}
    ports:
      - "127.0.0.1:${TEMPERATURE_PORT}:80"
    restart: always
```

Strangely, **same container** when run on local Docker host (Windows) is allowing me to debug without a problem.

Even more strangely, **every other container** on the same remote host allows me to be debugged, except **every** ASP.NET Core ones! There is one containerized .NET Core console app to which I can also connect without an issue!

Dockerfile for container which throws an error:

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /src
COPY ["TemperatureService3/TemperatureService3.csproj", "TemperatureService3/"]
RUN dotnet restore "TemperatureService3/TemperatureService3.csproj"
COPY . .
WORKDIR "/src/TemperatureService3"
RUN dotnet build "TemperatureService3.csproj" -c Release -o /app

FROM build AS publish
ARG INFOVER="Pre-Release"
RUN dotnet publish "TemperatureService3.csproj" -c Release -o /app /p:InformationalVersion=$INFOVER

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "TemperatureService3.dll"]

HEALTHCHECK CMD curl --fail http://localhost/health || exit
```

Dockerfile for containerized console app (which I can debug successfully):

```
FROM mcr.microsoft.com/dotnet/core/runtime:3.0-alpine AS base
WORKDIR /app
COPY . .
ENTRYPOINT ["dotnet", "Eleia.dll"]
```

**Finally, I have even tried to connect to empty ASP.NET Core image** started with `docker run -it --rm mcr.microsoft.com/dotnet/core/aspnet:3.0` and to "sample app" started with `docker run -it --rm -p 8000:80 --name aspnetcore_sample mcr.microsoft.com/dotnet/core/samples:aspnetapp` and it fails with 0x80004005 in both cases. Same for `docker run -it --rm --entrypoint /bin/bash mcr.microsoft.com/dotnet/core/samples`.

The only difference between containers is that one that works is **Alpine based, while the rest is not (Bionic based) - may be there a problem**?

So I have run: `docker run -it --rm mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine` and **it works**! No 0x80004005. So I am not sure if the issue should be here or in dotnet/dotnet-docker, but I am filling it here at the moment.

Host is Ubuntu 18.04.3 LTS with Docker 18.09.7.
Newest Visual Studio 2019 16.4.1.

**Comment by ktos** [comment]
To confirm the bug further, I have set up a new instance of Ubuntu 18.04.3 LTS with Docker 18.09.7, the only things I've done were:

```
sudo apt update && sudo apt upgrade
reboot
sudo apt install docker.io
sudo usermod -aG docker ubuntu
exit
docker ps
docker run -it --rm -p 8000:80 --name aspnetcore_sample mcr.microsoft.com/dotnet/core/samples:aspnetapp
```
And there is the same result, error 0x80004005:
![image](https://user-images.githubusercontent.com/1633261/70851877-41beaa00-1e9b-11ea-8666-d3f6be86a342.png).

Then, I thought about using VSCode/Omnisharp debugger integration, so I used `docker -H` as a pipe program and first got:

```
[Window Title]
Visual Studio Code

[Content]
Operating system """ not supported.

[Open launch.json] [Cancel]
```

Error "Operation not supported" and "Operating system """ not supported" are very similar, right?

It seems that VSCode is trying to perform such command:

```
docker -H ssh://ktos@[redacted] exec temperaturektosdev_temperatureservice3_old sh -s < C:\Users\ktos\.vscode\extensions\ms-vscode.csharp-1.21.8\scripts\remoteProcessPickerScript
```

So what is a content of that script? There is:

```
uname && if [ "$(uname)" = "Linux" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= ; elif [ "$(uname)" = "Darwin" ] ; then ps -axww -o pid=,comm=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,args= -c; fi
```

Running that as a command in a container directly resulted in:

```
Linux
bash: ps: command not found
```

So I installed `ps` by `apt install procps`. And than it connected, but there was some problem with vsdbg (starting but exiting immediately). And I thought - maybe it was that?

**AND YES! Remote debugging into Docker containers is now working in my VS2019!** There was no "ps" program installed in the container, so process picker cannot start!

So I think this is a bug in ASP.NET Docker containers, so I am creating an issue in that repo.

**Comment by pratiksanglikar** [comment]
HI @ktos ,
I'm glad installing `procps` solved your issue.

**Comment by marketten** [comment]
This also solved our problem. God bless you :))
