### ISSUE TITLE
User Secrets volume not mapped for Worker SDK

### ISSUE THREAD

**Issue by jbogard** [microsoft/DockerTools#223]
When you use the Web SDK for Docker, the User Secrets folders are correctly mapped:

https://docs.microsoft.com/en-us/visualstudio/containers/container-build?view=vs-2019#volume-mapping

However, for the Worker SDK, secrets are enabled by default (with a [temporary workaround](https://github.com/aspnet/Extensions/issues/2743)), but the secrets volume is *not* mapped.

I'm working around this today by mapping myself:

```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">

 <PropertyGroup>
   <TargetFramework>netcoreapp3.1</TargetFramework>
   <UserSecretsId>89595f67-a846-41e5-a74e-f876488ea8be</UserSecretsId>
   <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
   <DockerfileRunArguments>-v "$(AppData)/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"</DockerfileRunArguments>
 </PropertyGroup>
```

The expected behavior is to be able to use user secrets in a worker SDK whether I'm debugging on the host machine or inside a container.

**Comment by pratiksanglikar** [comment]
Thank you for reporting the bug. It is now under investigation.

**Comment by pratiksanglikar** [comment]
HI @jbogard ,
I am investigating this issue and just tried to reproduce,

Do user-secrets get loaded by just adding the volume mapping - `"$(AppData)/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro"`?

1. Create worker service.
2. Add user secrets using `dotnet user-secrets set "SecretKey" "SecretValue"`
3. Add packageReference to `<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.0" />`
4. print user-secret in `Worker.cs`

Doesn't seem to load user-secrets, Is there some step that I am missing?

**Comment by pratiksanglikar** [comment]
Create an issue - [#2880](https://github.com/dotnet/extensions/issues/2880) since even after mapping the volume, user secrets are not accessible in the container.

**Comment by rellis-of-rhindleton** [comment]
I've noticed that when using an image based on `mcr.microsoft.com/dotnet/core/aspnet:3.1-alpine`, the HOME environment variable is "/", not "/root" as it would be in e.g. the ubuntu image.

Mounting the volume like this appears to work:

```
docker run -it --rm --read-only -p 80:5000 -v %APPDATA%\Microsoft\UserSecrets:/.microsoft/usersecrets:ro ...
```

**Comment by tymur999** [comment]
This is still an issue in Net 5. The above answer does not work, since iirc Visual Studio uses Debian-based images.

**Comment by nathan-alden-sr** [comment]
Has there been any movement on this? I am still unsure of the idiomatic way to share .NET user secrets with Docker containers. In my case I'm using .NET 6.

**Comment by dbreshears** [comment]
This works for me in a container with a .NET 6 C# WorkerService in  VS 2022 after adding "Microsoft.Extensions.Configuration.UserSecrets (6.0.0)" NuGet package and adding DOTNET_ENVIRONMENT env variable to the Docker profile in LaunchSettings.json

```
{
  "profiles": {
    "WorkerService1": {
      "commandName": "Project",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": true
    },
    "Docker": {
      "commandName": "Docker",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
} 
```

I tested with the sample Pratik provided earlier at [#2880](https://github.com/dotnet/extensions/issues/2880).  I didn't need 3b. or add a property to volume mount the user secrets folder as it is already being volume mapped.

**Comment by jcotton42** [comment]
I'm curious why this was closed. From what I can tell it still requires you to manually specify a volume mount, which really is not great. The tooling should do it automatically.

**Comment by dbreshears** [comment]
@jcotton42, looks like this was fixed for single container scenarios but will need to investigate why not working for Compose tooling.   We might have fixed it there and it regressed.

**Comment by quarkonium3** [comment]
I can't get this to work at all in docker-compose .net6.0 Worker service project. 
I tried the docker-compose volume mapping workaround above without success. I can shell into the container and I see the full usersecrets folder mounted at /.microsoft/usersecrets. I can also step into the code and see that config is loading a JsonConfigurationProvider for secrets.json, but it seems to be just trying to use a bare path with only the filename 'secrets.json'
