### ISSUE TITLE
Launching failed because directory '/remote_debugger' in the container is empty

### ISSUE THREAD

**Issue by CrestApps** [microsoft/DockerTools#225]
I am running Docker Tools on Windows 7 64bit. When I try to run my app using `docker-composer` I get the following error 

> Launching failed because directory '/remote_debugger' in the container is empty. This might be caused by Shared Drives credentials used by Docker Desktop being out of date. Try resetting the credentials in the Shared Drives page of the Docker Desktop Settings and then restart Docker

![](https://i.stack.imgur.com/YH7nD.png)

Here is the most recent build output from Visual Studio

```
1>------ Build started: Project: MyProject, Configuration: Debug Any CPU ------
1>MyProject -> C:\MyProjects\MyProject\MyProject\bin\Debug\netcoreapp3.1\MyProject.dll
2>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
2>docker-compose  -f "C:\MyProjects\MyProject\docker-compose.yml" -f "C:\MyProjects\MyProject\docker-compose.override.yml" -f "C:\MyProjects\MyProject\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose15694150546677200279 --no-ansi up -d
2>Creating network "dockercompose15694150546677200279_default" with the default driver
2>Creating MyProject ...
2>Creating MyProject ... done
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```
Here is the content of my `docker-composer.yml` file

```
version: '3.4'

services:
  myproject:
    image: ${DOCKER_REGISTRY-}myproject
    build:
      context: .
      dockerfile: MyProject/Dockerfile
    volumes:
      - photos:/app/Storage

volumes:
  photos:

```

Here is the content of my `Dockerfile`

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["ProjectName/ProjectName.csproj", "ProjectName/"]
RUN dotnet restore "ProjectName/ProjectName.csproj"
COPY . .
WORKDIR "/src/ProjectName"
RUN dotnet build "ProjectName.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ProjectName.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProjectName.dll"]

```

I tried to remove all images on my machine using the following command
```
docker system prune -a
```

But still getting the same issue.

I shared the C_DRIVE to ensure there is no folder issues.
![Screenshot_7](https://user-images.githubusercontent.com/24724371/72115039-6c651c80-32fa-11ea-8a8e-b7f138b27c91.png)

![Screenshot_8](https://user-images.githubusercontent.com/24724371/72115041-6ec77680-32fa-11ea-9b88-b4b395276c79.png)

**Comment by pratiksanglikar** [comment]
Hi @CrestApps ,
Thank you for reporting the issue.
Are you running the docker inside a VM?
The shared screenshots of drive sharing suggests that they are not screenshots of Docker desktop.
You can check if drive sharing is working for **docker desktop** by -
1. Find a docker desktop icon in your task bar (a whale icon)
2. Right click on the whale icon and click on Settings
3. From the left pane, click on Shared Drives
4. Ensure that the drive are shared correctly.

![DockerDriveSharing](https://user-images.githubusercontent.com/1625492/72117816-ec43b480-3303-11ea-95de-f4d3c44bb5f7.png)

**Comment by CrestApps** [comment]
@pratiksanglikar Docker Deaktop is not available for Windows 7. Docker desktop unfortunately work on Windows 10. I installed Docker toolbox along with Oracle VirtualBox. 

After installing Docker toolbox, I run the terminal which installed everything that is needed and ran Docker. I then opened Oracle VirtualBox manager, clicked on the settings of the “default” machine, clicked on “Shared Folders” And finally added the C_Drive as you can see in the screenshots I provided earlier.

**Comment by bhattvaibhav** [comment]
I am also getting the same issue.  While running from the docker compose. 

**Launching failed because the directory '/remote_debugger' in the container is empty. This might be caused by the Shared Drives credentials used by Docker Desktop being out of date. Try resetting the credentials in the Shared Drives page of the Docker Desktop Settings and then restarting Docker.**

Is it related to permission issue? Also did not see any option related shared drive in docker desktop...

========== Preparing Containers ==========
Getting Docker containers ready...
C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\user.name\AppData\Local\Temp\GetVsDbg.ps1" -Version vs2017u5 -RuntimeID linux-x64 -InstallPath "C:\Users\user.name\vsdbg\vs2017u5"
AuthorizationManager check failed.


I saw above error in container tools when I debug it creates the image and after 2-3 seconds it exits. 

Can you guide how I can resolve this issue?

![image](https://user-images.githubusercontent.com/71937961/118138972-8cdc4400-b424-11eb-8a23-fdf8ad34aa7c.png)

**Comment by HamedNaghdi** [comment]
I have this problem too. Has any one find a solution for this issue?

**Comment by NCarlsonMSFT** [comment]
@HamedNaghdi is your Docker Desktop configured to use Hyper-V or WSL? To check look at the value of "Use the WSL 2 based engine" in the General settings of Docker Desktop.

**Comment by Arman-Espiar** [comment]
i got same error on vs 2022 and docker desktop using WSL 2

**Comment by dbreshears** [comment]
@Arman-Espiar, can you please open a separate issue with detailed information or a repro for what you are facing

**Comment by Arman-Espiar** [comment]
> @Arman-Espiar, can you please open a separate issue with detailed information or a repro for what you are facing

I found the fix in this [Ansewer](https://github.com/microsoft/DockerTools/issues/226#issuecomment-582169213). 
the _C:\Users\MyPC\vsdbg\vs2017u5_ was empty.

**Comment by Hei-Lima** [comment]
Hey, if anyone is having the same problem in VS2022, go to the Docker Desktop app → Settings → Resources → WSL Integration. I noticed that I didn’t have any distro installed, so I installed Ubuntu using `wsl --install Ubuntu` and it worked!

<img width="1597" height="1017" alt="Image" src="https://github.com/user-attachments/assets/68d129d2-5ab3-49a9-9963-18662b11d6db" />
