### ISSUE TITLE
Feature: possibility to set env variables for Docker build

### ISSUE THREAD

**Issue by sibbl** [microsoft/DockerTools#227]
Currently it's not possible to set i.e. `DOCKER_BUILDKIT=1` for a single project, e. g. in the `launchSettings.json`.

It's necessary to set it for the whole system or current user on Windows, but it might be helpful to be able to set it per project.

**Comment by pratiksanglikar** [comment]
Docker Desktop [2.3.5.0](https://docs.docker.com/docker-for-windows/edge-release-notes/#docker-desktop-community-2350) makes BuildKit feature enabled by default.
