### ISSUE TITLE
How to publish container image from CI server

### ISSUE THREAD

**Issue by ryudice** [microsoft/DockerTools#228]
Are there any guides on working without a UI? all the guides I have found are for publishing from within visual studio. What about if you want to build and publish the container image from the command line? such as the case for running in a CI server.

**Comment by machie27** [comment]
Hi @ryudice ,

Are you talking about building containers in docker? Then the [docker ](https://docs.docker.com/engine/reference/commandline/build/) documentation should suffice if you want to build with the CLI. If you're talking about pushing to container registries, that depends on what your using as a container registry. Most of the big ones have good documentation on that as well. Mostly it'll consists of logging in with [docker login](https://docs.docker.com/engine/reference/commandline/login/) on that registry server and [pushing ](https://docs.docker.com/engine/reference/commandline/push/)the container there. Is that what you meant?

Hope I could help.

Stephen
