### ISSUE TITLE
multiple launchSettings for Docker not honored

### ISSUE THREAD

**Issue by bklooste** [microsoft/DockerTools#230]
I see different behaviors  if I have 2 sections , the port number of the 2nd is ignored but environment variables are correctly passed to the container. 

If i comment out the docker section I get object not found on trying to debug into container 

    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
      "environmentVariables": {},
      "httpPort": 58042
    },
    "Docker-integration": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/swagger",
      "httpPort": 53105,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "Endpoints:rsa-events": "http://host.docker.internal:19093/itest/rsa-events/",
        "Endpoints:rewards": "http://host.docker.internal:19093/itest/rewards/",
        "Endpoints:betinfo": "http://host.docker.internal:19093/itest/betinfo/",
        "Endpoints:cerberus": "http://host.docker.internal:19093/itest/cerberus/",
        "Endpoints:pm": "http://host.docker.internal:19093/itest/pm/"
      }

**Comment by pratiksanglikar** [comment]
A fix for this issue has been internally implemented. We will update you when it is available for download.

**Comment by pratiksanglikar** [comment]
A fix for this issue is now available in preview release. Try out the fix by installing the most recent preview from https://visualstudio.microsoft.com/vs/preview/ .

**Comment by machie27** [comment]
This one is partially fixed, however a new bug is opened and awaiting a fix. See the comments in https://developercommunity.visualstudio.com/content/problem/892815/not-able-to-build-containers.html

**Comment by machie27** [comment]
Can confirm this is now fixed in the latest release!
