### ISSUE TITLE
Container orchestrator helm api versions out of date

### ISSUE THREAD

**Issue by laurencee** [microsoft/DockerTools#232]
The helm files generated by the `Add` -> `Container Orchestrator Support` context option contain quite outdated `apiVersion` references.

`deployment.yaml` specifies `apps/v1beta2` which at this stage should be `apps/v1`

`ingress.yaml` is a little more tricky since it has a completely different path as of Kubernetes 1.14. The way the helm command line templating works around this is with the following templating:
```
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
```

---
On a less important note, it's really nice that secrets are auto templated but there should probably also be a configmap or a variable range available for regular environment variables.

**Comment by dbreshears** [comment]
@laurencee , thanks for point this out.  The VS tooling integrates the Azure Dev Spaces SDK which scaffolds these files when adding container orchestration support,  it looks like there is an effort in the Dev Spaces SDK to update to Helm 3 which shouldl address this.   https://github.com/Azure/dev-spaces/issues/272.

**Comment by dbreshears** [comment]
Azure Dev Spaces was deprecated,  closing as external
