### ISSUE TITLE
Build Failure unable to prepare context: unable to evaluate symlinks in context path

### ISSUE THREAD

**Issue by ericwj** [microsoft/DockerTools#235]
Either Visual Studio or Docker is unable to resolve paths to my source repo because it is on a VHDX and my Source folder is a symlink to a folder named Source on that virtual disk.

Note that it is conveniently assumed that this error is non-critical, although apart from pulling base images the build didn't do anything noticeable so this error is critical.

After doing `Add Docker Support` and running a build, I get the following error.
```
========== Warming up container(s) for ProjectName ==========
Starting up container(s)...

docker build 
-f "C:\Users\Eric\Source\ProjectName\src\ProjectName\Dockerfile"
--force-rm -t projectname:dev --target base 
--label "com.microsoft.created-by=visual-studio"
--label "com.microsoft.visual-studio.project-name=ProjectName" 
"C:\Users\Eric\Source\ProjectName" 

unable to prepare context: unable to evaluate symlinks in context path:
CreateFile C:\Users\Eric\Volume{012345678-0123-0123-0123-0123456789abc}: 
The system cannot find the file specified.

A non-critical error occurred while getting the container(s) ready. Your project(s) will continue to function normally. The error was: Docker command failed with exit code 1.
unable to prepare context: unable to evaluate symlinks in context path:
CreateFile C:\Users\Eric\Volume{012345678-0123-0123-0123-0123456789abc}: The system cannot find the file specified.
```
Relevant PowerShell commands will yield:
```
PS> dir C:\Users\Eric

    Directory: C:\Users\Eric

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
l----           5/16/2018  1:45 AM                Source -> Volume{012345678-0123-0123-0123-0123456789abc}\Source

```

I know for a fact Docker doesn't handle a very similar situation either since I wanted to put the [`data-root`](https://docs.microsoft.com/nl-nl/virtualization/windowscontainers/manage-docker/configure-docker-daemon#configure-docker-with-a-configuration-file) path on a Storage Spaces virtual disk on Windows Server 2019 linked to a directory on C: and that also produced errors on `docker pull`.

**Comment by dbreshears** [comment]
Closing as this is external to Docker
