### ISSUE TITLE
Blazor Wasm on Docker-Compose?

### ISSUE THREAD

**Issue by rasert** [microsoft/DockerTools#236]
Is there or will it be in future, support for running Blazor WebAssembly (with Nginx) with the Visual Studio debugger running with Docker-Compose?

When trying something like this, I get this error:

> CTC1030 Value cannot be null
> Parameter name: stream

I tried to change the target of the Blazor project from .NetStandard2.1 to netcoreapp3.1 but then it can't find Mono packages.

UPDATE:

When I try to run the project alone using Docker, I get this error:

> Debugging Error
> Unable to find the target operating system for the project xxx.

But I placed the correct information on the csproj

`<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>`

**Comment by pratiksanglikar** [comment]
@dbreshears , do we have any plans to support Blazor apps on VSMac?
