### ISSUE TITLE
Debugging Azure Functions v3

### ISSUE THREAD

**Issue by gregorybleiker** [microsoft/DockerTools#237]
I'm trying to debug a Azure Functions project of version ~3 in VS 2019. This is failing because the function host is mounted as a volume from %appdata%\AzureFunctionsTools\Containers\Releases\2.46.0\linuxCLI, which still contains v2 of the function host. How can I upgrade the linuxCLI to 3.x ? (The error I'm getting is similar to this: https://github.com/Azure/azure-functions-dotnet-extensions/issues/32)

**Comment by NCarlsonMSFT** [comment]
@gregorybleiker I've checked, this is a bug in 16.4.5 (current version in the release channel). This has already been fixed in 16.5.0 Preview 4.0 (available in the [preview channel](https://visualstudio.microsoft.com/downloads/)).

**Comment by NCarlsonMSFT** [comment]
@gregorybleiker I've verified this is now working in the release channel. Please re-open if you are still having issues.
