### ISSUE TITLE
Node.js Missing In Build-on-Host

### ISSUE THREAD

**Issue by kalebmccalllancom** [microsoft/DockerTools#238]
I've added docker support to a legacy Angular 4.4/Dotnet Core 2.0 application. I am using Windows containers as the Angular AOT compiler was for some reason failing when run from a Linux container. This application works fine when built into a container and run.

Exception:
```
InvalidOperationException: Failed to start Node process. To resolve this:.

[1] Ensure that Node.js is installed and can be found in one of the PATH directories.
    Current PATH enviroment variable is: C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\ContainerAdministrator\AppData\Local\Microsoft\WindowsApps;C:\Program Files\dotnet;
    Make sure the Node executable is in one of those directories, or update your PATH.

[2] See the InnerException for further details of the cause.

This exception was originally thrown at this call stack:
	System.Diagnostics.Process.StartWithCreateProcess(System.Diagnostics.ProcessStartInfo)
	System.Diagnostics.Process.Start()
	System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
	Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.LaunchNodeProcess(System.Diagnostics.ProcessStartInfo)
```

Dockerfile:
```
FROM microsoft/aspnetcore:2.0-nanoserver-sac2016 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/aspnetcore-build:2.0-nanoserver-sac2016 AS build
WORKDIR /src
COPY ["<project-name>/<project-name>.csproj", "<project-name>/"]
COPY ["<project-name>-Common/", "<project-name>-Common/"]
RUN dotnet restore "<project-name>/<project-name>.csproj" -s "https://api.nuget.org/v3/index.json" -s "C:/src/<project-name>-Common/"
COPY . .
WORKDIR /src/<project-name>
RUN dotnet publish "<project-name>.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=build C:/app/ .
ENTRYPOINT ["dotnet", "<project-name>.dll"]
```

Here are the files available to the virtual mount
![containers](https://user-images.githubusercontent.com/46658427/75408989-4401b200-597c-11ea-89a3-2614392ef182.png)

Ideally I would be able to include C:\Program Files\nodejs in the mount and add it to the PATH used within the build-on-host virtual container thing. I am unsure how to do this, or if it is at all possible with the current tools, please advise

**Comment by dbreshears** [comment]
@kalebmccalllancom . Can you try adding this below to your <webapp>.csproj which will volume mount the nodejs folder and set a path to it in the container.   I was able to make this work using default Dockerfile added to an asp.net core 2.1 angular app which used image mcr.microsoft.com/dotnet/core/aspnet:2.1-nanoserver-1903


`<DockerfileRunArguments>-v "C:\Program Files\nodejs:C:\Program Files\nodejs:ro" -e "PATH=C:\Windows\system32;C:\Windows;C:\Program Files\dotnet;c:\program files\nodejs" </DockerfileRunArguments>`
