### ISSUE TITLE
Support reusing compose definition when running Docker profile

### ISSUE THREAD

**Issue by kobellem** [microsoft/DockerTools#241]
In a multi-project solution we should be able to reuse the docker-compose definition for running a single project. This would be useful for more complex setups that have shared file mounts and network definitions. Right now it's possible by configuring this using the `DockerfileRunArguments` in each project file, but this creates a lot of updates to be done when the setup changes and is error-prone.

**Use case:**
The docker-compose file contains all definitions to setup the whole environment, a developer can then start the application outside of visual studio using `docker-compose up`. He then manually stops the project he wants to work on, goes into visual studio and launches it, by reusing the docker-compose definition we can ensure that the setup stays the same.

**Comment by bwateratmsft** [comment]
@haniamr there's some new attach capabilities in the container tools window that can help here, right?

**Comment by haniamr** [comment]
Sorry I totally missed this. Yes, you can use the Containers window in VS to attach to a running container (either Windows or Linux).

**Comment by dbreshears** [comment]
Our tooling in VS 2022 now supports specifying a subset of services via profiles which should address this.
