### ISSUE TITLE
Containers Window doesn't show running containers with latest WSL2

### ISSUE THREAD

**Issue by rodolphocastro** [microsoft/DockerTools#242]
Using Docker Desktop with the latest WSL2 kernel the Containers Windows doesn't show a single running container, even when I launch containers from within Visual Studio:
![image](https://user-images.githubusercontent.com/2666310/76961277-db16b580-68fb-11ea-8f81-54b00da38e23.png)

Extension version is `0.1.1910.202`, Windows Version is `19041.153`. 

`docker version` output:

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by rodolphocastro** [comment]
It seems VisualStudio somehow gets lost when there's a `%userprofile%/.docker/config.json` present in the system. Removing the config.json made the Container Window work as intended:
![image](https://user-images.githubusercontent.com/2666310/76986124-fc899880-691f-11ea-84b2-c30db94b17cd.png)

**Comment by dbreshears** [comment]
@rodolphocastro , glad this is resolved for you,   what was in your config.json?   I have the same file present and not able to reproduce this.   I also have the same docker and os version as you. What version of VS?   My extension version is a bit more recent and maybe something that is fixed but I don't recall anything specific.

**Comment by rodolphocastro** [comment]
@dbreshears there were some configs for setting the http_proxy, here's the file:

```json
{
    "credsStore": "desktop",
    "proxies": {
        "default": {
            "httpProxy": "http://proxy.company.interno:3128",
            "httpsProxy": "http://proxy.company.interno:3128",
            "noProxy": ".company.interno, .company.com.br"
        }
    },
    "stackOrchestrator": "swarm"
}
```
