### ISSUE TITLE
docker-compose ignores DockerfileFastModeStage attribute

### ISSUE THREAD

**Issue by FWest98** [microsoft/DockerTools#244]
Currently, when using docker-compose support in VS, the generated `docker-compose.vs.debug.g.yml` file simply takes the first target from the `Dockerfile` when in fast mode. This ignores the possible custom value you can set in the MSBuild property `DockerfileFastModeStage`. It would be nice if this attribute would be incorporated in the docker-compose part as well.

Current work-around is to define the `target` property in a `docker-compose.vs.debug.yml` file.

**Comment by dbreshears** [comment]
Thanks for the feedback.  Seems like a reasonable request.  This is one of those items where the compose tooling was created before the single Dockerfile experience and is the documented approach.   

We likely can't get to this right away but will keep it open for investigation to see if we can also honor this MSBuild property from compose,  but still have docker-compose-vs.debug.yml override if specified there as well.

**Comment by D3MaxT** [comment]
Definitely +1 to this request.
Just ran into this today and wasted like 2 hours researching why my multistage dockerfiles weren't working with Compose in debug mode.

Ugh. Please add some priority to this.

**Comment by NickMaev** [comment]
Any news?

**Comment by dbreshears** [comment]
It's on our backlog,  bumped the priority.

**Comment by dbreshears** [comment]
@NickMaev .  Thanks again for the feedback. When digging into this we unfortunately realized this is a much larger work item than we  anticipated in our compose tooling, and have not been able to prioritize with the other work we have.   Given the easy workaround and interest in this,  our plan is to add the workaround to our official [documentation](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019#:~:text=Docker%20Compose%20MSBuild%20properties%201%20DockerComposeBaseFilePath%20%3D%20null%2Fundefined%3A,%3D%20..%5Cmydockercompose%3A%20files%20will%20be%20up%20one%20level.).

**Comment by vardalis** [comment]
Still not addressed 4 years later?

**Comment by fiveisprime** [comment]
@vardalis, as mentioned above, this isn't something that we're going to pick up due to the effort required for the change and it being supported in the compose config. You'll need to add the `target` setting with the specific tag in the `build` property for the service in your compose config file.

This is documented in the [compose build settings](https://learn.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019#customize-the-docker-build-process) document.

**Comment by vardalis** [comment]
Thanks for the feedback @fiveisprime! I didn't realize until later that single container setup is different from docker compose setup and that one can override the generated docker-compose.vs.debug.g.yml by the way you suggest here.
