### ISSUE TITLE
AbsoluteOutputAssemblyPath.cache not refreshed when switching targets

### ISSUE THREAD

**Issue by FWest98** [microsoft/DockerTools#246]
When switching targets (Windows to Linux), the cached file `AbsoluteOutputAssemblyPath.cache` (in `obj/Container`) does not seem to refreshed; causing this Windows-path to be used in Linux-commands:
`docker exec -i <env> -w "/app" <id> sh -c ""dotnet" <nuget> "c:\app\somefile.dll" | tee /dev/console"`
Obviously, this fails as it is not valid. Manually removing the cached file solves the issue. Note that the working directory was set correctly. Furthermore, other cached entries in this folder seem to be updated properly as well.
I did notice that when running Linux containers, this cached value was not recreated, this seems to suggest that it is not used in Linux normally, and therefore might be 'forgotten' to be removed.

**Comment by pratiksanglikar** [comment]
Hi @FWest98 , thanks for reporting this issue.
Can you please confirm following things for me?
1. You are using single project experience and not docker-compose?
2. What version of Visual Studio are you facing the issue with?
3. What is the version of `Microsoft.VisualStudio.Azure.Containers.Tools.Targets` referenced in your project?

**Comment by FWest98** [comment]
This has to do with the single project experience; I had a compose project in there as well but this concerns the switch from single project Windows to Linux containers. I did this by adding Docker support to the project again, choosing Linux, and then choosing to recreate the Dockerfile.

This concerns VS version 16.5.0, with package version 1.9.10.

**Comment by pratiksanglikar** [comment]
Thank you for getting back with the required information quickly.
We have identified the issue and it's under investigation.
Meanwhile if you are blocked, please try upgrading the nuget package to version 1.10.8.

**Comment by dbreshears** [comment]
Closing stale issue.
