### ISSUE TITLE
Docker logs

### ISSUE THREAD

**Issue by iAlexanderMoon** [Microsoft/DockerTools#25]
When debugging/running MANY containers the Output Debug can be VERY verbose. Being able to attach to the logs of the specific container using the docker cli would be useful. As well as other container monitoring tools such as kitematic.

Is there another way to start the containers such that standard out and error can also go to docker container? Basically an alternative to:
```
entrypoint: tail -f /dev/null
```

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
