### ISSUE TITLE
Fast mode, user secrets and non-root user?

### ISSUE THREAD

**Issue by rsirny** [microsoft/DockerTools#250]
I am developing Linux-based ASP.NET Core container application. My environment is Windows 10 and Visual Studio 2019 Professional with default Fast Mode container development mode. I have added a non-root user account to my image (see below) and it seems to work ok with the exception of user secrets which are by default mounted to `/root/.microsoft/...`. Is there any way to affect how the user secrets are mounted?

```dockerfile
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-alpine3.11 AS base
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
RUN addgroup  myapp && \
    adduser -S -u 1000 -G myapp myapp 
USER myapp 
EXPOSE 8080

#...
```

**Comment by bwateratmsft** [comment]
There isn't today, but you can probably use `<DockerfileRunArguments>` MSBuild property to add some `-v C:\Users\...:/home/myapp/.microsoft/...` mapping (so, the same folder on the host would be mapped to two places in the container).

**Comment by rsirny** [comment]
@bwateratmsft thanks, I ended up using `<DockerfileRunArguments>-v "$(USERPROFILE)\AppData\Roaming\Microsoft\UserSecrets:/home/myapp/.microsoft/usersecrets:ro"</DockerfileRunArguments>`. 

Should I close the issue?

**Comment by bwateratmsft** [comment]
I'd say keep it open for now, we're still investigating ways to better support running as not-root in both VS and VSCode.

**Comment by ggirard07** [comment]
This is going to be even more prevalent with dotnet 8 docker image shifting to rootless mode...

**Comment by dbreshears** [comment]
This is addressed in the next preview version of VS 2022 (17.7 Preview 2),  for .NET 8 only.

**Comment by ggirard07** [comment]
@dbreshears Can you provide a bit more details about how this is going to work?

**Comment by dbreshears** [comment]
@ggirard07,   we volume mount UserSecrets folder to both root and app users

${{APPDATA}}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
${{APPDATA}}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro

**Comment by ggirard07** [comment]
@dbreshears so if I use my own image which define its own non-root user, let's say "myapp" instead of the default name selected by the dotnet team, I will get straight back into same issue as those looks static?

**Comment by fiveisprime** [comment]
Closing this as fixed. @ggirard07, I'd recommend creating a suggestion over on [Developer Community](https://developercommunity.visualstudio.com/VisualStudio) regarding any further improvements; however, it looks like you're set.
