### ISSUE TITLE
Not compatible with Shared Projects

### ISSUE THREAD

**Issue by mrjrt** [microsoft/DockerTools#251]
We currently use a Shared Project to surface our non-code bits of our solution (i.e. cloudformation, etc), and I've been banging my head against the error message "value cannot be null" for the last two days whilst trying to add in docker-compose debugging support.

I've just realised it was because the .shproj is at the top level, adjacent to the solution, where our dockerfile is (and has to be for our CI pipeline). @bwateratmsft's comments in #174 about the heuristic logic looking for projects clicked with me and I tried deleting the project files and now I get sensible error messages about other issues.

Please, please, please handle that error more gracefully and give a more useful message than:
```
error CTC1030: Value cannot be null.
error CTC1030: Parameter name: stream
```

As well as that, could you please make it a bit smarter about unrecognised projects so it ignores, or even just warns about ones it doesn't support?

This has been an issue for some time, i.e. #141  #124 #212 #174 ...and probably a fair few others.

I'm using VS2019 (16.5.3)

**Comment by dbreshears** [comment]
Thanks for the feedback.  Will bump the priority on this and look into whether we can do something about the project association. As a first step I agree we should be giving a much better error message and will look into a fix for that.

**Comment by pratiksanglikar** [comment]
A fix for this has been internally implemented. We will notify you when the fix is available to download.

**Comment by pratiksanglikar** [comment]
A fix for this issue has been released.
Please download the latest VS version from - [https://visualstudio.microsoft.com/downloads/](https://visualstudio.microsoft.com/downloads/)

You can now specify the projects to ignore using the MSBuild property - `<DockerComposeProjectsToIgnore>`
This MSBuild property can be specified in dcproj and it contains the `;` separated list of all the projects that need to be ignored.

Projects can either be specified as absolute paths or relative paths from the solution directory.
