### ISSUE TITLE
Capture build warnings on Azure DevOps

### ISSUE THREAD

**Issue by rosieks** [microsoft/DockerTools#255]
Please solve issue of capturing build warnings and errors in Azure DevOps while building docker image via dotnet build. This issue is already solved while using dotnet build task by providing dedicated logger that writes in format expected by Azure DevOps. I believe that it can be solved same way in docker builds. The only problem is that necessary logger is not distributed to public. Here is related issue: https://github.com/microsoft/azure-pipelines-tasks/issues/7749

**Comment by dbreshears** [comment]
closing as this is external to the Visual Studio Docker tooling.
