### ISSUE TITLE
Build Helm Chart does not support helm 3

### ISSUE THREAD

**Issue by greggbjensen** [microsoft/DockerTools#256]
microsoft.visualstudio.azure.kubernetes.tools.targets\1.1.0\build\Helm.targets gives the following error when helm 3 is installed and you run `Build Helm Chart` from Visual Studio.

![image](https://user-images.githubusercontent.com/1800213/81956753-ec610300-95c8-11ea-97cf-db693149f2df.png)

`EXEC : error : unknown flag: --save`

This is because of this line, where `--save` is not a supported flag in helm 3.

```xml
<Exec Command='helm package --save=false -d "$(HelmRepositoryDirectory)" "%(_HelmChart.Identity)"' />
```
Can this be updated to conditionally add the flag, maybe with a `<Helm3Enabled>true</Helm3Enabled>` property or something?

There is also an additional error for `Install Helm Chart`:

`EXEC : error : must either provide a name or specify --generate-name`

This is from the following code:

```xml
<Exec Command='helm install "%(_HelmChart.Identity)" $(_HelmKubernetesContextArgument) $(_HelmValuesFileArgument)' />
```

Here is the current command options for helm 3:

https://helm.sh/docs/helm/helm_package/

**Comment by dbreshears** [comment]
@greggbjensen,   we can likely do something to address this like you mention and should be able to get to it soon.    I was able to workaround this by 

- removing ` Sdk="Microsoft.NET.Sdk.Web"` from the project element, 
- adding ` <Import Sdk="Microsoft.NET.Sdk.Web" Project="Sdk.props" />` to the top directly under the project block.
- adding  `<Import Sdk="Microsoft.NET.Sdk.Web" Project="Sdk.targets" />` to the bottom of the project block.
- then add a "HelmPackage" target override with supported helm3 options below the Sdk.targets import.

**Comment by greggbjensen** [comment]
Just wanted to copy over what you had posted on the other issue.  Here is what I am trying:

```xml
<Project>

	<Import Sdk="Microsoft.NET.Sdk.Web" Project="Sdk.props" />

	<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Kubernetes.Tools.Targets" Version="1.1.0" />
  </ItemGroup>
	<Import Sdk="Microsoft.NET.Sdk.Web" Project="Sdk.targets" />

	<Target Name="HelmPackage" Inputs="@(_HelmChart)" Outputs="%(Identity).output" Condition="'$(HelmSkipPackage)' != 'true'">
		<MakeDir Directories="$(HelmRepositoryDirectory)" />
		<Message Text="Packaging Helm chart '%(_HelmChart.Identity)'..." />
		<Exec Command='helm package -d "$(HelmRepositoryDirectory)" "%(_HelmChart.Identity)"' />
	</Target>
</Project>
```

**Comment by greggbjensen** [comment]
@dbreshears that fixed the support for Helm 3 as a workaround.  Thanks.

**Comment by greggbjensen** [comment]
#257 is an issue I submitted as a suggestion for general life-cycle extensibility.  I think this will be great for this feature.

**Comment by traderhut** [comment]
Still an issue with Visual Studio 2019, 10 months later.  You indicated this should be able to be fixed quickly above...   I want to try this out (new to Helm), but it crashes if I try to build it in visual studio...

**Comment by dbreshears** [comment]
@traderhut .  Apologize.  Support for helm 3 ended up not getting in due to the workaround and the 2 commands being provided by our Azure Dev Spaces tooling extension which Dev Spaces announced deprecation in 2020 so work on the tooling was de-prioritized.   

I tested the workaround and appears to be working in the latest 16.11.   Does the workaround of overriding the HelmPackage target not work for you?

**Comment by dbreshears** [comment]
Closing stale issue, the helm support no longer exist as it was deprecated with the Azure Dev Spaces tooling
