### ISSUE TITLE
Allow override of DependsOnProperties

### ISSUE THREAD

**Issue by greggbjensen** [microsoft/DockerTools#257]
So I have run into a couple issues like helm 3 not being supported, that I would like to workaround.  The easiest way I think to do this would be to allow someone to override the DependsOn properties similar to how the build process works.

That would mean changing `Helm.targets` first property group to look have a condition:

```xml
<PropertyGroup>
  <HelmLintDependsOn Condition="'$(HelmLintDependsOn)' == ''">HelmCreateChartItems;HelmLintCore</HelmLintDependsOn>
  <HelmBuildDependsOn Condition="'$(HelmBuildDependsOn)' == ''">HelmLint;HelmBuildRequiredCharts;HelmDependencyUpdate;HelmPackage</HelmBuildDependsOn>
  <HelmPushRequiredDockerImagesDependsOn Condition="'$(HelmPushRequiredDockerImagesDependsOn)' == ''">HelmPushRequiredDockerImagesOfChart;HelmPushRequiredDockerImagesOfRequiredCharts</HelmPushRequiredDockerImagesDependsOn>
  <HelmInstallDependsOn Condition="'$(HelmInstallDependsOn)' == ''">HelmBuild;HelmPushRequiredDockerImages;HelmInstallCore</HelmInstallDependsOn>
</PropertyGroup>
```

Then for someone to quickly override and add helm 3 support they could do the following in their project file:

```xml
<PropertyGroup>
  <HelmBuildDependsOn>HelmLint;HelmBuildRequiredCharts;HelmDependencyUpdate;HelmPackageOverride</HelmBuildDependsOn>
</PropertyGroup>

<Target Name="HelmPackageOverride" Inputs="@(_HelmChart)" Outputs="%(Identity).output" Condition="'$(HelmSkipPackage)' != 'true'">
  <MakeDir Directories="$(HelmRepositoryDirectory)" />
  <Message Text="Packaging Helm chart '%(_HelmChart.Identity)'..." />
  <Exec Command='helm package -d "$(HelmRepositoryDirectory)" "%(_HelmChart.Identity)"' />
</Target>
```

Here is the example from the .NET build process:

https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-extend-the-visual-studio-build-process?view=vs-2019#override-dependson-properties

**Comment by greggbjensen** [comment]
I would like to suggest this as a workaround for #256 as well as general life-cycle extensibility for this very useful feature.

**Comment by dbreshears** [comment]
Closing stale issue, the helm support no longer exist as it was deprecated with the Azure Dev Spaces tooling
