### ISSUE TITLE
Feature - Add support (new XML tag) to start only specific services

### ISSUE THREAD

**Issue by mjoksa** [microsoft/DockerTools#258]
Let's say that I have docker-compose file with 20 services (containers) in it. 
Now, imagine that I want to debug/start only 5 of them cause I do not need/want to wait for all other to start. 
With current available tags/settings in dcproj file I was not able to make this happen. 
Is it possible to have this implemented in near future? As a reference, Rider already has this possibility :)

**Comment by pratiksanglikar** [comment]
A feature to ignore certain projects from Docker-Compose is already underway.
We will update this thread when that feature becomes generally available.

**Comment by pratiksanglikar** [comment]
A fix for this issue has been released.
Please download the latest VS version from - https://visualstudio.microsoft.com/downloads/

You can now specify the projects to ignore using the MSBuild property - `<DockerComposeProjectsToIgnore>`
This MSBuild property can be specified in dcproj and it contains the `;` separated list of all the projects that need to be ignored.

Projects can either be specified as absolute paths or relative paths from the solution directory.
