### ISSUE TITLE
Missing output file '0BF51CDE-3F92-4658-A23E-B9790F86C1BB'.

### ISSUE THREAD

**Issue by dmelinosky** [microsoft/DockerTools#259]
I have a project that I've added the container tools to and when I select build, it always rebuilds the project even if nothing has changed.

I turned on diagnostic logging for the MSBuild project build output verbosity and for the MSBuild project build log file verbosity.

Each time I select build, the first line is the following:

1>Project 'Users' is not up to date. Missing output file '0BF51CDE-3F92-4658-A23E-B9790F86C1BB'.

If I remove the package, the build behavior is as expected and if nothing has changed, the project is not rebuilt.

Is this a known issue?  Is there a workaround?

**Comment by AlexeyKourakolov** [comment]
I have same problem with 0BF51CDE-3F92-4658-A23E-B9790F86C1BB guid :(

**Comment by dbreshears** [comment]
@dmelinosky, @AlexeyKourakolov ,  do either of you have a repro project you can share?  I haven't been able to come up with anything related to this guid.

**Comment by dmelinosky** [comment]
Here's some repro steps that are working for me:

1. Create a new C# 4.7.2 MVC project.  (I didn't add docker support when I created it with the wizard)
2. Set the MSBuild project output verbosity to Diagnostic.

![image](https://user-images.githubusercontent.com/1643620/89734453-23a94980-da2a-11ea-81ef-cbcd8b54dc03.png)

3. Build it a few times, the first time you'll see all the output, the next few times it will say the project is up to date.
![image](https://user-images.githubusercontent.com/1643620/89734649-59026700-da2b-11ea-93ad-4af5add4a5a4.png)

4. Right click on the project, use Add - Docker Support
![image](https://user-images.githubusercontent.com/1643620/89734661-7a635300-da2b-11ea-99c2-3435210604ef.png)


5. Set the project configuration to IIS Express or Docker
5. Build again.  The first thing in the output window should be something similar to 1>Project 'dockerextdemo' is not up to date. Missing output file '0BF51CDE-3F92-4658-A23E-B9790F86C1BB'.

![image](https://user-images.githubusercontent.com/1643620/89734708-bdbdc180-da2b-11ea-89d0-5e61641de8f1.png)

and when the build completes you'll see it did in fact build the project

![image](https://user-images.githubusercontent.com/1643620/89734803-61a76d00-da2c-11ea-9983-77723b98c0a0.png)

**Comment by dbreshears** [comment]
@dmelinosky . Thanks I can repro and we are investigating a fix

**Comment by dmelinosky** [comment]
Great, thanks 👍

**Comment by NCarlsonMSFT** [comment]
@dmelinosky the "file" 0BF51CDE-3F92-4658-A23E-B9790F86C1BB is added to the project to prevent the up-to-date checker in the C# project system from skipping calling msbuild (which has some docker steps the project system doesn't know about)
You can opt-out of this behavior by adding:
```
  <ItemGroup>
    <UpToDateCheckOutput Remove="0BF51CDE-3F92-4658-A23E-B9790F86C1BB" />
  </ItemGroup>
```
To the bottom of your project after the import of the Microsoft.VisualStudio.Azure.Containers.Tools.Targets.targets
*Optional:* To maintain most of the behavior for skipping the up to date check you can also add a property:
```
  <PropertyGroup>
    <DisableFastUpToDateCheck>true</DisableFastUpToDateCheck>
  </PropertyGroup>
```
If you don't add that property then whenever you need a container to be started for F5 you will need to first run clean or change a file to force a build on the next F5.

**Comment by NCarlsonMSFT** [comment]
@dmelinosky we are pursing a more long term fix, but we don't have a timeline for when it will be available. When it comes it should look very similar to these steps.
