### ISSUE TITLE
Error on build when on network with corporate proxy

### ISSUE THREAD

**Issue by Strifex** [Microsoft/DockerTools#26]
When attempting to build an ASP.NET Core 1.1 WEB API templated project within Visual Studio 2017 (and on a network that requires an authenticated proxy to get outside), I continually get this error:

MSB4018	The "EnsureVsDbgExists" task failed unexpectedly.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (407) Proxy Authentication Required.

I have added the proxy string into my docker for windows container and yet nothing seems to work.  Is there a special configuration required for the VS build tools to acknowledge the proxy settings?

**Comment by mmaguigan** [comment]
@Strifex, I am in a similar ship. I use tools like cntlm to resolve my needs (plus that allows me to discriminate on which hosts get proxied and which hosts don't when applications do not support such distinctions).

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
