### ISSUE TITLE
Docker container exited - Cannot find the container with the name starting with <containerName>

### ISSUE THREAD

**Issue by vickykrbu** [microsoft/DockerTools#260]
Hi All,

I have installed docker and VS 2019 in Windows server 2019 and from here i execute my web application code. When i add Docker-Compose, It pulls the related image file for application and when i try to execute the Docker-Compose, Then it is throwing one error popup called: Cannot find the container with name starting with <containername>.
When i run this command "docker ps -a" then i can see the container is present but status is "Exited".

Below are the Docker-compose.yml file content:
`version: '3.4'

services:
  devexpress_3d:
    image: ${DOCKER_REGISTRY-}devexpress3d
    build:
      context: .\DevExpress_3D
      dockerfile: Dockerfile
`

I tried to run the container manually it runs and again after few seconds it gets exited.
The i am running in another server which have Windows 10 installed. There everything is working fine.

Please suggest to fix this issue.

**Comment by pratiksanglikar** [comment]
Hi @vickykrbu ,
If I understand correctly, you are having difficulty running your application from Windows Server 2019.
Please make sure that the user group `Users` have permissions to following directories on your host machine -
```
 - C:\Users\<username>\AppData\Roaming\ASP.NET\Https
 - C:\Users\<username>\AppData\Roaming\Microsoft\UserSecrets
 - C:\Users\<username>\source\repos\WebApplication10\WebApplication10
 - C:\Users\<username>\onecoremsvsmon
 - C:\Users\<username>\source\repos\WebApplication10
 - C:\Program Files\dotnet\sdk\NuGetFallbackFolder
 - C:\Users\<username>\.nuget\packages
```
![image](https://user-images.githubusercontent.com/1625492/90198863-d6a9d800-dd87-11ea-8cf6-b678f2c1116b.png)

**Comment by dbreshears** [comment]
closing stale issue.
