### ISSUE TITLE
What is correct folder mapping with wsl2

### ISSUE THREAD

**Issue by mhamri** [microsoft/DockerTools#261]
looking at [this article ](https://www.docker.com/blog/docker-desktop-wsl-2-best-practices/)

I wonder what is the correct way to map the folder with wsl2 when the visual studio doesn't support wsl yet?

I tried to figure out what is the dev workflow with wsl for asp.net core app. but look like it's still in those gray area. 
any suggestion? or maybe not the time to switch to wsl2 yet?

**Comment by fiveisprime** [comment]
We shipped an update to allow for this in 17.10 Preview 1. See #417 for more information on how to configure VS to handle the mappings correctly and let us know there if you run into anything.
