### ISSUE TITLE
Parsing launchSettings.json requires applicationUrl to use VS Container Tools

### ISSUE THREAD

**Issue by mryanmurphy** [microsoft/DockerTools#263]
There is a bug or undocumented requirement in `launchSettings.json` file that prevents Docker command from properly starting a debug session.

As a repro: start from the base ASP.NET Core Web Application project template, and replace `launchSettings.json` with the below setup. Attempting to start a debug session with the Docker profile will result in an error `Debugging Error  Unable to parse the launchSettings.json file.`, but debugging with the Project profile works without any issues.

```json
{
  "profiles": {
    "WebApplication1": {
      "commandName": "Project",
      "launchBrowser": true,
      "launchUrl": "weatherforecast",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/weatherforecast",
      "publishAllPorts": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

To fix the Docker profile, `applicationUrl` must appear once in _any_ profile. For example, a profile that is otherwise not setup:
```json
{
  "profiles": {
    "WebApplication1": { "applicationUrl": "" },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/weatherforecast",
      "publishAllPorts": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

Or in iisExpress settings:
```json
{
  "iisSettings": {"iisExpress": {"applicationUrl": ""}},
  "profiles": {
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/weatherforecast",
      "publishAllPorts": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

**Comment by pratiksanglikar** [comment]
Hi @mryanmurphy,
we look at the `applicationUrl` parameter as a fallback option to determine whether to use SSL or not.
The first option it looks for is the `useSSL` property in the `Docker` launch profile.
Please include `useSSL` property in the `Docker` launch profile to continue debugging without having to specify the `applicationURL`.

`"Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "publishAllPorts": true,
      "useSSL": true
    }
`
