### ISSUE TITLE
Why I get Debug Error when I add "command" in docker-compose.yml while I'm debugging

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/DockerTools#265]
I want pass arguments to the container.

If I use `docker-compose up` to run it, it works well.

If I press `F5` in VS2019 to debug it, it shows error as below

![image](https://user-images.githubusercontent.com/4510984/87729547-3b5d2b80-c7f8-11ea-9d41-ea8fb83dc207.png)

**Comment by pratiksanglikar** [comment]
Hi @GF-Huang ,
Can you please provide us with a repro project?

**Comment by GF-Huang** [comment]
@pratiksanglikar Please try this project https://github.com/GF-Huang/DockerSample

**Comment by pratiksanglikar** [comment]
Thank you for providing the repro project. I am able to reproduce the issue. It is now under investigation.

**Comment by pratiksanglikar** [comment]
Hi @GF-Huang 
The `command:` parameter in the `docker-compose.yml` overrides the default start-up command.
Visual Studio tooling for docker-compose has a different mechanism for fasters builds (check [https://aka.ms/containerfastmode](https://aka.ms/containerfastmode) for more information). 

Coming back to your project.
You can send parameters to the `docker-compose up` command using `DockerComposeUpArguments` defined in the docker-compose project properties.
To do that, please unload the `docker-compose` project, then right-click to open project properties, and under the `<PropertyGroup>` tag, define your arguments as - `<DockerComposeUpArguments> -t test </DockerComposeUpArguments>`
Then reload the project.

To see the full list of available arguments, please visit - [https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019)

**Comment by GF-Huang** [comment]
OK, thanks.

**Comment by GF-Huang** [comment]
@pratiksanglikar I had try, but it seems not work like `command`. The arguments which I pass to `command`, they will pass to the final application's main(string[] args) by the `args` parameter, but `DockerComposeUpArguments` is pass the to `docker-compose.exe`, then act the arguments of `docker-compose.exe`.

So when I use this command to run: `docker-compose.exe up -i /data/input.csv -o /data/output.txt -e 10 -m 50 -p -w 0.25`,
it show me this:
```
Builds, (re)creates, starts, and attaches to containers for a service.

Unless they are already running, this command also starts any linked services.

The `docker-compose up` command aggregates the output of each container. When
the command exits, all containers are stopped. Running `docker-compose up -d`
starts the containers in the background and leaves them running.

If there are existing containers for a service, and the service's configuration
or image was changed after the container's creation, `docker-compose up` picks
up the changes by stopping and recreating the containers (preserving mounted
volumes). To prevent Compose from picking up changes, use the `--no-recreate`
flag.

If you want to force Compose to stop and recreate all containers, use the
`--force-recreate` flag.

Usage: up [options] [--scale SERVICE=NUM...] [SERVICE...]

Options:
    -d, --detach               Detached mode: Run containers in the background,
                               print new container names. Incompatible with
                               --abort-on-container-exit.
    --no-color                 Produce monochrome output.
    --quiet-pull               Pull without printing progress information
    --no-deps                  Don't start linked services.
    --force-recreate           Recreate containers even if their configuration
                               and image haven't changed.
    --always-recreate-deps     Recreate dependent containers.
                               Incompatible with --no-recreate.
    --no-recreate              If containers already exist, don't recreate
                               them. Incompatible with --force-recreate and -V.
    --no-build                 Don't build an image, even if it's missing.
    --no-start                 Don't start the services after creating them.
    --build                    Build images before starting containers.
    --abort-on-container-exit  Stops all containers if any container was
                               stopped. Incompatible with -d.
    --attach-dependencies      Attach to dependent containers
    -t, --timeout TIMEOUT      Use this timeout in seconds for container
                               shutdown when attached or when containers are
                               already running. (default: 10)
    -V, --renew-anon-volumes   Recreate anonymous volumes instead of retrieving
                               data from the previous containers.
    --remove-orphans           Remove containers for services not defined
                               in the Compose file.
    --exit-code-from SERVICE   Return the exit code of the selected service
                               container. Implies --abort-on-container-exit.
    --scale SERVICE=NUM        Scale SERVICE to NUM instances. Overrides the
                               `scale` setting in the Compose file if present.
```

**Comment by GF-Huang** [comment]
I think I use environment variables will be better.
