### ISSUE TITLE
Docker Compose adds all project sources in solution into each project container.

### ISSUE THREAD

**Issue by IVTore** [microsoft/DockerTools#266]
Hi,
To reproduce this:
Make a blank solution, then add three .net core web api empty projects with docker linux support.
A, B, and C
Then add Docker-Compose orchestration from project A (you can not do it through solution which is annoying).
Then add the images of other projects (B, C) to docker-compose.yml 
Run.
Examine the container contents. 
When I build the solution, Docker-compose feeds all the sources into containers.
For instance project A has a container A.
In container A which has src folder, there I can see sources of Projects A, B, C etc.
Am I doing something wrong? Or is this the expected behaviour?

**Comment by pratiksanglikar** [comment]
Hi @IVTore , This is an expected behavior to support project to project references.

**Comment by IVTore** [comment]
Thanks
