### ISSUE TITLE
docker-compose disappears from project dropdown

### ISSUE THREAD

**Issue by elangelo** [microsoft/DockerTools#267]
When adding 'Container Orchestration support' to a solution Visual studio shows a 'Docker-compose' optin in the project dropdown list:

![image](https://user-images.githubusercontent.com/1935881/89038716-24165600-d341-11ea-8305-9ffa8e150d1b.png)

When another user opens this solution this 'project' is not added to the dropdown list (docker and container tools are installed in that visual studio as well)

How can we get this button?

**Comment by pratiksanglikar** [comment]
Hi @elangelo , would you please mind checking if your startup project is set to "docker-compose" project once a new user opens the solution?

**Comment by elangelo** [comment]
The project is not set as startup project when opened by a new user.

**Comment by pratiksanglikar** [comment]
Please try setting "docker-compose" as a startup project to debug with "docker-compose" debug profile.

**Comment by elangelo** [comment]
That seems to work. It's doesn't seem very intuitive to find but seems to be ok

**Comment by paddywaan** [comment]
Why is this closed? This is aweful! Every time I build my application independently of docker, the docker-compose build configuration removes itself from being an option, and I need to repeat the incantation ritual of configuring the startup project to be set to docker compose. Why is it removed in the first place, and how is this not considered a bug?

**Comment by pratiksanglikar** [comment]
Hi @paddywaan ,
This issue doesn't address the one you are describing. Please open a new issue with detailed steps on how to reproduce and I will be happy to take a look.

**Comment by paddywaan** [comment]
Please see #275 .
