### ISSUE TITLE
docker compose run from visual studio causes error "invalid target"

### ISSUE THREAD

**Issue by ghost** [microsoft/DockerTools#268]
Trying to run an angular app using docker-compose project in visual studio. but i am getting this error

![image](https://user-images.githubusercontent.com/69152807/90602297-224afe80-e22c-11ea-8e94-e707e75c1f35.png)

my machine setup:
- visual studio professional 2019 (v16.7.2)
- docker community (v2.3.0.4 (46911))
- angular cli (version (10.0.4))

### DockerFile
`
FROM node:12.13.0 as builder

COPY ClientApp/package.json ClientApp/package-lock.json ./

RUN npm install && mkdir /ng-app && mv ./node_modules ./ng-app

WORKDIR /ng-app

COPY ClientApp .

RUN npm run build:prod

FROM nginx:latest

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /ng-app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY ClientApp/nginx/default.conf /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
`

### Docker-compose.yml
`
version: '3.4'

services:
  myui:
    image: ${DOCKER_REGISTRY-}myui
    build:
      context: .
      dockerfile: Dockerfile
`

### Docker-compose.override.yml
`
version: '3.4'

services:
  myui:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
`

### default.conf (for nginx)
`
server {

  listen 80;

  sendfile on;

  default_type application/octet-stream;

  gzip on;
  gzip_http_version 1.1;
  gzip_disable      "MSIE [1-6]\.";
  gzip_min_length   1100;
  gzip_vary         on;
  gzip_proxied      expired no-cache no-store private auth;
  gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
  gzip_comp_level   9;

  root /usr/share/nginx/html;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "upgrade";

  location / {
    try_files $uri $uri/ /index.html =404;
  }

}
`

i have tried running "docker-compose up --build" in powershell and it's working fine. so i think this could be a container tools issue or something. does anyone know how to resolve this issue?

**Comment by pratiksanglikar** [comment]
Hi @anthonydagondon ,
The Docker-Compose tools in Visual Studio 2019 are currently available for .net (.NET Core, .NET Framework) projects at the moment.
Support for using Single container is outlined in this document - [https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019](https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019)

To continue using Docker-Compose with Node/Angular projects please give a try to our VS Code extension - 
[https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)

**Comment by dbreshears** [comment]
Closing stale issue
