### ISSUE TITLE
Container Tools window stopped working, gives error: "An item with the same key has already been added"

### ISSUE THREAD

**Issue by kasperhhk** [microsoft/DockerTools#269]
I was creating some demo projects that were using VS2019 Container Tools to run docker, and somehow i managed to break the container tools permanently across all projects.

Whenever i debug the container list is now empty, and it says an error occured.
When i click details it just says:
"Container Tools Extensions
An item with the same key has already been added."

![image](https://user-images.githubusercontent.com/4959424/92679543-fdc4dc80-f328-11ea-9d0d-5bb781e136f5.png)

![image](https://user-images.githubusercontent.com/4959424/92679556-04535400-f329-11ea-81dc-de2091f30834.png)

Quite frustrating and useless errormessage, and there is no error details anywhere.

I don't think it's a docker issue, as i deleted all data from docker.
Docker is working fine, the container is working fine.

It is just the container tools that doesn't work.

I'm using Visual studio 2019 Version 16.7.3, Docker desktop community version 2.3.0.4 (46911)

**Comment by pratiksanglikar** [comment]
Hi @kasperhhk, I have been trying to reproduce this issue without any success.
Do you have the repro steps that I can follow?

**Comment by christian-be** [comment]
I encountered the same issue in my setup, @ravipal already had a look at the issue and it's most likely caused by duplicate environment variables. In my case, HTTP_PROXY, HTTPS_PROXY and NO_PROXY env-vars are set multiple times inside the container.

Snippet of output from docker inspect:
```
"Env": [
           "http_proxy=”… ",
           "HTTP_PROXY=”… ",
           "https_proxy=”… ",
           "HTTPS_PROXY=”… ",
           "no_proxy=”… ",
           "NO_PROXY=”… "
           "HTTP_PROXY=”… "
           "http_proxy=”… ",
           "HTTPS_PROXY=”… ",
           "https_proxy=”… "
           "NO_PROXY=”… ",
           "no_proxy=”… ",
            …other, non duplicate env-vars
          ]
```

**Comment by Jalalx** [comment]
This happened to me and the root cause was a duplicate environment variable.
Thank you @christian-be !

**Comment by dbreshears** [comment]
An old issue that should be fixed in latest builds. Closing
