### ISSUE TITLE
Executed command on run from VS 2017

### ISSUE THREAD

**Issue by libsamek** [microsoft/DockerTools#27]
Currently there is no way of knowing, which command is executed in container when we do Start from Visual Studio using Docker. Entrypoint on development container is set to `tail -f /dev/null` but there is no way of knowing which command is executed to run an app.

When everything works, it's fine and great, but sometimes start of application fails and there is no way of knowing what went wrong.

Example of output in case of error:
```
Did you mean to run dotnet SDK commands? Please install dotnet SDK from: 
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
The program '' has exited with code 145 (0x91).
```

Error by itself does not provide enough information. Plus the above link is very useless.

It would be very useful if we could see what command is actual exectued and the option to change it.

**Comment by DavizOWNS** [comment]
Agreed. And it would be nice to have optional pre-run command which would be useful if your app has to wait for other containers to start.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!

**Comment by dejvid-smth** [comment]
What additional information do you need ? The problem still stands and is relevant. This issue should not be closed.

**Comment by bwateratmsft** [comment]
@dejvid-smth You are correct, this issue is still relevant so I am reopening it. Thank you!

**Comment by brunobertechini** [comment]
+1. Very low feedback from docker tools for Visual Studio. This should be given more attention (the whole project actually) due to the fact this will be used more and more.

**Comment by BigMorty** [comment]
Thanks @brunobertechini for you feedback. My name is Mike Morton and I have recently taken over as PM for the Visual Studio container tools. I just checked VS2017 (15.9.8) and noticed when I F5 to start debugging an ASP.NET web app or Console app (both .NET core and full Fx) that we do output the command used to start the container. Are you not seeing this message in the Output window? Specifically, you should see it in the Build pane of the Output window.

**Comment by JRC86** [comment]
@BigMorty 
I tried building a docker image by right-clicking a dockerfile inside VS. That command was not shown in output window, but I'm fairly sure I have seen it before?

I'm documenting my user experience for this as I learn. I wouldn't want to clutter this post with the potential issues I have found and would really prefer to email someone who might be interested in this.

**Comment by bwateratmsft** [comment]
@JRC86 Are you looking in the "Build" output window? I see the build command here when I right-click > Build Docker Image:

![image](https://user-images.githubusercontent.com/36966225/57789412-b8b97780-76ed-11e9-81b9-6fbcac99c2f8.png)

**Comment by JRC86** [comment]
@bwateratmsft 
That line and the next one are not shown for me. This one has an image already and a container.
![dockerbuildoutput](https://user-images.githubusercontent.com/10474768/57790806-c695e980-773b-11e9-8331-55f367fe8722.jpg)

The  following screen shows building a docker image without actually running the initial build that runs when switching profile to Docker.
![dockerbuildoutputnoprevimg](https://user-images.githubusercontent.com/10474768/57791913-255c6280-773e-11e9-961b-0d0351eaff5c.jpg)

Both builds failed, meaning the command is displayed in an error message. Is this by design?
I read my notes and found that the command is not visible whenever there is an error on build.

I'm going to do some more testing.

**Comment by bwateratmsft** [comment]
@JRC86 What version of the Microsoft.VisualStudio.Azure.Containers.Tools.Targets package does your project reference? I tested with the latest (1.7.8), I suppose older versions maybe did not output the build command used.

**Comment by JRC86** [comment]
@bwateratmsft  
Version 1.4.10.
I updated to 1.7.8 and You are right, it works. the build command is now shown.

**Comment by BigMorty** [comment]
Great to hear @JRC86! Thanks @bwateratmsft for helping solve this!
