### ISSUE TITLE
WorkerService Dockerfile is wrong

### ISSUE THREAD

**Issue by Pilchie** [microsoft/DockerTools#271]
---
**Issue moved from dotnet/aspnetcore#25584**
- Please respond to @mihaimyh.

---

_From @mihaimyh on Thursday, September 3, 2020 9:15:48 PM_

When generating a Dockerfile for a worker service using latest net5-preview8 from Visual Studio Version 16.8.0 Preview 2.0 the runtime image is wrong.

The fix is using `mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim`.

```
- FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim AS base
+ FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
```
Using `mcr.microsoft.com/dotnet/runtime:5.0-buster-slim` will result in the following error:
```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '5.0.0-preview.8.20414.8' was not found.
  - No frameworks were found.

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=5.0.0-preview.8.20414.8&arch=x64&rid=debian.10-x64

```

**Comment by Pilchie** [comment]
---
**Issue moved from dotnet/aspnetcore#25584**
- Please respond to @blowdart.

---

_From @blowdart on Thursday, September 3, 2020 9:23:00 PM_

@richlander Where should this go?

**Comment by Pilchie** [comment]
---
**Issue moved from dotnet/aspnetcore#25584**
- Please respond to @BrennanConroy.

---

_From @BrennanConroy on Wednesday, September 9, 2020 8:37:39 PM_

@MichaelSimons Could you move this issue to dotnet-docker?

**Comment by Pilchie** [comment]
---
**Issue moved from dotnet/aspnetcore#25584**
- Please respond to @MichaelSimons.

---

_From @MichaelSimons on Wednesday, September 9, 2020 8:44:28 PM_

This doesn't belong in https://github.com/dotnet/dotnet-docker from the looks of it.  It looks like an issue for https://github.com/microsoft/dockertools instead.  @pratiksanglikar do you agree?

**Comment by Pilchie** [comment]
---
**Issue moved from dotnet/aspnetcore#25584**
- Please respond to @pratiksanglikar.

---

_From @pratiksanglikar on Wednesday, September 9, 2020 10:35:52 PM_

@MichaelSimons , Yes, I would say it belongs to [https://github.com/microsoft/dockertools](https://github.com/microsoft/dockertools).

@mihaimyh it is expected since it is a preview version of .NET5, please use nightly version of .NET5 to get around this issue.
Please change images to `mcr.microsoft.com/dotnet/nightly/aspnet:5.0` and `mcr.microsoft.com/dotnet/nightly/sdk:5.0` in the dockerfile.

The images are correctly scaffolded for projects using released bits of .NET.

**Comment by dbreshears** [comment]
Closing as this should be resolved now that .Net 5 is released
