### ISSUE TITLE
Ability to pass --env-file argument in docker-compose

### ISSUE THREAD

**Issue by earthslasthope** [microsoft/DockerTools#273]
The issue I'm having is I can't see a way to pass a custom env-file in Visual Studio when debugging my docker-compose project. I can see there is a DockerfileRunEnvironmentFiles property that allows doing this for single projects (docker run) but there is nothing similar for docker-compose. Furthermore, I can't find a documented way to pass any custom options that come after docker-compose before the commands which would take care of this (e.g. docker-compose --env-file my_vars -f docker-compose-custom.yml up).

Are there any options to accomplish this? Can I customise how the docker-compose command gets built?

For your reference I was looking at the documentation here https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019

**Comment by pratiksanglikar** [comment]
Hi @tthordarson , 
Additional arguments to the `docker-compose up` command can be passed through `DockerComposeUpArguments` property.
That being said, I tried `--env-file` with `DockerComposeUpArguments`, but `--env-file` needs to be passed before `up` as opposed to after `up`.
I am investigating how this could be achieved.

**Comment by syedhassaanahmed** [comment]
@pratiksanglikar Any update on the investigation about passing the custom env file as argument to `docker compose up` ?

**Comment by pratiksanglikar** [comment]
@syedhassaanahmed, it is an item on our backlog, but with the current priorities, there is no specific date when we can get to it.

**Comment by CriggerMarg** [comment]
@pratiksanglikar Any updates now?

**Comment by NCarlsonMSFT** [comment]
@CriggerMarg this remains on the backlog (now assigned to me) and is actually getting fairly close to the top.

**Comment by ludovicasa** [comment]
Hello,
any news on this one ?

Currently the command generated by VS adds the "--env-file" option after the "up" command:
`up -d --env-file .env.dev`

resulting in an error:

```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(402,5): error DT1001: unknown flag: --env-file
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(402,5): error DT1001: If the error persists, try restarting Docker Desktop.
```

**Comment by NCarlsonMSFT** [comment]
Sorry for the delay, this has now reached the top of the backlog and a fix is out for review. I still don't have a timeline for when the fix will be available, but it is in progress.

**Comment by raulidavid** [comment]
Please, friend @NCarlsonMSFT , let me know when it's ready. I'm having the same problem. Regards

**Comment by NCarlsonMSFT** [comment]
@raulidavid this currently available in the preview channel 17.5 Preview 4

**Comment by raulidavid** [comment]
Thanks @NCarlsonMSFT 🙏

**Comment by NCarlsonMSFT** [comment]
Sorry @raulidavid, I was flitting through too many things yesterday and omitted telling you that there is a new MSBuildProperty to support this:
```<DockerComposeEnvFilePath>myawesomefilename.env</DockerComposeEnvFilePath>```

**Comment by raulidavid** [comment]
thanks @NCarlsonMSFT  now it's working!!

**Comment by CriggerMarg** [comment]
@NCarlsonMSFT  how about updating documentation https://learn.microsoft.com/en-us/visualstudio/containers/docker-compose-properties ?

**Comment by NCarlsonMSFT** [comment]
@CriggerMarg I've added updating the docs to the backlog.

**Comment by davhdavh** [comment]
It works great, but would be nice if it was also documented :)

**Comment by fiveisprime** [comment]
Closing this as fixed. The documentation has also been updated to include the `DockerComposeEnvFilePath` property
