### ISSUE TITLE
CTC1030 Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by edokan** [microsoft/DockerTools#276]
When I try to debug a container from Visual Studio I get this error on build. It refers to the `microsoft.visualstudio.azure.containers.tools.targets\1.10.8\build\Container.targets:198`. It seems like a regression of #204. I reverted back to 1.9.5 and it is gone.

I already have "iisSettings" in my launchSettings.json. 

Please provide a way to diagnose this error, a log file or more detailed error message.

My Env:
VS2k19 Community 16.7.6 on Win 10 Prof 1909.
Docker Desktop 2.4.0.0, Engine 19.03.13

**Comment by pratiksanglikar** [comment]
Hi @edokan , would you be able to share your project with us? or sample repro project?

**Comment by edokan** [comment]
I'd like to provide a repro project, but I'm literally very new to all this docker world and do not know how to create a similar situation. I cannot share my project, but tell you that my colleagues suffer the same fate when they update their package.

This is why I ask if there is way to diagnose this, log, flags or something similar.

**Comment by pratiksanglikar** [comment]
Hi @edokan ,
Would you mind sharing the logs in the directory - `%Temp%\Microsoft.VisualStudio.Containers.Tools`?
Also, I would be interested in your `launchSettings.json` file.

**Comment by AydenWasTaken** [comment]
@pratiksanglikar i am having the same issue, but now on line 209.

Environment:
ASP .NET Core 3.1
VS 2019 16.9.2
Docker engine version: 20.10.5

I cannot find any directory like %Temp%\Microsoft.VisualStudio.Containers.Tools. Could it be located elsewhere?

launchSettings.json:
``` json
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:13564",
      "sslPort": 44319
    }
  },
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "publishAllPorts": true,
      "useSSL": true
    }
  }
}
```

**Comment by pratiksanglikar** [comment]
Hi @AydenWasTaken,
What is the version of your Visual Studio?
What version of the nuget package `microsoft.visualstudio.azure.containers.tools.targets` are you using?

**Comment by AydenWasTaken** [comment]
@pratiksanglikar 
visual studio 2019 16.9.2
microsoft.visualstudio.azure.containers.tools.targets 1.10.13

**Comment by pratiksanglikar** [comment]
Hi @AydenWasTaken,
I just tried reproducing with VS 16.9.2,NuGet package version 1.10.13 and your provided launchSettings.json, I wasn't able to reproduce the bug.
Do you mind sharing a sample repro project if you have any?
If you don't wish to provide publicly, you can create a private repo on GitHub and provide me access.

**Comment by AydenWasTaken** [comment]
@pratiksanglikar i can share the whole project with you if you'd like (its a school project). i think i am too much of a beginner with docker to reproduce the bug

**Comment by AydenWasTaken** [comment]
@pratiksanglikar https://github.com/AydenWasTaken/proepapi_bugreport
it seems that i cannot reproduce it with my project consistently. I will reclone my own project to see if it persists.

**Comment by dbreshears** [comment]
Closing this as stale.
