### ISSUE TITLE
Cannot add Azure Function project to docker-compose

### ISSUE THREAD

**Issue by ProH4Ck** [microsoft/DockerTools#278]
Hi,
I cannot add an Azure Function project to my docker-compose in Visual Studio 2019.
If I manually add service to my docker-compose.yml and try to build I got this error:
```
error CTC1031: Linux containers are not supported for XXX.AzureFunctions project.
```
Running docker-compose command from outside visual studio is working.
Thanks

**Comment by ProH4Ck** [comment]
Found solution: just move Dockerfile in another folder.

![image](https://user-images.githubusercontent.com/8057670/99426007-e6473880-2903-11eb-9325-7f89282433cc.png)

**Comment by pratiksanglikar** [comment]
Hi @ProH4Ck ,
Azure Functions is not officially supported with Docker-Compose tooling at the moment.
I am glad the workaround worked for you.
I am closing this issue, please open a new one if you face any other issue.
