### ISSUE TITLE
docker-compose.yml multiple files

### ISSUE THREAD

**Issue by Leosamus** [microsoft/DockerTools#279]
I would like to know if it is possible to add another optional file to docker-compose command in Visual Studio. Can't find anything on internet.

For example : we would like a local docker-compose.development.yml but we can't modify the docker-compose command which is launched by Visual.

Do you have any suggestion ?

EDIT 1 : With need a gitable solution to make everyone able to use it

**Comment by dbreshears** [comment]
@Leosamus , can you try adding the AdditionalComposeFilePaths MSBuild property to the .dcproj.  The docs for this are at https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019

**Comment by Leosamus** [comment]
Ah yeah it sure does the trick ! So dumb.
I don't know why I didn't find it sooner. I hope it will help other people.
Thanks !
