### ISSUE TITLE
Exception User-Unhandled no View Details

### ISSUE THREAD

**Issue by libsamek** [Microsoft/DockerTools#28]
When code hits an unhandled exception it would be nice to have a View Details "link", which opens QuickWatch. This works when running application outside of containers.

Currently you can still see a unhandled expection details in $exception variable (Locals tab or manually in Watch1 tab), but it would be much more friendlier to have a missing link.

**Comment by rajkumar42** [comment]
@libsamek  which version of VS are you using?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
