### ISSUE TITLE
Can't step-in/over/set-next-statement in attached process, breakpoints work

### ISSUE THREAD

**Issue by pasisavolainen** [microsoft/DockerTools#280]
`Version 16.9.0 Preview 1.0`

Locally built container, image `mcr.microsoft.com/dotnet/core/aspnet:3.1`

I can attach to process, but step-in, step-over and set-next statements do not work, they all appear to be letting the process run away. Build configuration *is* `Release` in that image.

Rebuilt the image with "Debug" configuration and added
```xml
    <DebugSymbols>yes</DebugSymbols>
    <DebugType>embedded</DebugType>
```
and now the stepping works.

Could the tooling warn that nothing but breakpoints will work in current binary configuration?

**Comment by pasisavolainen** [comment]
The `DebugSymbols/DebugType` don't do anything by themselves, it really needs the Debug configuration for step-in/over to work.

**Comment by dbreshears** [comment]
You also likely need to turn off optimization as well in the release config

 <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <DebugType>embedded</DebugType>
      <DebugSymbols>true</DebugSymbols>
      <Optimize>false</Optimize>
 </PropertyGroup>

This shouldn't be specific to Docker debugging in release config and would likely encounter with IISExpress debugging as well.
