### ISSUE TITLE
The command 'cmd /S /C dotnet restore "DockerAppPrueba/DockerAppPrueba.csproj"' returned a non-zero code: 1

### ISSUE THREAD

**Issue by RafaelLiendo2409** [microsoft/DockerTools#282]
I am trying to run a demo following the instructions from this page:
https://docs.microsoft.com/en-us/visualstudio/containers/hosting-web-apps-in-docker?view=vs-2019&viewFallbackFrom=aspnetcore-5.0

I ran the image in my local machine and worked fine, but when I am trying to publish it to Azure, I got:

Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Error		No se pudo ejecutar el comando de Docker. Código de salida: 1.
The command 'cmd /S /C dotnet restore "DockerAppPrueba/DockerAppPrueba.csproj"' returned a non-zero code: 1	DockerAppPrueba	C:\Users\usuario\source\repos\DockerAppPrueba\DockerAppPrueba\Dockerfile	0	

This is my docker file:

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-nanoserver-1903 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-nanoserver-1903 AS build
WORKDIR /src
COPY ["DockerAppPrueba/DockerAppPrueba.csproj", "DockerAppPrueba/"]
RUN dotnet restore "DockerAppPrueba/DockerAppPrueba.csproj"
COPY . .
WORKDIR "/src/DockerAppPrueba"
RUN dotnet build "DockerAppPrueba.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DockerAppPrueba.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DockerAppPrueba.dll"]

This is the publication:

![image](https://user-images.githubusercontent.com/44041077/103183921-fe9f6100-487a-11eb-9b4e-00731babfeab.png)

**Comment by dbreshears** [comment]
@RafaelLiendo2409 ,  this seems to be related to dotnet restore failing in the container.    You won't run into this when debugging because for perf reasons the tooling only executes the first stage of the Dockerfile with the Debug build configuration.    When you publish it executes all stages in the Dockerfile which is then hitting this issue.   If you change your build configuration to "release" and F5 / build in VS you would most likely hit the same issue.     I would look into why "dotnet restore" is failing in the container as the next step.  Might be network issue or if you are using a specific NuGet.config,  you would need to add a COPY statement in the Dockefile to ensure it is copied into the container.

**Comment by RafaelLiendo2409** [comment]
> @RafaelLiendo2409 , this seems to be related to dotnet restore failing in the container. You won't run into this when debugging because for perf reasons the tooling only executes the first stage of the Dockerfile with the Debug build configuration. When you publish it executes all stages in the Dockerfile which is then hitting this issue. If you change your build configuration to "release" and F5 / build in VS you would most likely hit the same issue. I would look into why "dotnet restore" is failing in the container as the next step. Might be network issue or if you are using a specific NuGet.config, you would need to add a COPY statement in the Dockefile to ensure it is copied into the container.

**Comment by RafaelLiendo2409** [comment]
I have updated and created other projects in Visual STudio, but it still does not work, this is the docker file... It is an standar project without any package addition. In fact it is a blank project to start developing in VS.  I do not think is it a network problem. Do I have to change anything?

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["WebAppDock2.csproj", ""]
RUN dotnet restore "./WebAppDock2.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "WebAppDock2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebAppDock2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebAppDock2.dll"]

**Comment by RafaelLiendo2409** [comment]
I have updated and created other projects in Visual STudio, but it still does not work, this is the docker file... It is an standar project without any package addition. In fact it is a blank project to start developing in VS. I do not think is it a network problem. Do I have to change anything?

#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["WebAppDock2.csproj", ""]
RUN dotnet restore "./WebAppDock2.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "WebAppDock2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebAppDock2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebAppDock2.dll"]

**Comment by dbreshears** [comment]
@RafaelLiendo2409 ,  looks default to me. What version of Visual Studio from Help->About are you running on?  I can run through this scenario with a default project on Spanish locale in our latest version and see if I reproduce.

**Comment by dbreshears** [comment]
@RafaelLiendo2409 , are you testing Linux or Windows container ?

**Comment by RafaelLiendo2409** [comment]
![image](https://user-images.githubusercontent.com/44041077/104516085-6367f480-55b9-11eb-86b0-8d0ed6f1059d.png)

I am using windows container 
![image](https://user-images.githubusercontent.com/44041077/104516191-8e524880-55b9-11eb-9e39-5f8ea29bd52b.png)

**Comment by dbreshears** [comment]
Maybe you have an outdated or preview .Net Core 5.0 SDK image?  Can you try pulling again from docker via  the command line

docker pull mcr.microsoft.com/dotnet/sdk:5.0

What does this show before and after pulling the latest

docker run -it --rm mcr.microsoft.com/dotnet/sdk:5.0 dotnet --list-runtimes

**Comment by RafaelLiendo2409** [comment]
I have just tested a default Visual Studio Web Core application, but with the Linux container, and it did work. The problem seems to be with windows container, I will execute the commands you sent me and I let you know the results

**Comment by RafaelLiendo2409** [comment]
I ran the commands you sent me...

Microsoft Windows [Versión 10.0.19042.685]
(c) 2020 Microsoft Corporation. Todos los derechos reservados.

C:\Users\usuario>docker pull mcr.microsoft.com/dotnet/sdk:5.0
5.0: Pulling from dotnet/sdk
a076a628af6f: Already exists
e79f147a4676: Already exists
7bc0d28c13d1: Already exists
11e5d642ebb0: Already exists
3a71aeae63e7: Already exists
f6ba3bfef1a6: Already exists
0eb46dc13fc1: Already exists
56383fdc8fb3: Already exists
Digest: sha256:92a5929ec1f6fde83e3a5df6b5bf83bb0761b70ab22d338d3efdf8b725658904
Status: Downloaded newer image for mcr.microsoft.com/dotnet/sdk:5.0
mcr.microsoft.com/dotnet/sdk:5.0

C:\Users\usuario>

And ...

Microsoft Windows [Versión 10.0.19042.685]
(c) 2020 Microsoft Corporation. Todos los derechos reservados.

C:\Users\usuario>docker run -it --rm mcr.microsoft.com/dotnet/sdk:5.0 dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
failed to resize tty, using default size

C:\Users\usuario>


Is anything there you can see?... I updated Visual Studio 2019 yesterday

**Comment by dbreshears** [comment]
It shows it downloaded a newer image for the SDK,  did it not fix the issue?   You can also attempt to reproduce by changing the build configuration to "Release" and F5.

**Comment by RafaelLiendo2409** [comment]
No, I got the same eror, I created a new basic web app net core with Docker using windows container... and there is still teh same error:

![image](https://user-images.githubusercontent.com/44041077/104632038-be095b00-5662-11eb-8986-cf3b47110f76.png)

**Comment by dbreshears** [comment]
Need to figure out why dotnet restore is failing in the release container build for windows containers. Assume you are on Windows 10?

One way that might help is to trim down the Dockerfile,  

FROM mcr.microsoft.com/dotnet/sdk:5.0 
WORKDIR /src
COPY ["WebApplication13.csproj", ""]
RUN dotnet restore "./WebApplication13.csproj"


Do a "Clean Solution" from the build menu, then F5 with release configuration set in VS.   This should fail due to error about c:\app folder, but then you should be able to navigate into the container using the container tools window (View -> Other Windows -> Containers).  Select the running container .  Click on the toolbar and select Open Terminal Window.   

From the "src" folder you should see WebApplication13.csproj and then run "dotnet restore" and see what the error output is.

You could also run "dotnet --info" to get more info about dotnet runtime and sdk versions inside this container.

**Comment by NCarlsonMSFT** [comment]
@RafaelLiendo2409 could you please copy any docker output from the output window? That should have a more detailed error message.

**Comment by RafaelLiendo2409** [comment]
Hi, 

 Yes I am using Windows 10.  I followed your instructions, but when the erros occurs... the actual container disappears from the window. You can see in the image I attached, I changed the docker file, the compilation process starts and it set a name to the container by it self...  but when the error happepns, that container is removed from that section...   The frist 


![image](https://user-images.githubusercontent.com/44041077/104749154-18b0be80-5718-11eb-83ae-4e45f62bb03d.png)

After error....

![image](https://user-images.githubusercontent.com/44041077/104749461-76dda180-5718-11eb-8706-cc69884413d5.png)

This is the output of the proccess

1> ---> Running in 5308f894def2
1>  Determining projects to restore...
1>C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [C:\src\WebApplication13.csproj]
1>C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   No such host is known. (api.nuget.org:443) [C:\src\WebApplication13.csproj]
1>C:\Program Files\dotnet\sdk\5.0.102\NuGet.targets(131,5): error :   No such host is known. [C:\src\WebApplication13.csproj]
1>Removing intermediate container 5308f894def2
1>The command 'cmd /S /C dotnet restore "./WebApplication13.csproj"' returned a non-zero code: 1
1>C:\Users\usuario\source\repos\WebApplication13\Dockerfile : error CTC1014: No se pudo ejecutar el comando de Docker. Código de salida: 1.
1>C:\Users\usuario\source\repos\WebApplication13\Dockerfile : error CTC1014: The command 'cmd /S /C dotnet restore "./WebApplication13.csproj"' returned a non-zero code: 1
1>Compilación del proyecto "WebApplication13.csproj" terminada -- ERROR.
========== Compilar: 0 correctos, 1 incorrectos, 0 actualizados, 0 omitidos ==========

**Comment by dbreshears** [comment]
Looks like you having network issues when running a windows container.    I assume that https://api.nuget.org/v3/index.json can be accessed from the host?  

You can bypass Visual Studio check in the container from the command line

docker run -it mcr.microsoft.com/dotnet/sdk:5.0 cmd
ping api.nuget.org

I would recommend trying to reset Docker Desktop to factory defaults and if you still can't make windows containers work I  would reach  out to the windows container team at https://github.com/microsoft/Windows-Containers or post something on  stackoverflow to see if they have ideas on troubleshooting the networking issues.

**Comment by RafaelLiendo2409** [comment]
I can acces http://api.nutget.org/v3/index.json as you can see
![image](https://user-images.githubusercontent.com/44041077/104969036-19ae4e00-59ad-11eb-9033-a3a05ceeeac3.png)

**Comment by dbreshears** [comment]
Can you access the Nuget url from the windows container?  You can try by  running the following from a windows command prompt

docker run -it mcr.microsoft.com/dotnet/sdk:5.0 cmd

Now from the command prompt in the container run

curl https://api.nuget.org/v3/index.json

**Comment by RafaelLiendo2409** [comment]
I do not know if you a want this:

![image](https://user-images.githubusercontent.com/44041077/106496639-bdeec500-6482-11eb-81de-bcd6f20d1896.png)

Then I received:
![image](https://user-images.githubusercontent.com/44041077/106496673-ca731d80-6482-11eb-87af-fb4cfd53368b.png)

And finally I ran this: 

![image](https://user-images.githubusercontent.com/44041077/106496720-d5c64900-6482-11eb-84f5-5966a6a5dda2.png)

**Comment by dbreshears** [comment]
Ok. thanks for verification.   This does seem to be a windows container networking issue.

**Comment by RafaelLiendo2409** [comment]
Do you have any idea to solve it?, Because when I use a Linux container with Visual Studio, I do not have this problem.

**Comment by dbreshears** [comment]
I don't unfortunately as it isn't related to the Visual Studio Docker tooling but rather docker,  windows containers, and networking issue,  as the problem reproduces without the use of Visual Studio.    I would suggest posting an issue on https://forums.docker.com,  https://stackoverflow or https://github.com/microsoft/Windows-Containers with your simple repro above using curl from within the container to see if the community or team can offer suggestions on how to troubleshoot or fix.  I see a few customers have logged similar questions in the past on these forums,  so you might find a documented fix already.
