### ISSUE TITLE
updates to base image don't show up in final image

### ISSUE THREAD

**Issue by itron-jpritch** [microsoft/DockerTools#283]
I have a multistage Dockerfile to build/run my net5.0 console app into a linux container.    
The Dockerfile installs the Java runtime into the final image, after build is complete.

When I manually build the image using the command-line, everything works fine.  When I build the image from Visual Studio, it doesn't include the Java runtime.  It appears to be based on the base image prior to my installation steps.    Here is the Dockerfile:

```
FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["MetrixIDR.SessionService.csproj", ""]
RUN dotnet restore "./MetrixIDR.SessionService.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MetrixIDR.SessionService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MetrixIDR.SessionService.csproj" -c Release -o /app/publish

FROM base AS final

## Workaround for apt/jre issues
RUN mkdir -p /usr/share/man/man1
RUN apt update && apt install apt-utils -y --no-install-recommends

## Install JRE
RUN apt update && apt install default-jre -y --no-install-recommends

WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MetrixIDR.SessionService.dll"]
```

**Comment by NCarlsonMSFT** [comment]
@itron-jpritch, if you're interested this behavior is documented at https://aka.ms/containerfastmode
By default, for debugging, base is the stage that is used (although this can be configured using [DockerfileFastModeStage](https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties)). In your case I would advise changing your dockerfile to
```
FROM mcr.microsoft.com/dotnet/runtime:5.0-buster-slim AS base
## Workaround for apt/jre issues
RUN mkdir -p /usr/share/man/man1
RUN apt update && apt install apt-utils -y --no-install-recommends

## Install JRE
RUN apt update && apt install default-jre -y --no-install-recommends
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["MetrixIDR.SessionService.csproj", ""]
RUN dotnet restore "./MetrixIDR.SessionService.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "MetrixIDR.SessionService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MetrixIDR.SessionService.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MetrixIDR.SessionService.dll"]
```

Moving installing JRE to the base stage allows it be used both in debugging and production.

**Comment by itron-jpritch** [comment]
Thanks for the help.   I tried something like you suggested and had no success, which just left thinking I didn't understand how to go about it.    It's good to know it was my implementation that wasn't working, not my understanding.
