### ISSUE TITLE
Issue while installing container tool extension

### ISSUE THREAD

**Issue by innocentqa** [microsoft/DockerTools#288]
I have installed latest Visual studio community 16.8.5 with Dot net framework 4.8.0484. For a sample docker based project (project file name docker-compose.dcproj), it showed incompatible. So I have tried to install VS container tool extn (0.1.1910.202) But getting error that -- 
02/18/2021 14:23:13 - Installation of Microsoft.VisualStudio.Containers.Tools.Extensions failed. The extension has a lower version than required by Visual Studio. Please help.

**Comment by NCarlsonMSFT** [comment]
@innocentqa, you don't need to install an extension, you need to install a component. Which workloads do you have installed for VS? If you have "ASP.Net and web development", "Azure development", or ".NET Core cross-platform development" you should have the components you need.

Just in case the workload isn't working as expected you can also use the "Individual Component" tab and select "Container development tools"

**Comment by innocentqa** [comment]
Please close the issue for now. I have installed that component installed but still it shows incompatiable project.

**Comment by innocentqa** [comment]
Please close the issue for now. I have installed that component installed but still it shows incompatiable project.

**Comment by innocentqa** [comment]
Please close the issue for now. I have installed that component installed but still it shows incompatiable project.
