### ISSUE TITLE
Docker orchestration doesn't use all layers of Dockerfile

### ISSUE THREAD

**Issue by derekgreer** [microsoft/DockerTools#289]
Microsoft Visual Studio Professional 2019
Version 16.8.6
VisualStudio.16.Release/16.8.6+31019.35
Microsoft .NET Framework
Version 4.8.03752

[ExampleDockerWebApi..20210222-1614046987.zip](https://github.com/microsoft/DockerTools/files/6026434/ExampleDockerWebApi.20210222-1614046987.zip)

### The symptom: It _appears_ docker-compose.yml doesn't pass build args when building images.
I have an example app with a docker-compose.yml which defines a build args of VERSION with a value of 2.3.4.5.  The WebAPI project's Dockerfile uses this build arg to set the Version parameter when building and publishing, with a default of 2.0.0.0 if unset.  Upon hitting the version endpoint, it _should_ return the set version (i.e. 2.3.4.5).  It instead returns 1.0.0.0.  

When launched from the command line via a simple ```docker-compose build && docker-compose up -d```, hitting the endpoint returns the expected version of 2.3.4.5.

### The actual issue: docker-compose.yml trickery
The docker-compose.yml file seems to be being overridden by generated docker-compose files in the obj folder (e.g. docker-compose.vs.debug.g.yml) which launches the container with a mount of the project's source from the host system rather than using the layers actually built by the project's Dockerfile.  The binaries which are executed are therefore not the same as those published by the image. 

Ultimately, what I expect to happen is for the docker-compose.yml file to work exactly as it would if I launched it outside of Visual Studio, just with the ability to attach the debugger.

**Comment by NCarlsonMSFT** [comment]
@derekgreer this is an optional performance enhancement. If you want the VS tools to just build the entire image you can set the msbuild property "DockerDevelopmentMode" to "Regular".
For more on this optimization see: https://aka.ms/containerfastmode 
For more configuration options see: https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019

**Comment by derekgreer** [comment]
Awesome ... aside from my embarrassment of having not found and read the documentation before opening an issue 😂

Thanks!
