### ISSUE TITLE
Debugging feels slow

### ISSUE THREAD

**Issue by libsamek** [Microsoft/DockerTools#29]
When you try to expand a variable it takes a couple of seconds to actually expend.

It would be very nice if that was instant, as it normally is, outside of containers.

**Comment by rajkumar42** [comment]
@libsamek logs would help the investigation. 

If you are on Visual Studio 15.2 or lesser use https://github.com/Microsoft/MIEngine/wiki/Logging . On 15.3 or greater use the commands to turn logging on/off. 

```
DebugAdapterHost.Logging /On:"FileName"
```
or
```
DebugAdapterHost.Logging /On /OutputWindow
```

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
