### ISSUE TITLE
Can't add Blank Node.js Console application to docker compose in VS2019

### ISSUE THREAD

**Issue by stamo** [microsoft/DockerTools#290]
I have a project which includes 14 containers, 13 of them are .Net Core applications and one Node.js console application. I'm able to orchestrate all of .net apps just with adding docker orchestration support. Unfortunately no such option for the Node.js application. I have added it manualy, but then I was not able to build the docker-compose project. Here is the error I get:

> CTC1030	Unable to find the template docker-compose.vs.debug.yml

The location is in Microsoft.Docker.Sdk:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	303

There is no problem when running **docker-compose up** from the CLI, but I can not run my docker-compose project from VS2019

Here is my Node.js app Dockerfile

``` Dockerfile
FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ["UCUMIntegration/package*.json", "./"]

RUN npm ci --only=production

COPY ["UCUMIntegration/*.js", "./"]
COPY ["UCUMIntegration/Protos/*.proto", "./Protos/"]
COPY ["UCUMIntegration/Certificates/*", "./Certificates/"]

EXPOSE 443
CMD [ "node", "app.js" ]
```

Here is my docker-compose.yml (part of it):

``` yaml
ucum.mh.local:
    image: ${DOCKER_REGISTRY-}ucumintegration
    build:
      context: .
      dockerfile: UCUMIntegration/Dockerfile
```

And docker-compose.override.yml

``` yaml
ucum.mh.local:
    ports:
      - "44392:443"
```

I've added to my UCUMIntegration.njsproj file **DockerDefaultTargetOS** and **DockerComposeProjectPath**:

``` xml
<PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
    <Name>UCUMIntegration</Name>
    <RootNamespace>UCUMIntegration</RootNamespace>
    <SaveNodeJsSettingsInProjectFile>True</SaveNodeJsSettingsInProjectFile>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
</PropertyGroup>
```
but it didn't help.

**Comment by NCarlsonMSFT** [comment]
@stamo I believe you can work around this by telling the compose tools to not attempt to handle this project (currently only C#/VB.NET are supported in VS).
There are two ways to exclude a project:
  - Add the property `<DockerComposeProjectsToIgnore>` to your .dcproj. Example: ```<DockerComposeProjectsToIgnore>path\to\AngularProject1.csproj</DockerComposeProjectsToIgnore>```
  - Put the Dockerfile for the node project in a folder under the project (be sure to update the references in the docker-compose file)

This will allow you to get everything running and debug the .NET apps, but you won't be able to debug the Node app. If you need node debugging as well I suggest trying out the [VS Code container tools](https://code.visualstudio.com/docs/containers/docker-compose) which is able to debug both.

**Comment by stamo** [comment]
@NCarlsonMSFT Thank you very much. This work arround is OK in my case. I don't need to debug the NodeJs app, but still have to be able to debug .Net applications. It worked for me.

Nevertheless it will be greate to have the ability to include and debug all kinds of VS supported application templates in docker tools. 

I think you've done amazing job with container support in Visual Studio
