### ISSUE TITLE
Using profiles with Compose

### ISSUE THREAD

**Issue by ThomasTosik** [microsoft/DockerTools#293]
Hi,

Docker-Compose supports "profiles":
https://docs.docker.com/compose/profiles/

I tried to utilize them together with VS but cant find a way to do it.

I have seen there is a DockerComposeUpArguments property that i can use but this only works for the UP command. But PROFILE is an option.  This results in UP not knowing "--profile" and hence telling me. Any way to do this?

Example that will not work (paths omitted):
```
docker-compose  -f "********\docker-compose.yml" -f "********\docker-compose.override.yml" -p dockercompose10841098029480571219 --no-ansi up -d --build --force-recreate --remove-orphans --profile login
```

Ideally (profile options moved forward):
```
docker-compose  -f "********\docker-compose.yml" -f "********\docker-compose.override.yml" -p dockercompose10841098029480571219 --no-ansi --profile login up -d --build --force-recreate --remove-orphans
```

```
> docker-compose --help
Define and run multi-container applications with Docker.

Usage:
  docker-compose [-f <arg>...] [--profile <name>...] [options] [--] [COMMAND] [ARGS...]
  docker-compose -h|--help

Options:
  -f, --file FILE             Specify an alternate compose file
                              (default: docker-compose.yml)
  -p, --project-name NAME     Specify an alternate project name
                              (default: directory name)
  --profile NAME              Specify a profile to enable
```

Regards

**Comment by pratiksanglikar** [comment]
Hi @ThomasTosik,
Official support for `profiles` is on our backlog and it would be coming to VS tooling soon.
We will let you know when it is released.
cc: @ravipal

**Comment by ravipal** [comment]
We added this feature in VS 16.10 Preview 2, please check the release notes
https://devblogs.microsoft.com/visualstudio/visual-studio-2019-v16-10-preview-2/#run-launch-services-defined-in-your-compose-files

**Comment by Thorocaine** [comment]
Hello.
This is working in VS, but by any chance does anyone know how to get it to work when building services in Azure pipelines?

**Comment by NCarlsonMSFT** [comment]
@Thorocaine the Azure DevOps tasks are supported through this repo: https://github.com/microsoft/azure-pipelines-tasks

Glancing through the code I don't see an option for the profile flag, but you may be able to use the command customization and prepend the profile argument(s) as part of your "command name"
