### ISSUE TITLE
Function App with docker compose error

### ISSUE THREAD

**Issue by blundell89** [microsoft/DockerTools#294]
Hi,

I have recently been setting up some applications to take advantage of Container Tools for VS.

One of our solutions contains both standard web app projects (targeting `Microsoft.NET.Sdk.Web`) but also has a function app project (targeting `Microsoft.NET.Sdk`).

When adding the function app to the docker-compose file, error `CTC1031` is returned: `Linux containers are not supported for DockerComposeFunctionApp project.`

I have noticed that issue #124 exists but have opened this one to focus more on the docker-compose aspect, My two questions are:

1. How can we move past this error? I have tried a [suggested workaround](https://github.com/microsoft/DockerTools/issues/141#issuecomment-522822258) but I've noticed that when using this, subsequent debugging does not use the latest source. Is there a way to always debug with the latest source (without having to manually build in the CLI)?
2. Can we raise this as a feature request? If not, it would be good to see a better explanation of the error in Visual Studio 😄 

## Reproduction

I've put a quick repro up [here](https://github.com/blunners/docker-compose-function-app). Cloning and running debug will show the error.

Thanks in advance

**Comment by pratiksanglikar** [comment]
Hi @blunners,

Functions app is not supported with docker-compose tooling.
You could get around this problem by telling the docker-compose tooling to ignore the functions project.
To do that, please specify the project in the property - `DockerComposeProjectsToIgnore`.
e.g. `<DockerComposeProjectsToIgnore>path\to\FunctionsProject.csproj</DockerComposeProjectsToIgnore>`.

**Comment by jscheeres** [comment]
Any updates on this?

**Comment by ravipal** [comment]
@jscheeres, we are working on adding docker compose support of Azure Functions. Will update you once it is released.

**Comment by ravipal** [comment]
@jscheeres the Azure Functions support is available in the [latest Visual Studio preview](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes) (17.2 Preview 2)
