### ISSUE TITLE
Docker Compose provides no way to set build target for debugging

### ISSUE THREAD

**Issue by groogiam** [microsoft/DockerTools#295]
There does not appear to be a way to customize the build target when using docker compose as there is for a single project. Single projects have the DockerfileFastModeStage property as discussed in https://github.com/microsoft/DockerTools/issues/277. The generated docker-compose.vs.debug.g.yml always uses the first target in the file and there appears to be no way to change that via a project setting.

**Comment by NCarlsonMSFT** [comment]
While there isn't a project setting, as noted in #244 you can customize the stage using [docker-compose.vs.debug.yml](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019#docker-compose-file-labels).

**Comment by groogiam** [comment]
That should work. Thanks.
