### ISSUE TITLE
Docker compose debugging does not break on exceptions

### ISSUE THREAD

**Issue by groogiam** [microsoft/DockerTools#296]
From what I can tell it looks like the the debugger does not break on exceptions when using a docker compose project.

**Comment by NCarlsonMSFT** [comment]
@groogiam can you please provide some more context? I did a quick test on my machine and was able to break at an exception. 
Some potentially helpful pointers:
This is guide on the exception handling in VS, and its configuration: https://devblogs.microsoft.com/devops/understanding-exceptions-while-debugging-with-visual-studio/
Also if you are debugging in the Release Configuration (or have set ContainerDevelopmentMode to Regular) you need to disable just my code as the optimized binaries produced in the image are not considered [user code](https://docs.microsoft.com/en-us/visualstudio/debugger/just-my-code?view=vs-2019#BKMK__NET_Framework_Just_My_Code)

**Comment by groogiam** [comment]
@NCarlsonMSFT It appears to be the just my code not working. However, I don't have release configuration or container development mode set to regular. I can confirm the exception breakpoints hit when use the vanilla web api visual studio template and adding docker compose orchestration. However on my project with the same visual studio settings applied no breakpoints are hit when an exception is thrown in my controller code. 

I've tailored the docker file and docker-compose.yml in my project, as well as moved the docker-compose code into it's own directory but I don't suspect these would break the debugging. My project is hosted in Azure Dev Ops. I could add you the repository if you would be willing to take a quick look to see if you can find any thing that would cause this behavior? Thanks.

**Comment by NCarlsonMSFT** [comment]
@groogiam It would be best if you could make a minimized repro for me to look at (avoid any potential appearance of impropriety from looking at your sources).
A few things to check in terms of your customizations:
- Are you using Debug assemblies built on your host machine mounted into the container?
- Are you using any Configuration other than Debug for the compose project?
- With your customizations is the debugger able to automatically find the symbols for your assemblies?

**Comment by groogiam** [comment]
The issue seems to have corrected itself.  I was able to reproduce it several times yesterday, but this morning after several unsuccessful tests it just started working. I'm not sure what happened but according to git I have not made any changes to my repository. In any case thanks for your help.

**Comment by groogiam** [comment]
This is started happening again. There have been no changes to my visual studio settings. The debugger seems to just selectively decide it is not going to break on exceptions.

**Comment by NCarlsonMSFT** [comment]
@groogiam I checked with the folks who own the debugger and thier recommendation was to use the Report a Problem button in VS:
![image](https://user-images.githubusercontent.com/14239288/113612660-fd619b00-9604-11eb-8e6e-9c01f5c61824.png)
Which will open a bug in Developer Community. They will be happy to investigate it from there.

**Comment by groogiam** [comment]
Reported to https://developercommunity.visualstudio.com/t/debugger-not-breaking-on-exceptions-when-using-doc/1390864

**Comment by mweel1** [comment]
+1  It randomly works and doesn't.

**Comment by dbreshears** [comment]
This is an external issue, closing here
