### ISSUE TITLE
Attach to a proces not working - unknown error 0x80131c08

### ISSUE THREAD

**Issue by onedevteam** [microsoft/DockerTools#299]
I have web api in .net core 3.1 running in a linux container started with docker-compose from bash shell on windows 10.

I'm trying to attach VS 2019 debugger to this container

![image](https://user-images.githubusercontent.com/7267540/119119857-e992bc80-ba2b-11eb-9314-b681c472ec3e.png)

every time i click attach, after 10-15 seconds, i'm getting an error

![image](https://user-images.githubusercontent.com/7267540/119119962-04653100-ba2c-11eb-844c-e475236e84ea.png)

Any idea how to resolve this?

**Comment by NCarlsonMSFT** [comment]
@onedevteam I believe https://github.com/microsoft/MIEngine would be the right place to log this issue.

**Comment by dbreshears** [comment]
Closing stale issue as external
