### ISSUE TITLE
Open Source Request

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Microsoft/DockerTools#30]
As Microsoft announced Docker Tools would be open sourced, could you consider making it open source as soon as possible?
https://blogs.msdn.microsoft.com/stevelasker/2016/11/22/visual-studio-docker-tools-support-for-visual-studio-2015-2017/

As far as I know, I can't find the open source repository for Docker Tools not only for Visual Studio 2017 but also for Visual Studio 2015. If the repository is already open sourced, please let me know.

**Comment by mmaguigan** [comment]
I would like to echo this. I have some business requirements that I would not expect the community to live with (though I'd probably be happy to submit a PR if interested). If this were an open source project, I could adjust things to meet my acceptance criteria without hackery or waiting for *N* development cycles if it makes the backlog.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!

**Comment by tanaka-takayoshi** [comment]
@bwateratmsft I have no idea why you say "inactive" because I'm waiting for Microsoft since I've created this case. I've been expecting open sourcing since Microsoft has made a public announcement. It could help me developing a VSIX tool.
In addition, I'm not able to reopen the closed issue in this repository.

**Comment by bwateratmsft** [comment]
@tanaka-takayoshi You're correct, it makes sense that this is not inactive. However it is a duplicate of #39 so I have changed the label from stale to duplicate.

**Comment by tanaka-takayoshi** [comment]
fair enough.
