### ISSUE TITLE
Docker Compose - multiple projects web-app, web-api, grpc and/or worker causing SSL issues

### ISSUE THREAD

**Issue by 3GDXC** [microsoft/DockerTools#300]
adding one or more project that uses SSL cause unrecoverable build issues which show as incorrect errors in VS2019
and using docker-compose from command line show : -

#12 1.468 /usr/share/dotnet/sdk/5.0.203/NuGet.targets(131,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json.
#12 1.468 /usr/share/dotnet/sdk/5.0.203/NuGet.targets(131,5): error :   The SSL connection could not be established, see inner exception. 
#12 1.468 /usr/share/dotnet/sdk/5.0.203/NuGet.targets(131,5): error :   The remote certificate is invalid because of errors in the certificate chain: PartialChain

**Comment by NCarlsonMSFT** [comment]
@3GDXC This looks like the issues with NuGet.ors certificate that started in January: https://devblogs.microsoft.com/nuget/net-5-nuget-restore-failures-on-linux-distributions-using-nss-or-ca-certificates/
You should be able to fix this by updating your SDK image.

**Comment by dbreshears** [comment]
Looks like this was answered, closing stale issue
