### ISSUE TITLE
docker-compose argument --no-ansi is deprecated

### ISSUE THREAD

**Issue by philipwolfe** [microsoft/DockerTools#302]
docker-compose has been warning this for a while and now it is officially deprecated.  Can we please get a quick release to fix this?  I don't think there is a way to avoid this based on the way that the `BuildDockerComposeOptions` is written.

From the Visual Studio output window:
```
docker-compose  -f "C:\SourceControl\...\docker-compose.yml" -f "C:\SourceControl\...\docker-compose.override.yml" -f "C:\SourceControl\...\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose16426688549683828944 --no-ansi build
[31moption '--no-ansi' is DEPRECATED ! Please use '--ansi' instead.
[0mnot implemented
A non-critical error occurred while getting containers ready.  Your project will continue to function normally.  The error was: [0mnot implemented
```

From Microsoft.Docker.dll Version: 2.2.9626.1
```c#
      public string BuildDockerComposeOptions(IEnumerable<string> composeProfileNames = null)
      {
        StringBuilder stringBuilder = new StringBuilder();
        foreach (DockerComposeClient.MergedDockerComposeSourceDocument composeSourceDocument in (IEnumerable<DockerComposeClient.MergedDockerComposeSourceDocument>) this._documentsToMerge)
          stringBuilder.AppendFormat((IFormatProvider) CultureInfo.InvariantCulture, " -f \"{0}\"", (object) composeSourceDocument.FilePath);
        stringBuilder.AppendFormat((IFormatProvider) CultureInfo.InvariantCulture, " -p {0}", (object) this._workspaceName);
        stringBuilder.Append(" --no-ansi");
        if (composeProfileNames != null)
        {
          foreach (string composeProfileName in composeProfileNames)
            stringBuilder.Append(" --profile " + composeProfileName);
        }
        return stringBuilder.ToString();
      }


```

**Visual Studio 2019 version:** 16.10.4
**Docker Compose version:** v2.0.0-beta.6
**Docker Version:** 
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:41 2021
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by dbreshears** [comment]
@philipwolfe.   Not sure it is related to the deprecated --no-ansi arg, although we have a fix coming for that.  

It reproduced for me when having "Use Docker Compose V2" enabled in experimental features, but only with Windows containers.  Do you have that set by chance, looks like you might looking at v2.0.0-beta.6 version?

**Comment by philipwolfe** [comment]
@dbreshears Good call!  I had that experimental feature checked.  When I unchecked it, everything works now.  
(I don't remember checking this, must have been from a while ago.  It has worked for me up till today.)

![image](https://user-images.githubusercontent.com/61720289/126855878-03f97a94-179f-4622-aa66-f6444a7a31dd.png)

**Comment by dbreshears** [comment]
Great. thanks for the confirmation.
