### ISSUE TITLE
.NetCore3.1&ReactJS SPA: Cannot publish to docker hub

### ISSUE THREAD

**Issue by gunnarsireus** [microsoft/DockerTools#304]
Starting with the project “ASP.NET Core with ReactJS” , download, build and run it. It works very well.
Add “Docker Support” for publishing as image to docker hub.
Update the dockerfile according to Microsofts documentation.
I’m using docker desktop version 3.5.2(66501).
Try to publish with the updated docker file. Its not working.
Error:
executor failed running [/bin/sh -c dotnet publish "ASPNETCore31ReactJS.csproj" -c Release -o /app/publish]: exit code: 1
2>Build failed. Check the Output window for more details.

Thanks in advance, Gunnar Siréus

**Comment by NCarlsonMSFT** [comment]
@gunnarsireus I'm assuming you looked at https://docs.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2019
If so, @ucheNkadiCode can you try following the docs so we can investigate.

**Comment by gunnarsireus** [comment]
Hello.
Follow the instruction (with Linux containers) with one exception: Publish
to your own Docker Hub, not Azure Container Registry.

It will fail:

#18 2.611   Determining projects to restore...
#18 3.276   All projects are up-to-date for restore.
#18 4.580   Project1 -> /src/Project1/bin/Release/netcoreapp3.1/Project1.dll
#18 4.585   Project1 ->
/src/Project1/bin/Release/netcoreapp3.1/Project1.Views.dll
#18 4.695   /bin/sh: 2: /tmp/tmp8d3852f4619c4e30a4fee57e39728197.exec.cmd:
npm: not found
#18 4.697 /src/Project1/Project1.csproj(38,5): error MSB3073: The command
"npm install" exited with code 127.
#18 ERROR: executor failed running [/bin/sh -c dotnet publish
"Project1.csproj" -c Release -o /app/publish]: exit code: 1
------
> [publish 1/1] RUN dotnet publish "Project1.csproj" -c Release -o
/app/publish:
------
executor failed running [/bin/sh -c dotnet publish "Project1.csproj" -c
Release -o /app/publish]: exit code: 1
2>Build failed. Check the Output window for more details.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========


Thanks in advance, Gunnar Siréus

Den tis 3 aug. 2021 kl 00:26 skrev Nathan Carlson ***@***.***

**Comment by ucheNkadiCode** [comment]
Hey @gunnarsireus! So I followed the tutorial above and I was also not able to Reproduce the Publish failure.

I have created a sample project at https://github.com/ucheNkadiCode/ClassicCoreAndReactApp. Could you verify that your Dockerfile is the same. I want to inform you that we have identified that our docker image is using a pretty old version of Node. I would suggest updating the **two places** in your Dockerfile from

```docker
RUN curl -sL https://deb.nodesource.com/setup_10.x |  bash -
RUN apt-get install -y nodejs
```
to

```docker
RUN curl -sL https://deb.nodesource.com/setup_lts.x |  bash -
RUN apt-get install -y nodejs
```
The sample project I have linked you to uses the current version of Node 10. Let us know if we can help you further.

**Comment by dbreshears** [comment]
Closing stale issue
