### ISSUE TITLE
Custom MSBuild Properties not available in UI

### ISSUE THREAD

**Issue by mtivan** [microsoft/DockerTools#306]
Hi guys,

in the latest changelog (version 1.11.1) I have found the following entry: "Show custom MSBuild properties in the UI" 
Unfortunately I have not been able to find where the custom build properties are displayed in the Visual Studio UI. 

I am running Microsoft Visual Studio Enterprise 2019 Version 16.11.3 on Windows 10. I also do have custom container related MSBuild properties defined in the csproj file. e.g. DockerfileContext. Also the version of the package is 1.11.1

Any comment or guidance where the properties are displayed will be highly appreciated. Thanks.

PS: with the custom MSBuild properties I hope you mean: https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2019

**Comment by NCarlsonMSFT** [comment]
@mtivan If you open the Properties window:
![image](https://user-images.githubusercontent.com/14239288/134047632-f79efd52-d51c-440b-a199-c450507c7be1.png)
You can see the properties DockerImageLabels, and DockerfileContext:
![image](https://user-images.githubusercontent.com/14239288/134048012-0478f10b-175d-4857-baa2-edae76345965.png)
For now, those are the only properties in the UI.

**Comment by mtivan** [comment]
Hi Nathan,

found it. thanks. 

On a slightly related note, i am trying to automate the creation of some microservice projects with the dotnet cli.
Adding docker and orchestration support is not available at the cli at the moment. i want to write a dotnet cli extension
to do this, jsut add the generic docker file, helm chart, update project properties. 

Do you know what would be the best place to ask for more information how visual studio does it, e.g. where the files come from? Do you think I will be able to utilize some VS mechanism or will i have to pull the files and update the props "manually"? Thanks for your help.

**Comment by NCarlsonMSFT** [comment]
@mtivan This is as good a place as any for that question. The VS experience for adding Dockerfiles is not accessible for that kind of automation, so you would need to make the changed manually.
