### ISSUE TITLE
"Preparing Containers" not providing docker-compose.vs.debug.g.yml anymore

### ISSUE THREAD

**Issue by JBBianchi** [microsoft/DockerTools#311]
Hello,

Since the beginning of the week, my Visual Studio 2019 seem to be unable to prepare my containers. 

I installed the latest updates for VS2019 (16.11.5), Docker Desktop (4.1.1, engine 20.10.8, compose 1.29.2, cred helper 0.6.4, k8s 1.21.5, snyk 1.563.0) & all my Windows 10 Updates but the problem persist. I tried to repair, uninstall/reinstall, clean VS cache, reset settings/user data, still the same behavior:

When I launch Visual Studio with a "Docker Compose" project in it, VS starts to prepare the containers (for "fast start" or I don't recall the exact name of the process).  In the `Container Tools` outputs:
```
Starting Docker Desktop...
========== Preparing Containers ==========
Getting Docker containers ready...
docker-compose  -f "C:\path-to-solution\deployment\docker-compose\docker-compose.yml" -p dockercompose9464286311065417946 --ansi never build
...
#15 [container build  3/30] COPY [src/Gateway/Gateway.Api/Gateway.Api.csproj, src/Gateway/Gateway.Api/]
#15 sha256:dfcd4c4f1e6bfac13a74e8fb1b8610e0ef71b4590e224402a1715c994e4525ab
#15 ERROR: "/src/Gateway/Gateway.Api/Gateway.Api.csproj" not found: not found
...
------
A non-critical error occurred while getting containers ready.  Your project will continue to function normally.  The error was: failed to solve: rpc error: code = Unknown desc = failed to compute cache key: "/src/Gateway/Gateway.Api/Gateway.Api.csproj" not found: not found
```

The same behavior appears in every solution, so it's not solution/project specific but "Visual studio-wide". As you can see, the `docker-compose` command misses an argument, it's supposed to add the `-f C:\path-to-solution\deployment\docker-compose\obj\Docker\docker-compose.vs.debug.g.yml` created by VS automagically but it doesn't. In consequence, any reference to `src/` or `app/` fails.

I don't have any idea where to look for to fix this issue. Any help would be greatly appreciated.

Best regards,

Edit:
Note that when clicking the start button "Docker Compose", the build process do use the debug yml from VS:
```
Build started...
1>------ Build started: Project: docker-compose, Configuration: Debug Any CPU ------
1>docker-compose  -f "C:\path-to-solution\deployment\docker-compose\docker-compose.yml" -f "C:\path-to-solution\deployment\docker-compose\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose9464286311065417946 --ansi never config
```
The build succeed, the container runs but the app doesn't run in the container (application unreachable, the "Logs" tab of the container displays "No logs found for this container").

Edit 2:
It's working in VS 2022 Preview.

Edit 3:
After installing VS 2022 Preview, VS 2019 works again ... makes total sense...

Edit 4:
Nevermind `Edit 3`, it's even more funky. I boot my computer, I launch the project in VS2019, it's failing (no -f debug.yml, no access to src/app, empty logs container on start). I close and I launch the project in VS2022, it works. I close and relaunch VS2019, it works ...

**Comment by JBBianchi** [comment]
@martyt I did already, it was one of my first thoughts. I removed the entire project and reclone it from our git server (so without bin/obj) but VS still failed. Just to be sure, I tried doing it again with your command but I end up with the same result.

**Comment by JBBianchi** [comment]
> @JBBianchi So things seem to be working for me now in Docker v4.1.1, but I'm not sure which of the changes I made resolved the issue:
> 
> * Debugged the solution in VS2022 Preview (latest update)
> * Repaired VS2019 installation
> * Cleared `bin` and `obj` folders in my solution
> * Deleted the `%UserProfile%\vsdbg` and %UserProfile%\onecoremsvsmon` folders
> * Deleted all solution-related containers and images
> * Rebooted my machine a few times
> 
> Others in my organization are still having no success in VS2019 and have moved to VS2022 Preview for now, having failed to get Docker v3.6 or 4.01 to work -- leading me to believe this is more of a VS problem than a Docker problem.

I tried `> * Deleted the %UserProfile%\vsdbg and %UserProfile%\onecoremsvsmon` folders` because I didn't try that (manually at least) but still facing the same problem. I did the same as your colleagues, running problematic projects on VS2022 preview.

**Comment by kondelik** [comment]
> Will keep it open until the fix for VS2019 is released.

is there any rough time estimate?

**Comment by ravipal** [comment]
The next VS update is on Nov 9th. It will have the fix.

**Comment by Vaccano** [comment]
@ravipal - After the fix is released, how do I undo the `docker-compose disable-v2` command?

**Comment by shobhitkasliwal-onbe** [comment]
docker-compose enable-v2 worked for me.

**Comment by carlos-takeapps** [comment]
Today's fix release notes does not mention this issue. Has the fix been released?

**Comment by ravipal** [comment]
The latest update to VS 2019 (16.11.6) has the fix.
