### ISSUE TITLE
VS2022 uses unlisted package Microsoft.VisualStudio.Azure.Containers.Tools.Targets 1.14.0

### ISSUE THREAD

**Issue by ArturDorochowicz** [microsoft/DockerTools#316]
When I create a new Asp.Net Core Web App in VS2022 and select Enable Docker, the generated app references  the Microsoft.VisualStudio.Azure.Containers.Tools.Targets 1.14.0 package. It works fine, but when I go to nuget.org for this package (https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/1.14.0), it tells me that the package has been unlisted: _The owner has unlisted this package. This could mean that the package is deprecated, has security vulnerabilities or shouldn't be used anymore._ This is unexpected.

**Comment by ravipal** [comment]
@ArturDorochowicz, The package was unlisted because I missed listing the package, there is no security or other vulnerabilities with this package. Now it is listed. Sorry for the confusion.

**Comment by ravipal** [comment]
@ArturDorochowicz, Version 1.15.0 is used in our next preview release 17.2 Preview 2, which is not released yet. 1.15.0 will be listed when we ship the 17.2 preview 2.

**Comment by ArturDorochowicz** [comment]
Right, my bad. Sorry for this. I thought it came with 17.1.
