### ISSUE TITLE
How can I specify the .env files for docker compose to run?

### ISSUE THREAD

**Issue by nicholasyin** [microsoft/DockerTools#317]
I found [this document](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2022) where I know how to specify if I have multiple docker compose yml files with any file names. However, this document doesn't mention anything about passing the .env files. How can I do that?

**Comment by ravipal** [comment]
@nicholasyin I think you are using the `DockerComposeBaseFilePath` to use different compose file names. Similarly, you could use `DockerComposeUpArguments` to pass different environment file using the argument `--env-file test1.env`

**Comment by nicholasyin** [comment]
Good to know. Thanks a lot.
