### ISSUE TITLE
Kubernetes/Helm Container Orchestration Support option not showing

### ISSUE THREAD

**Issue by lambdakris** [microsoft/DockerTools#319]
Hi, I am trying to use the Kubernetes/Helm container orchestration support with VS 2022. I have Kubernetes installed through Docker Desktop and KIND, however, the Kubernetes/Helm option for Container Orchestration Support is not showing.

![container support screen shot](https://user-images.githubusercontent.com/15176003/144467633-8a412234-33cd-4fa6-ae66-8e9cfc4c48c3.png)

![kube config screenshot](https://user-images.githubusercontent.com/15176003/144467878-067fea8f-b889-43d2-9677-b5dea681f880.png)

Is there something I'm missing?

**Comment by BigMorty** [comment]
Hi @lambdakris - The “Kubernetes/Helm” container orchestration support was part of our Azure Dev Spaces tooling which was deprecated along with the Azure Dev Spaces service in May 2021.

**Comment by lambdakris** [comment]
Ah, thanks for clarifying. Love a good definitive answer, at least I know it's not me.

**Comment by BigMorty** [comment]
@lambdakris, glad to help! :-)
