### ISSUE TITLE
Consider disabling UseAppHost in generated Dockerfiles

### ISSUE THREAD

**Issue by mthalman** [microsoft/DockerTools#321]
The Dockerfiles generated by VS include the following line:

```Dockerfile
RUN dotnet publish "WebApplication.csproj" -c Release -o /app/publish
```

This ends up outputting both a `WebApplication` executable and a `WebApplication.dll` library file in the output directory. Either file can be used to execute the app. The executable can be executed directly while the DLL requires the use of the .NET CLI (`dotnet WebApplication.dll`). From an image size perspective, it seems wasteful to include both files in the output. Only one of them is actually needed in order to execute the app. The Dockerfile is configured to only make use of the DLL:

```Dockerfile
ENTRYPOINT ["dotnet", "WebApplication31.dll"]
```

So it seems reasonable to simply not include the executable in the output.

By using the `UseAppHost` property, the publish logic can be configured to not include the executable in the output.

I propose that the Dockerfiles generated by the tools set this property by default:

```Dockerfile
RUN dotnet publish "WebApplication.csproj" -c Release -o /app/publish /p:UseAppHost=false
```

**Comment by bwateratmsft** [comment]
This is probably a good thing to do in vscode-docker as well.

**Comment by dbreshears** [comment]
Yep. this makes sense to do.  I've added an item on the VS tooling backlog

**Comment by devopg** [comment]
yes do this thing sync with default  as local pc build.

https://github.com/dotnet/dotnet-docker/discussions/3389

**Comment by dbreshears** [comment]
This was completed, closing
