### ISSUE TITLE
Docker Run command work's in Visual Studio but not in CLI

### ISSUE THREAD

**Issue by nickdm26** [microsoft/DockerTools#327]
My Container is running in Visual Studio as expected after clicking run perfectly fine.

I went to copy the docker run command from the build output so that I could create a docker-compose.yml file 
while doing so I noticed launching the container from the CLI with the same command causes the container to start but not run correctly. e.g. no Logs are visible via Docker Desktop.

Docker Run Command
`docker run -dt -v "C:\Users\NickMuldrew\vsdbg\vs2017u5:/remote_debugger:rw" -v "C:\Users\NickMuldrew\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Users\NickMuldrew\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" -v "C:\Users\NickMuldrew\Documents\GIT\Imports\C# Stuff\SanitzerWebhook:/app" -v "C:\Users\NickMuldrew\Documents\GIT\Imports\C# Stuff\SanitzerWebhook:/src/" -v "C:\Users\NickMuldrew\.nuget\packages\:/root/.nuget/fallbackpackages" -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_ENVIRONMENT=Development" -e "ASPNETCORE_URLS=https://+:443;http://+:80" -e "DOTNET_USE_POLLING_FILE_WATCHER=1" -e "NUGET_PACKAGES=/root/.nuget/fallbackpackages" -e "NUGET_FALLBACK_PACKAGES=/root/.nuget/fallbackpackages" -P --name SanitzerWebhook_1 -v "C:\Users\NickMuldrew\Documents\GIT\Imports\Import Processing Tool (IPT)\Input:/app/Input:rw" -v "C:\Users\NickMuldrew\Documents\GIT\Imports\Import Processing Tool (IPT)\Logs\Sanitizer:/app/Logs:rw" --entrypoint tail sanitzerwebhook:dev -f /dev/null`

This was done within Visual Studio 2022 with .NET 6

**Comment by NCarlsonMSFT** [comment]
@nickdm26 Did you know VS will generate a compose file for you: https://docs.microsoft.com/en-us/visualstudio/containers/overview?view=vs-2022#docker-compose-support

If that doesn't do what you want, then I should warn you in debug mode we do a lot of optimizations to run your code in the container faster (see [here](https://aka.ms/containerfastmode) if you're interested in the details) so a lot of what you're seeing in that command is to support reusing the same container for multiple runs to save time on F5.

If you just want to run the container normally, and assuming you've built the full dockerfile, you will want a command more like: 
docker run -dt -v "C:\Users\NickMuldrew\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro" -v "C:\Users\NickMuldrew\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro" -P -v "C:\Users\NickMuldrew\Documents\GIT\Imports\Import Processing Tool (IPT)\Input:/app/Input:rw" -v "C:\Users\NickMuldrew\Documents\GIT\Imports\Import Processing Tool (IPT)\Logs\Sanitizer:/app/Logs:rw" sanitzerwebhook

As a warning: the volume maps for /root/.microsoft/usersecrets and /root/.aspnet/https are created by VS to support using the .NET development certificate from windows in the container and should not be used in production. Once VS has set it up, you can use it outside of VS, but it will not work on a machine where VS has not already configured the project for HTTPS in a container. If you want to configure the certificate yourself, the steps are outlined in the .NET docs: https://docs.microsoft.com/en-us/dotnet/core/additional-tools/self-signed-certificates-guide

**Comment by nickdm26** [comment]
Thank you that seemed to help.
