### ISSUE TITLE
Change run arguments for .net framework projects

### ISSUE THREAD

**Issue by johnayoub** [microsoft/DockerTools#329]
Hello,

I'm currently working with a .NET Framework (4.8) project that I'm trying to add docker support to. However, I can't seem seem to find any documentation on how to add and change the run arguments or even add an extra mount. Everything points to .NET Core projects which uses a different project file structure.

**Comment by NCarlsonMSFT** [comment]
@johnayoub Have you tried using the msbuild properties from https://docs.microsoft.com/en-us/visualstudio/containers/container-msbuild-properties?view=vs-2022? You can set them in a PropertyGroup in any supported MSBuild project (SDK style is not required).

Of particular note for your scenario are:
`DockerfileRunArguments` which lets you amend to the docker run command (you can use this to add a mount)
`DockerDebuggeeArguments` which lets you modify the arguments passed to your app

**Comment by johnayoub** [comment]
@NCarlsonMSFT Yes, I can confirm that this working. Sorry I didn't realize that this isn't specific to SDK style project. Thank you!
