### ISSUE TITLE
Please add support for dotnet vstest MyApplication.dll

### ISSUE THREAD

**Issue by litan1106** [microsoft/DockerTools#333]
Please add support for dotnet vstest MyApplication.dll so we can run tests with container tool.

**Comment by NCarlsonMSFT** [comment]
The testing team has added support for running tests in a container: https://docs.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022

**Comment by litan1106** [comment]
> The testing team has added support for running tests in a container: https://docs.microsoft.com/en-us/visualstudio/test/remote-testing?view=vs-2022

I already checked out that link before I created the issue. Remote testing doesn't support multiple containers because some applications would use a mssql database for testing.

**Comment by NCarlsonMSFT** [comment]
@litan1106, your best bet is to submit a [suggestion](https://developercommunity.visualstudio.com/report?space=8&entry=suggestion) requesting support for the remote test feature supporting starting dependencies.
