### ISSUE TITLE
Unable to debug "dotnet/aspnet:6.0-alpine" with "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false"

### ISSUE THREAD

**Issue by FHFS** [microsoft/DockerTools#347]
Hello,

We are trying to debug our project, but we are having trouble debugging.
Our project requires "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false" and "dotnet/aspnet:6.0-alpine"
Our container runs fine with that environment variable set. However we get an error when starting the debugger.
```
One or more errors occurred.
Failed to launch debug adapter. Addition information may be available in the output window.
The Operation was canceled.
```
When we set "DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true", we are able to start the debug tool. 

How do we fix this?

**Comment by FHFS** [comment]
I have installed icu-lib, and it is working correctly in the container. The problem is with the debugging tool, it exits when I try to debug an image with DOTNET_SYSTEM_GLOBALIZATION_INVARIANT set to true.

**Comment by NCarlsonMSFT** [comment]
I am unable to reproduce that localy once I've installed icu-libs. Can you provide a minified repro?

For reference here is my test Dockerfile
```Dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
RUN apk update; apk add icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT false
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build
WORKDIR /src
COPY ["WebApplication20/WebApplication20.csproj", "WebApplication20/"]
RUN dotnet restore "WebApplication20/WebApplication20.csproj"
COPY . .
WORKDIR "/src/WebApplication20"
RUN dotnet build "WebApplication20.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebApplication20.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebApplication20.dll"]
```

**Comment by FHFS** [comment]
I also made a sample project where I did install ICU-LIBS and set the env variable. Where I was able to debug with 
"DOTNET_SYSTEM_GLOBALIZATION_INVARIANT true" set in the docker-compose file, debugging failed with it set to false.

Yesterday I updated Docker and VisualStudio(Preview), and now I am just unable to debug docker images.
