### ISSUE TITLE
Docker support for multiple projects in different solution folders

### ISSUE THREAD

**Issue by adeliab** [microsoft/DockerTools#348]
I have a repo structure similar to this:
- Core
  - Core.sln
    - Core.Project1.csproj
    - Core.Project2.csproj
- Api
  - Api.sln
    - Api.Project1.csproj
    - Api.Project2.csproj
    - (project reference to) Core.Project1.csproj
    - (project reference to) Core.Project2.csproj

When I right click "Add Docker Support" in my API project, I get this error
![image](https://user-images.githubusercontent.com/7829826/181222156-6bb6755b-6108-409d-9e05-d5ff0b73f742.png)

I assume this is because there are references to projects that are located in a different solution folder (the Core projects).

Is there a Docker Tools setup that would support this scenario?
I would like to have the same capability as the 'default' Docker support - with the FastMode enabled and being able to debug from VS (Code)

If I create a docker file on the root folder all the projects, will the debugger still work and be able to mount the other folders?

**Comment by NCarlsonMSFT** [comment]
I tested this locally to make sure, if you temporarily create a solution in the root directory and add the relevant projects you can add docker support to the web project. It will add the relevant files and properties to the project so that it will work from the existing solution; you can then delete the temporary solution.

**Comment by adeliab** [comment]
> I tested this locally to make sure, if you temporarily create a solution in the root directory and add the relevant projects you can add docker support to the web project. It will add the relevant files and properties to the project so that it will work from the existing solution; you can then delete the temporary solution.

i see, the file is generated. thanks!
