### ISSUE TITLE
Launch Browser Not Working

### ISSUE THREAD

**Issue by nathanpjones** [Microsoft/DockerTools#35]
My expectation is that whatever I set is for url is launched regardless of how the composition is set up. It's less clear to me how the service selection is used, but I'm guessing it has to be a .NET core service so the tools will know when startup is complete.

In any case, the launch browser setting doesn't seem to be working properly and I don't see anything in the output indicating why it's failing. I don't see any documentation for these settings.

My setup is a composition with several .NET Core services and an nginx service to proxy traffic to them. The nginx service will route https traffic from 443 and redirect 80 to https and 443. The .NET services have fixed ports that are only internally visible.

I've tried a number of different url and service combinations. So far, the only combo that actually launches a browser is `http://localhost:443` with one of my .NET Core services. But nginx coughs up an error because the protocol doesn't match the port (notice the http rather than http**s**).

Any guidance would be appreciated if I'm doing something wrong.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
