### ISSUE TITLE
IEnumerable Visualizer not available using Docker Tools with ASP.NET Core

### ISSUE THREAD

**Issue by abritabroad** [microsoft/DockerTools#352]
Please see stackoverflow issue:

https://stackoverflow.com/questions/73353896/ienumerable-visualizer-not-available-using-docker-tools-with-asp-net-core

Steve

**Comment by NCarlsonMSFT** [comment]
@abritabroad I spoke with the debugging team and they recommend opening a VS Feedback Ticket: https://developercommunity.visualstudio.com/report?space=8&entry=problem  to track this request.
