### ISSUE TITLE
Set multiple docker compose overrides with solution configuration

### ISSUE THREAD

**Issue by tomfanara** [microsoft/DockerTools#365]
I want to create 2-3 docker compose overrides as in

Dev, QA and Test. I would like to add these as Visual Studio Profile Configurations as in Debug or Release but add Dev, QA and Test and have VS switch out my overrides accordingly.

I followed a prior post in stackoverflow [Setup multiple docker-compose envs in Visual Studio](https://stackoverflow.com/questions/73035287/setup-multiple-docker-compose-envs-in-visual-studio) but it does not seem to recognize my PropertyGroup Condition="'$(Configuration)' == 'Dev'"

Any help appreciated!

**Comment by NCarlsonMSFT** [comment]
In which project is the configuration not being recognized?

Have you confirmed in the solution configuration manger that the configuration is being applied to that project (a solution configuration can apply different project configurations to different projects)?
To open the UI and check:
![image](https://user-images.githubusercontent.com/14239288/213580399-3df22eaa-4775-4628-84f4-fbacb5ad3482.png)
Which opens:
![image](https://user-images.githubusercontent.com/14239288/213580569-0786e000-83b1-482e-ad01-b897f3aa60ba.png)
This will show you a list of the individual project configurations being used for each solution configuration.

**Comment by tomfanara** [comment]
Hello thanks see below

![image](https://user-images.githubusercontent.com/90238499/213595590-7d862b52-c74a-4c05-9705-5e876bbce89c.png)

The below is my docker-compose.dcproj file

![image](https://user-images.githubusercontent.com/90238499/213595741-c9e94b20-0317-457d-8a35-b01bc04e9668.png)

below is my docker folder setup

![image](https://user-images.githubusercontent.com/90238499/213595884-8f546dcd-575b-4a47-a38a-fa915473f988.png)

**Comment by tomfanara** [comment]
Its not recognizing the dev configuration

**Comment by tomfanara** [comment]
updated docker-compose.dcproj

![image](https://user-images.githubusercontent.com/90238499/213599282-934e3212-acf8-4e45-b0fc-26db83c5b1eb.png)

**Comment by tomfanara** [comment]
Hello this fixed it for me!

https://stackoverflow.com/questions/72852490/current-solution-contains-incorrect-configuration-mappings

**Comment by NCarlsonMSFT** [comment]
Glad you were able to get unblocked! One comment as long as I've read your .dcproj: if you name your compose files: docker-compose.dev.yml and docker-compose.dev.override.yml then you can just set DockerComposeBaseFilePath to docker-compose.dev, no need for AdditionalComposeFilePaths.

You also don't need to set any property in the second PropertyGroup that has the same value as the first PropertyGroup, it doesn't hurt anything, but you don't need to maintain two copies.

**Comment by dbreshears** [comment]
Closed, since this appears to be fixed for you.
