### ISSUE TITLE
How to add a pre-launch command to the project

### ISSUE THREAD

**Issue by dazinator** [microsoft/DockerTools#370]
When I launch a docker-compose project in VS 2022, i'd like to do some initial prep. In other project types you can use a pre-build event. However for `dcproj` there isn't any such options. Is there some existing hook whereby I can run some command when the dcproj is launched (I would say or `built` but I am not sure whether this project type has build actions in the traditional sense).

**Comment by NCarlsonMSFT** [comment]
The `.dcproj` build has several extensibility points, including targets. Can you clarify what "initial prep" looks like? Are you trying to run a command in the container(s) or on the host?

**Comment by dazinator** [comment]
On the host.

I'd like to do some initial prep like to ensure an `external` network that is referenced in the compose file, is created using `docker network create` with a deterministic name. Networks owned by a compose file (e.g non external) do have the benefit that they do get auto created when the compose project is spun up, but the final network name is not deterministic as far as I can tell due to the names of networks owned by a complse file being prefixed by some gibberish value.

**Comment by NCarlsonMSFT** [comment]
In that case you should be able to have a target with a `BeforeTargets=DockerPrepareForLaunch` that runs the command you need.

As a warning: there is a chance that the targets will change in the future. That said, it hasn't been renamed in at least 6 years, so it's proven stable so far.

**Comment by dazinator** [comment]
Thanks that sounds perfect. I will give that a go.
