### ISSUE TITLE
Bug in DockerTools in Visual Studio 2022 17.5.0

### ISSUE THREAD

**Issue by dmitriyi-affinity** [microsoft/DockerTools#371]
Project with the same name:
![image](https://user-images.githubusercontent.com/89005666/220853149-e49be3a1-94b6-413d-97c5-57d0e2885071.png)

Causes build failure for the `docker-compose` project.

![image](https://user-images.githubusercontent.com/89005666/220853368-8cda70cd-55d0-482b-acf3-0831591aec06.png)

Very easy to reproduce.
1) Create solution with docker-compose
2) Add projects with the same name 
3) Use VS 2022 17.5.0, compilation will fail. In VS 2022 17.4.x everything works.

**Comment by dmitriyi-affinity** [comment]
![image](https://user-images.githubusercontent.com/89005666/220863002-91e374a7-5f75-49bc-8d1d-e814a6514d1d.png)
Unable to report a problem to the official VS Feedback site :(

Please give an advice on how to report a problem with the MS VS Feedback site.

**Comment by dmitriyi-affinity** [comment]
FYI https://answers.microsoft.com/en-us/feedback/forum/fdbk_commsite-bug/the-problem-with-the-developer-commuity-visual/e1772878-2fbb-474d-8178-6607718be1e0

**Comment by NCarlsonMSFT** [comment]
A fix for this has been submitted for 17.6 Preview 3

**Comment by dmitriyi-affinity** [comment]
Thank you for the quick resolution.

**Comment by knoxi** [comment]
Will the fix also be applied in VS 17.5?

**Comment by NCarlsonMSFT** [comment]
@knoxi: Yes the fix has been backported.
