### ISSUE TITLE
The semaphore timeout period has expired.

### ISSUE THREAD

**Issue by kr185187** [microsoft/DockerTools#375]
PS C:\WINDOWS\system32> docker pull mcr.microsoft.com/windows/nanoserver:ltsc2019
ltsc2019: Pulling from windows/nanoserver
896318806a73: Extracting [==================================================>]  103.3MB/103.3MB
failed to register layer: re-exec error: exit status 1: output: hcsshim::ProcessBaseLayer \\?\C:\ProgramData\Docker\windowsfilter\092af699329101751a7d55173e2baaf87ac5aafa538922350ce5e8b3582708ad: The semaphore timeout period has expired.

-->Using Windows containers in windows 10 Pro

**Comment by dbreshears** [comment]
@kr185187.   This seems like an issue with Docker on your machine or windows containers and unrelated to the Visual Studio tooling extension.   I would recommend posting something on https://forums.docker.com/  or https://github.com/microsoft/Windows-Containers.
