### ISSUE TITLE
Visual Studio ignores COMPOSE_FILE environment

### ISSUE THREAD

**Issue by manuelelucchi** [microsoft/DockerTools#379]
I'm using the .env file for Docker Compose so I can quickly switch properties and is completely agnostic from Visual Studio, so anyone can use whatever environment they prefer. Everything works fine, except running with Visual Studio seems to ignore the COMPOSE_FILE environment that allows you to merge multiple compose files. I know it can be done from VS also, but I would like to leave it agnostic. Any idea?

**Comment by dbreshears** [comment]
I don't believe this is something we can easily support in the extension today based on our current design and usage of "-f" and generated compose files we merge.  We would have to know to parse the .env file instead, then figure out the best way to merge this with ours, etc.. 

We track feature requests through  [Visual Studio Developer Community ](https://developercommunity.visualstudio.com/VisualStudio/suggest) if you would like to enter this there, we would prioritize investigation of this alongside other bug fixes and feature requests we receive.
