### ISSUE TITLE
VS2022 Failed to Create Certificate

### ISSUE THREAD

**Issue by adminnz** [microsoft/DockerTools#384]
I have Visual Studio 2022 Professional and Docker Desktop v4.19.0 (106363).

I am doing File -> new ASP.NET Core Web App project and have the following settings configured.
![image](https://github.com/microsoft/DockerTools/assets/1552285/921c2f89-1b79-4c23-a2c4-8fbc5cbd5463)
Then add Container Orchestrator Support to the WebApplication1 project.

Then select Docker Compose as the debug profile and then attempt to debug the application.

I get the following error:
![image](https://github.com/microsoft/DockerTools/assets/1552285/bf96896a-d6fc-4fa2-8549-f415336d98de)

It says to look at the Container Tools output but there are no errors:

```
docker exec -i 3796991df0c9 /bin/sh -c "if PID=$(pidof dotnet); then kill $PID; fi"
========== Debugging ==========
docker ps --filter "status=running" --filter "label=com.docker.compose.service" --filter "name=^/WebApplication1$" --format {{.ID}} -n 1
3796991df0c9
```

What is strange is that from my understanding the usersecrets file of the project should have an entry for "Kestrel:Certificates:Development:Password". But mine is empty.

I have tried:

- Manually deleting the certificates from Current User/Personal & Current User/Trusted Root Certification Authorities
- running dotnet dev-certs https --clean
- running dotnet dev-certs https --trust
- manually exporting a certificate using 
`dotnet dev-certs https --export-path "C:\Users\username\AppData\Roaming\ASP.NET\Https\WebApplication1.pfx" -p "f5ab2782-6309-4d59-9b1b-ad28f3078599"`
and then manually adding to the user secrets file "Kestrel:Certificates:Development:Password": "f5ab2782-6309-4d59-9b1b-ad28f3078599"

But nothing works. I can't even find out how to get more information about what the cause of the issue is.

**Comment by NCarlsonMSFT** [comment]
To generate a log file with potentially more information you can set the environment variable MS_VS_CONTAINERS_TOOLS_LOGGING_ENABLED to 'true'. The log file is created in %tmp%\Microsoft.VisualStudio.Containers.Tools

**Comment by adminnz** [comment]
I ended up having to reinstall windows for this bug to not happen.

**Comment by an2ny** [comment]
having this issue right now, what is weird is that it just popped up recently. 
any fix?
