### ISSUE TITLE
Release notes for  1.18.1

### ISSUE THREAD

**Issue by ggirard07** [microsoft/DockerTools#385]
Release note links for NuGet package Microsoft.VisualStudio.Azure.Containers.Tools.Targets redirect to this repo, but currently changelog contains only up to 1.17.0.
Is it possible to add changelog for current latest (1.18.1 as of this writing)?

**Comment by dbreshears** [comment]
Thanks for bringing this up.  We seem to have this duplicated here and on NuGet.  Will fix this and likely move to just one source.

**Comment by dbreshears** [comment]
The NuGet now contians its own changelog.
