### ISSUE TITLE
Please Open Source Sdk

### ISSUE THREAD

**Issue by tebeco** [microsoft/DockerTools#39]
in order to diagnostic why i can't use it at work.
i have to decompile the MsBuild sdk for docker i. order to under all the detection stuff like the CLI etc ...

seeing the code made me understand that if Docker is installed elsewhere than c:\program files
it will fails
or magic string like "DockerCli.exe" that are not reused
is there a way to let the community helps on that ?

**Comment by galvesribeiro** [comment]
Yeah, I agree that it should be OSS'ed in order to get traction. The current Docker tooling is so poor. It doesn't allow you debug more than one instance of the container (something that is really useful in distributed application and that Today work with Azure Cloud Services emulator and Azure Service Fabric local cluster). 

I wish we could help to improve this poor experience.

**Comment by tebeco** [comment]
sooooo 
it won’t be open source ?

**Comment by tebeco** [comment]
it’s not stale as nobody from the maintainer wanted to take the point ?

**Comment by galvesribeiro** [comment]
Yeah... looks like...

**Comment by tebeco** [comment]
this is a so bad idea 
@bwatertmsft please look at how dotnet core and vscode got enhanced

reopen that issue, remove the stale flag
and please tell the product owner to come here and explain public why this should not be opened

please let everyone help you

**Comment by bwateratmsft** [comment]
We can see that this is still a relevant issue so we're going to reopen and discuss.

**Comment by tebeco** [comment]
from what i see
> we would love to begin with the official communication from the maintainer team

this should come from you

**Comment by tanaka-takayoshi** [comment]
I come from the duplicated issue. I have been waiting for open source since Microsoft announced.
https://blogs.msdn.microsoft.com/stevelasker/2016/11/22/visual-studio-docker-tools-support-for-visual-studio-2015-2017/

**Comment by lisaguthrie** [comment]
Thanks for all the feedback. We're still discussing this request. The Docker tools have deep dependencies on the internals of Visual Studio, so this not a trivial ask, but we fully understand the desire for extensibility and enhancements. We will keep this issue open for now, and we will update it as we decide how to move forward.

**Comment by tebeco** [comment]
@lisaguthrie
 thx a lot for the answer, that beein a yes or a no but at least now we have some feedback

**Comment by tebeco** [comment]
Seems like it was a no :)
