### ISSUE TITLE
Multiple unlisted versions available on nuget.org

### ISSUE THREAD

**Issue by david-brink-talogy** [microsoft/DockerTools#394]
I'm not sure if this is the correct repository, but over the last few months package Microsoft.VisualStudio.Azure.Containers.Tools.Targets has been repeatedly pushed and then unlisted from nuget.org.  Some of these unlisted versions have been picked up by our builds while they are available.  

Is there any issue with your CI/CD process?  

https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/1.19.0
https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/1.19.1
https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/1.19.2
https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/1.19.3
https://www.nuget.org/packages/Microsoft.VisualStudio.Azure.Containers.Tools.Targets/1.19.4

**Comment by patverb** [comment]
@psiservices-dbrink Those are indeed unlisted packages. For preview releases we publish the nuget as unlisted so projects created in preview releases can pull the preview packages but the nuget isn't listed so people do not update to a preview version. When a particular version is officially released, we publicly list it (generally alongside a release of Visual Studio).

**Comment by psiservices-dbrink** [comment]
They're getting picked up by our CI/CD.  Are they available for a short time before unlisting?  

Why don't you publish them as prerelease using the [normal convention](https://learn.microsoft.com/en-us/nuget/create-packages/prerelease-packages)?  If you add a -{prerelease} suffix wouldt it meet your use case?

**Comment by patverb** [comment]
Unlisted versions should not be picked up by NuGet Api calls, only a few unofficial Api calls list them. If you are using Dependabot  in your CI/CD it's a known issue with Dependabot.

**Comment by psiservices-dbrink** [comment]
Azure Devops artifacts is picking them up because nuget.org is an upstream source.  We opened a support ticket with that team and were told that there's nothing built in that will unlist the packages in the artifact feed once they've been picked up.  

I feel like we're stuck between two Microsoft teams.  Is it possible for your team to tag prereleases according to the normal conventions?

**Comment by dbreshears** [comment]
@psiservices-dbrink.   Yes, will re-open and we can look into how to best to resolve this on our side.

**Comment by psiservices-dbrink** [comment]
I'm almost 100% sure that 1.19.4 and 1.19.5 were marked as unlisted as recently as last week.  These versions are now re-listed and available on nuget.org.  

Is this intentional?  Apologies if I'm incorrect about the relisting.

**Comment by NCarlsonMSFT** [comment]
As per the above [comment](https://github.com/microsoft/DockerTools/issues/394#issuecomment-1654255946) they were to support as of then unreleased versions of VS. Now that 17.7 and 17.8 Preview 1 shipped we listed them.

**Comment by dbreshears** [comment]
Closing, we switched to using preview tags now
