### ISSUE TITLE
Write access to /home required for functions tooling to create /home/.azurefunctions folder

### ISSUE THREAD

**Issue by ggirard07** [microsoft/DockerTools#399]
I have a solution configured with .dcproj and docker-compose I use for debugging purposes. I am now trying to add a function app project to the same solution.

Currently, when running in a non-root variant of the dotnet isolated function image, the folder `/home/.azurefunctions` needs to be pre-created before trying to start a debug session.
If folder does not exist yet, tooling tries to create it as the non-root user but does not have permission to `/home` by default. It results result in a permission denied error and fast mode fails to start the image.
My workaround for now is to create the folder in my own base image.

Looking at the content of the folder, I am not sure I understand its purpose at it always empty.

**Comment by NCarlsonMSFT** [comment]
@ggirard07 I'm not finding examples for the "non-root variant of the dotnet isolated function image". Could you point me to an example?

**Comment by NCarlsonMSFT** [comment]
@ggirard07 The error you're seeing isn't coming from the VS tools, but instead the Azure Functions CLI, specifically: https://github.com/Azure/azure-functions-core-tools/blob/v4.x/src/Azure.Functions.Cli/Common/PersistentSettings.cs

Digging through the history of the mcr.microsoft.com/azure-functions/dotnet-isolated:4-dotnet-isolated6.0 image it appears that $HOME is being set to /home. updating my Dockerfile to use
```
ENV HOME=/home/app
```
let me set-up a low privileged app user like the one used in the .NET 8 images. This however seems wrong, and I think a conversation is needed with the owners of the Azure Functions image.

**Comment by ggirard07** [comment]
@NCarlsonMSFT Thanks for digging into that. It looks like your repo get a lot of false-positive feedback due to issues in tooling you are interacting with, sorry about the noise 😅 
I also noticed the misconfiguration for $HOME when dealing with user secrets, but I also reported it in your repo (#398) as I was not sure if DockerTools should honor the $HOME configuration regardless if it made sense.

**Comment by NCarlsonMSFT** [comment]
@ggirard07 The user secrets in Azure Functions issue is next on my to-do list. As of now, the tooling doesn't support User Secrets for Azure Functions which is what needs to be addressed first. The support for the non-root user on Azure Functions is a separate issue that seems like it will need some coordination with the Azure Functions team.

**Comment by dbreshears** [comment]
Closing stale issue, workaround available.
