### ISSUE TITLE
Can't run ConfigureWindowsDockerHost.ps1

### ISSUE THREAD

**Issue by npateman** [Microsoft/DockerTools#4]
I assume I need to run this in order to be able to publish to my host but I can't find any suitable documentation.  After running it I get an error as the script can't find "C:\RuntimeSettings\docker.settings".

Any ideas?

**Comment by SteveLasker** [comment]
Hi Nick,
This content of this repo isn't meant to be used directly. The http://aka.ms/DockerToolsForVS use this powershell script as a temporary workaround until we complete the Docker Extension for Windows. 
If you're looking to do Docker Provisioning of a Docker Container Host, you can look here for Windows Containers: http://aka.ms/WIndowsContainers
Or, here (http://aka.ms/DockerToolsForVS) for the Visual Studio Tools, which cover Linux as well as Windows. As part of the experience, we create the appropriate PowerShell scripts for provisioning the Docker Container Host, as well as the ARM templates.

**Comment by npateman** [comment]
Hi Steve,

Indeed that was the page I referred to in order to setup Windows Containers in the first place, but what I'm trying to do is publish to the host using Docker Tools for Visual Studio 2015.  It says how to publish to Azure but not how to publish to a Windows Server 2016 TP3 VM I have setup, unless I missed that bit.  Both articles mentioned talk about Azure and just brush over the custom host option, it says "Enables you to connect to on-prem or localhost Docker hosts using the Custom Host option."... but how?  It doesn't mention how to get the certs applied on the server or if I can disable that entirely and just connect, if so what's the URL?  Nothing I have tried will connect and there seems to be no point of technical enquiry to get moving.

Where would you suggest I look to find this info?

Nick.

**Comment by SteveLasker** [comment]
Hi Nick,
Thanks for keeping the questions going. We're working to get all the content visible.
Here's the docs for using the Visual Studio Docker Tools, and there's a section on using a local/custom instance. 
https://azure.microsoft.com/en-us/documentation/articles/vs-azure-tools-docker-hosting-web-apps-in-docker/
Please let me know if that doesn't meet your needs. In the meantime, I'll add this link to the readme.md and the VS Gallery page.
Steve

**Comment by npateman** [comment]
Hi Steve,

I've ended up doing a couple of things here, firstly looking at those docs again and attempting to setup my own Win Server 2016 TP3 VM as a container host, but I'm still not able to validate a connection.  The new link you have provided seems to assume you know how to do that already, that's what I'm having issues with, even after running "netstat -a" on the server to assure the port is listening, I still can't get a connection which makes me think it might be down to the tls settings and not having the correct certs on both sides of the connection.

I also tried just publishing to Azure, which should be the simplest way right?  Unfortunately something seems broken there too, it seems the VM doesn't have outgoing internet access, or has some kind of DNS issues as the end of the publish process (after uploading like 180mb of files??) 

	Step 0 : FROM microsoft/aspnet:1.0.0-beta5
	Get https://ms-tp3.registry-1.docker.io/v2/: dial tcp: GetAddrInfoW: No such host is known.
	Please visit http://go.microsoft.com/fwlink/?LinkID=529706 for troubleshooting guide.	MyProject		0

I'll keep looking at it, but it doesn't look too hopeful at the moment, I'd set up a Linux machine if I thought it would be any easier, but somehow doubt it, also not sure if a Windows container will run in a Linux docker host?  I read that a Linux container won't run on a Windows docker host.

Thanks for your help btw, it's much appreciated!

**Comment by npateman** [comment]
I think I might know what the Azure issue is, there is no Security Group associated with the NIC.  So when I try and add one using Powershell (as that's the only way you can at the moment), it tells me my account isn't in our company directory and fails.  I'm guessing it done that under the hood and failed, but that still doesn't explain why the Docker host port is open and I can connect to it, so maybe I'm completely wrong there.

**Comment by SteveLasker** [comment]
It looks like you're hitting some gaps in our assumptions about connecting from our Visual Studio Tools to an OnPrem container host. 
Have you looked at the docs here: http://aka.ms/windowscontainers
You can either connect with an unsecured port, or secure it with the certs that you can get from the Visual Studio tools.
I'd also suggest you post followup questions here: https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers
The Windows Team, and myself monitor that forum, and you'll get much better support overall. 
I haven't yet personally walked through the OnPrem connectivity, so it would be good to get larger awareness. 
I do appreciate your continued patience. We are working through a number of angles here we want to crispen up.
Steve

**Comment by npateman** [comment]
That's for all your help with this, I shall continue my quest over there.  Great work from what I've seen demoed so far anyway!  Thanks again.

**Comment by squasta** [comment]
Your error was expected : it's a preview and Docker commit doesn't work now cf. https://msdn.microsoft.com/virtualization/windowscontainers/about/work_in_progress#DockermanagementDockercommandsthatdontworkwithWindowsServerContainers
