### ISSUE TITLE
Program does not contain a static 'Main' method suitable for an entry point docker

### ISSUE THREAD

**Issue by jumapaoA** [microsoft/DockerTools#405]
CSC : error CS5001: Program does not contain a static 'Main' method suitable for an entry point 
I got this error while having ASP.NET Core 7 web app with ReactJS. The main method is in Program.cs and it is using a high-level statement.

**Comment by dbreshears** [comment]
@jumapaoA .  Have you seen this doc -  https://learn.microsoft.com/en-us/visualstudio/containers/container-tools-react?view=vs-2022
