### ISSUE TITLE
The "Configuration" parameter is not supported by the "WaitForWarmupCompletion" task

### ISSUE THREAD

**Issue by Dunge** [microsoft/DockerTools#407]
Visual Studio 17.8.0 Preview 4.0

I had a solution with a bunch of projects having a Dockerfile and referencing `Microsoft.VisualStudio.Azure.Containers.Tools.Targets Version="1.18.1"` successfully.

Yesterday I created a new project and added dockerfile support and it referenced `Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.5"`.

After building, I add this error `MSB4044 The "WaitForWarmupCompletion" task was not given a value for the required parameter "Configuration".`

I updated all my project to reference `Version="1.19.5"` and now I get this error on all my projects:

`MSB4064	The "Configuration" parameter is not supported by the "WaitForWarmupCompletion" task loaded from assembly: Microsoft.VisualStudio.Containers.Tools.Tasks, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from the path: C:\Users\**\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.18.1\tools\Microsoft.VisualStudio.Containers.Tools.Tasks.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.`

**Comment by Dunge** [comment]
Never mind, just restarting Visual Studio fixed it.

**Comment by pyamujala** [comment]
I am facing the similar issue. Even after restarting the PC, it did not go.  Following is the exception,

`Error	MSB4064	The "Configuration" parameter is not supported by the "Clean" task loaded from assembly: Microsoft.VisualStudio.Containers.Tools.Tasks, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a from the path: C:\Users\prade\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.18.1\tools\Microsoft.VisualStudio.Containers.Tools.Tasks.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.	HomePi.WebApi	C:\Users\prade\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.19.5\build\Container.targets	285	`

**Comment by NCarlsonMSFT** [comment]
@pyamujala There was a bug in a few recent versions of the NuGet where the assemblies weren't getting isolated from other versions correctly (fix pending) in the meantime ensure that all the projects in your solution are using the same version of the NuGet to prevent loading incompatible tasks.
