### ISSUE TITLE
Updating to 15.3 broke loading of the docker-compose project in a solution

### ISSUE THREAD

**Issue by josemaia** [Microsoft/DockerTools#41]
I updated to Visual Studio 2017 15.3.2.

Immediately after updating, I loaded a solution I was using.

The solution now displays the following:

"docker-compose (load failed)

Project file is incomplete. Expected imports are missing."

Attempting to re-generate the docker-compose files by deleting and re-creating everything did not work.

I was never prompted to update the docker-compose file to follow the 2.0 structure in this solution. In a different one, I was, and did, Attempting to copy over those changes also did not work.

**Comment by haniamr** [comment]
Since this was addressed over here https://developercommunity.visualstudio.com/content/problem/102634/updating-to-153-broke-loading-of-the-docker-compos.html, I'll be closing this issue.
