### ISSUE TITLE
DOCKER_CONVERT_WINDOWS_PATHS without Docker Desktop

### ISSUE THREAD

**Issue by rs38** [microsoft/DockerTools#413]
is there a way to setup a VS2022 WSL2 dev environment without Docker Desktop?

VS2022  build container just fine but throws "invalid volume specification" when trying to run them due to using Win-Paths instead of /mnt/c/users/whatsoever.

very much related but still true #177 

what would be a nice workaround in 2024?

**Comment by fiveisprime** [comment]
If possible, please test out the changes in 17.10 Preview 1 that recently shipped. See #417 for more information on how to configure this. Let us know in that issue if you run into anything.
