### ISSUE TITLE
Visual Studio DockerTools Does not Recognize YAML Extention as Valid

### ISSUE THREAD

**Issue by mlopeztn** [microsoft/DockerTools#424]
The Docker standard supports both YML and YAML as standard extensions for docker-compose files.  Currently we can use docker-compose.yml and docker-compose.override.yml files and Visual Studio works correctly.  Would it be possible to update the SDK to support docker-compose.yaml and docker-compose.override.yaml as the file names?  Visual Studio current produces an error when using these file extensions that it cannot find the files.

Reference
https://docs.docker.com/compose/compose-file/compose-file-v3/#:~:text=The%20Compose%20file%20is%20a,%2Fdocker%2Dcompose.yml%20.

**Comment by dbreshears** [comment]
Closing this.  We don't have plans to address as there doesn't seem to be enough interest in this to justify the regression risk.

**Comment by ravindUwU** [comment]
~@dbreshears could this decision be revisited? 🤔 `.yaml` (not `.yml`) is the recommended extension for YAML files; and [`compose.yaml` is _explicitly_ the preferred name for compose files](https://github.com/compose-spec/compose-spec/blob/914ec15d1fa498969c0df5c1d672306db3256089/spec.md?plain=1#L170-L172).~

omgomgomg I notice `docker-compose.yaml` works just fine in Visual Studio `18.10.1`! 🥳🎉 It is still generated as `docker-compose.yml` when Container Compose Support is added to a C# project, but it can be renamed to `.yaml`. Thanks!
