### ISSUE TITLE
Standalone TypeScript Angular Project support

### ISSUE THREAD

**Issue by eSPiYa** [microsoft/DockerTools#427]
I'm not really sure if I'm in the correct GitHub repo, but I think there should be Docker support for Standalone TypeScript Angular Project in Visual Studio, specially in debugging.

Maybe I can contribute in providing templates for the Dockerfile and docker-compose with hot-reload support which I was able to assemble through scrounging the internet. It is quite embarrassing because I'm not really that good with Docker, and only know a few basic stuffs about it.

**Comment by fiveisprime** [comment]
Hey there, we don't currently have any plans to support this scenario in the container tools. Supporting front-end frameworks is tricky: the build and start commands are different between frameworks and the container isn't typically suitable for production. That said, we've had a couple of people ask for this so I'll keep an eye on requests and if it becomes a popular request, we can investigate it.
