### ISSUE TITLE
Enable Docker Compose support off a local network instance

### ISSUE THREAD

**Issue by adoboninja** [microsoft/DockerTools#433]
I have a docker instance running off my synology nas. I was wondering if I can configure docker compose in VS2022 to use that instance of docker rather than installing a copy of docker desktop in my laptop.

**Comment by dbreshears** [comment]
No this won't work.  Currently we rely on volume mounts in Visual Studio for your application code, the debugger, and other utilities.   We don't have plans to support a remote instance of docker currently.
