### ISSUE TITLE
Docker compose execution idea

### ISSUE THREAD

**Issue by risogolo** [Microsoft/DockerTools#44]
I cannot find the possibility to change or override the command to execute docker-compose from visual studio. For example, I need to start (using F5) to environment by using this command "docker stack deploy -c docker-compose.yml xxx" and still need to be able to debug it. Is it possible? Can you please incorporate this idea to the next version. I think it uses "docker-compose up -d" and there is no way to override this behavior.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
