### ISSUE TITLE
Visual Studio 2022 Error trying to debug in Docker Compose

### ISSUE THREAD

**Issue by MrCSharp22** [microsoft/DockerTools#445]
Hi,
I have an ASP.NET Core project that needs to listen to 3 different ports with SSL enabled.

The ports are 5000, 5001, and 5002.

For this, I need to use the `ASPNETCORE_URLS` environment variable in the `docker-compose.override.yml` file and set it to `ASPNETCORE_URLS=https://*:5000/;https://*:5001/;https://*:5002/`

When I try to launch/debug the project, I get this error message in Visual Studio:

![image](https://github.com/user-attachments/assets/43e36b3c-896d-4dd1-932e-ebef2d5e5df0)

However, if I remove that variable, everything works except that the project is now only listening to port `8080`.

I haven't been able to find any logs that point to the source of the issue so I am stumped.

I can run the `docker-compose` file through docker directly and everything works fine.

I appreciate any help or clues to solve this issue.

Thank you.

**Comment by NCarlsonMSFT** [comment]
The certificate used by the .dcproj is generated by the dotnet tool dev-certs. What happens if you run `dotnet dev-certs https --trust --check` in a terminal window?

**Comment by MrCSharp22** [comment]
Hi @NCarlsonMSFT  here's the output of that command:

```
❯ dotnet dev-certs https --trust --check
A trusted certificate was found: D52695D48922A35036A7ACB5709F139FF66D44B3 - CN=localhost - Valid from 2024-09-08 01:17:47Z to 2025-09-08 01:17:47Z - IsHttpsDevelopmentCertificate: true - IsExportable: true
```

After, I ran the docker-compose project using Visual Studio with the same error as in the screenshot above.

I also used the `--clean` and then generated a new cert and trusted it using `dotnet dev-certs https --trust` with the same results.

**Comment by NCarlsonMSFT** [comment]
@MrCSharp22 just to double check, can you attempt to start the service project in a container w/o compose (set the service project as your start-up project and then select the Docker launch profile)?

**Comment by MrCSharp22** [comment]
@NCarlsonMSFT apologies for the late replies. I tried the above and got the same result:
![image](https://github.com/user-attachments/assets/aaae80b4-167b-49d8-b2c9-510278651570)

Additionally, this is the log from the Container Tools window in Visual Studio:

```
C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\[User]\AppData\Local\Temp\GetVsDbg.ps1" -Version vs2017u5 -RuntimeID linux-x64 -InstallPath "C:\Users\[User]\vsdbg\vs2017u5"
Info: Using vsdbg version '17.12.10904.2'
Info: Using Runtime ID 'linux-x64'
Info: Latest version of VsDbg is present. Skipping downloads
C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\[User]\AppData\Local\Temp\GetVsDbg.ps1" -Version vs2017u5 -RuntimeID linux-musl-x64 -InstallPath "C:\Users\[User]\vsdbg\vs2017u5\linux-musl-x64"
Info: Using vsdbg version '17.12.10904.2'
Info: Using Runtime ID 'linux-musl-x64'
Info: Latest version of VsDbg is present. Skipping downloads
docker run -dt -v "C:\Users\[User]\vsdbg\vs2017u5:/remote_debugger:rw" -v "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro" -v "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro" -e "ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true" -e "ASPNETCORE_ENVIRONMENT=Development" -P --name [ORG].Web --entrypoint dotnet [ORG]web --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait 
aecbd100067190f23829f1dffb8da62ab1670d226f6d50fac117fee4c54de239
Could not find the global property 'UserSecretsId' in MSBuild project 'X:\Projects\Orchard\Carlisle Homes\carlisle-homes-multisite\src\[ORG].Web\[ORG].Web.csproj'. Ensure this property is set in the project or use the '--id' command line option.
```

Visual Studio also generated this docker launch profile (I only added the environment name to the list of variables):

```
    "Container (Dockerfile)": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}",
      "environmentVariables": {
        "ASPNETCORE_HTTPS_PORTS": "8081",
        "ASPNETCORE_HTTP_PORTS": "8080",
        "ASPNETCORE_ENVIRONMENT": "Local"
      },
      "publishAllPorts": true,
      "useSSL": true
    }
```

**Comment by NCarlsonMSFT** [comment]
`Could not find the global property 'UserSecretsId' in MSBuild project 'X:\Projects\Orchard\Carlisle Homes\carlisle-homes-multisite\src\[ORG].Web\[ORG].Web.csproj'. Ensure this property is set in the project or use the '--id' command line option.`

Your project is missing the property `UserSecretsId` which can be set to any unique string (usually a random guid) for instance. Our tools should have added the property when you added docker support, but if you add it now it should start working.

**Comment by MrCSharp22** [comment]
Thanks @NCarlsonMSFT. That works!

I don't fully understand the relationship between the missing `UserSecretsId` and how the error wouldn't appear when I don't specify ports in the environment variable. I'd be interested in that actually.

I appreciate your help with this one. Thank you.

**Comment by NCarlsonMSFT** [comment]
`ASPNETCORE_URLS` containing an https URL necessitates configuring a certificate. The way our tools set-up the certificate for debugging uses the User Secrets feature to pass configuration into the container.
