### ISSUE TITLE
If VS is closed unexpectedly, I can't start Docker compose project due to a docker network error

### ISSUE THREAD

**Issue by kamranayub** [microsoft/DockerTools#450]
**Description**

When trying to run my Docker Compose project without debugging or with debugging, I occasionally receive a build error stating that a docker network "dockercompose<random chars>" label is incorrect:

> network dockercompose9027932406211217250_default was found but has incorrect label com.docker.compose.network set to ""

**Steps to Reproduce**

It's hard to reproduce. It usually happens to me after a Windows Update is automatically applied and my PC restarts. For example, I tried to reproduce it by force-ending the process tree for `devenv.exe` but it doesn't reproduce the problem.

Somehow, it gets into a state where the Docker Compose network label is updated/changed to be empty. (?)

```
Getting Docker containers ready...
docker-compose  -f "app\docker-compose.yml" -f "app\docker-compose.override.yml" -f "app\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose9027932406211217250 --ansi never build --build-arg BUILD_CONFIGURATION=Debug
```

This is the command that fails.

**Workaround**

To fix the issue, I remove the `dockercompose*` network manually and restart Visual Studio:

```sh
docker network ls
# look for dockercompose<chars>
docker network rm <id>
# Restart VS
```

**Proposed Solution**

I am not sure what the root cause is. But if the tools encounter this error, it seems reasonable to remove the `dockercompose` network and recreate it automatically.

**Comment by fiveisprime** [comment]
Hey there,

Unfortunately, this is something that we depend on Docker to manage, and it's out of scope for our tooling to know when to cleanup. I'd recommend opening an issue with the Docker folks on this one.

**Comment by kamranayub** [comment]
@fiveisprime interesting, I only run into it with VS 2022, so I guess I am not sure what the root cause is. You're saying that Docker Desktop may be the cause, somehow blowing away Docker Compose configuration 🤔 Could be!

I ran into it again today, here is the full error log in Container Tools:

```
docker ps --filter "status=running" --filter "label=com.docker.compose.service" --format {{.ID}};{{.Names}}
docker compose  -f "c:\app\docker-compose.yml" -f "c:\app\docker-compose.override.yml" -f "c:\app\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose9027932406211217250 --ansi never up -d --no-build
time="2024-12-21T13:52:11-06:00" level=warning msg="a network with name dockercompose9027932406211217250_default exists but was not created by compose.\nSet `external: true` to use an existing network"
network dockercompose9027932406211217250_default was found but has incorrect label com.docker.compose.network set to "" (expected: "default")
A non-critical error occurred while getting containers ready.  Your project will continue to function normally.  The error was: network dockercompose9027932406211217250_default was found but has incorrect label com.docker.compose.network set to "" (expected: "default")
If the error persists, try restarting Docker Desktop.
```

I just updated to Docker Desktop 4.37.1 so we'll see if that helps.

**Comment by kamranayub** [comment]
Alright, I was able to workaround it by explicitly specifying this network in `docker-compose.yml`

```yml
networks:
  default:
    name: dockercompose9027932406211217250_default
    external: true
```

It seems like this ensures it'll just use the network as long as it exists after initial creation 🤷‍♂
