### ISSUE TITLE
Going Open Source

### ISSUE THREAD

**Issue by tebeco** [Microsoft/DockerTools#48]
i can’t attach my debugger because sharing drive C is forbidden by GPO

 my source code is on D:
Vs2017 is on c:
docker can only install on c: (even thought i tricked it to work for a short period on D:)

should i share C ? D ? both

open sourcing this code would be a HUGE bonus when dealing with issue like this
What are the blocker so you can OpenSource DockerTools for vs2017 ?
can we help you so remove these blocker ?

**Comment by tebeco** [comment]
Also the last bug found on the power shell trying to download stuff for the debugger ...
i had to do reverse engineering and decompile your code to find an actual bug
that seems a bit overkill right ?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!

**Comment by bwateratmsft** [comment]
Changing close to duplicate of #39
