### ISSUE TITLE
Publish guidance on how to work with Docker for Windows on build agents.

### ISSUE THREAD

**Issue by stebet** [Microsoft/DockerTools#49]
I currently have a in-house hosted VSTS build agent and getting it to build projects that utilize the VS 2017 Docker tools has been a royal pain in the behind.

Some documentation and guidance on how to set-up a build agent that can build Windows Containers is sorely needed.

**Comment by 9Rune5** [comment]
Your comment indicates that you actually managed to get it rolling? I'm stuck with a somewhat cryptic "error MSB4018: The "ResolveTargetOS" task failed unexpectedly." message.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!

**Comment by EgoPingvina** [comment]
It's still a relevant problem!
