### ISSUE TITLE
Mvc Web App template in docker generates incorrect URL

### ISSUE THREAD

**Issue by Eilon** [Microsoft/DockerTools#50]
_From @smitpatel on October 6, 2017 22:38_

Steps:
1. Create new ASP.NET Core Web Application
2. Choose Web Application template for 2.0
3. Add individual accounts auth
4. Enable Docker support for windows.

Restore packages/build solution etc.
Press F5
Expected output:
Website from template is opened in browser.
Actual output:
Browser fails to load website. The website URL in browser is http://172.21.203.31/https://localhost:44341/

_Copied from original issue: aspnet/Mvc#6923_

**Comment by Eilon** [comment]
@natemcmaster - any ideas on this? Presumably a tooling issue? Do you know where those issues go?

**Comment by Eilon** [comment]
_From @natemcmaster on October 10, 2017 15:9_

Yes, I'm supposing this is a VS issue. You can use the Report an Issue feature in VS or try your luck here: https://github.com/microsoft/dockertools

**Comment by dbreshears** [comment]
@Eilon, able to repro in our latest tooling.  We will investigate a fix.

**Comment by dbreshears** [comment]
@Eilon , @smitpatel,  we have a fix ready, slated to make it in 15.5 P2

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
