### ISSUE TITLE
DockerServiceUrl

### ISSUE THREAD

**Issue by grahamehorner** [Microsoft/DockerTools#53]
When creating a #aspnetcore 2.0 project that has #identity enabled the DockerServiceUrl in the .dcproj file in not valid and is a string that is combined URIs in the form of http://{ip}/https:localhost:{port}/ see https://github.com/grahamehorner/AspNetCoreTemplateDockerIssues/tree/master/WebApplicationLinuxWithAuth as example of a repo

**Comment by yanchenw** [comment]
Hi grahamehorner, this issue has already been fixed in latest Visual Studio 2017 preview release.
You can download the latest bits here: https://www.visualstudio.com/vs/preview/

Please let us know if you have further question.

Thanks
Yanchen
