### ISSUE TITLE
Add->Docker Support does not account for custom output paths

### ISSUE THREAD

**Issue by twsouthwick** [microsoft/DockerTools#54]
I like to set up my projects so the obj and bin directories are all together instead of within the src files. I do this by adding a `Directory.Build.props` file to the top level directory next to the solution file with lines similar to this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

  <PropertyGroup>
    <OutputFullPath>$(MSBuildThisFileDirectory)</OutputFullPath>
    <OutputDrop Condition=" '$(OutputDrop)' == '' ">$(OutputFullPath)bin\$(Configuration)\</OutputDrop>
    <OutputPath>$(OutputDrop)\$(MSBuildProjectName)\</OutputPath>
    <BaseIntermediateOutputPath>$(OutputFullPath)obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>

</Project>
```

However, if a project has this and tries to add Docker support, then the resulting Dockerfile and docker-compose.yml do not produce a viable container.

## Steps
1. Create a new ASP.NET Core Web API project (do not select Docker support)
2. Add a `Directory.Build.props` as described above
3. Close VS and clear out everything (some of the paths may be cached - if under git use `git clean -xfd`)
4. Open VS
5. Add Docker Support to project
6. Debug with F5

### Expected
Container launches, debugger attaches, and site works

### Observed
Container launches, but debugger cannot attach. If I go into the container, I don't see a bin directory. The output of F5 looks like this:

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[12] dotnet' has exited with code 145 (0x91).
The program '' has exited with code 145 (0x91).
```

**Comment by mjrousos** [comment]
Any thoughts on this? It seems like volume mounting the output directory (instead of the project root) would solve the immediate problem here. I don't know enough about the Docker tools to know if not setting the working directory to the project root would cause other problems or not, though.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!

**Comment by Richard004** [comment]
I have bumped into this problem today again. My application had the separated out and bin dir for several solution projects. 
I have added docker-compose via "docker support" and experienced described behaviour. 
When I deleted my Directory.Build.props then it started to work. But now my obj and bin are scattered around my folder structure, which complicates other my workflows.

I do not insist on "fixing" it, but it would be nice to read here about a workaround how to fix the generated files manually to achieve both src/obj separation and also docker-compose functionality.

I apologise if there is some obvious solution. I am new to docker and docker-compose and I still struggle with how to nicely setup my environment. 

Thanks for any possible suggestion.

**Comment by bwateratmsft** [comment]
Hey @Richard004, unfortunately there's no workaround available right now, but I'll reopen this issue for future consideration.

**Comment by Richard004** [comment]
Thank you Brandon. I honestly do not have a strong opinion about this. I was used to having "readonly" src, but with the docker workflows I do not know what is "normal level of pain" people need to go through, so I propose that if nobody joins in next 3 months, let's close it again and I will adapt it somehow.

Is there some opinionated and documented setup for docker-compose in similar way like Scott Allen did here (!!!! mega useful presentation Scott !!!!) ?
https://www.youtube.com/watch?v=WMdBoeQtxUY

It can be for kubernetes as well, but we support equally the Azure deployment as well as really local installation on PCs of our colleagues.

**Comment by bwateratmsft** [comment]
@Richard004 Here's a video about our single-Dockerfile experience, and I'm sure you can find many things on YouTube or Channel 9: [https://www.youtube.com/watch?v=Tlswgxl_Xyk](https://www.youtube.com/watch?v=Tlswgxl_Xyk)

**Comment by rustamm** [comment]
We've got this problem too, we use Directory.Build.props in all our projects to change output paths to a folder other than src. A workaround would be great.

**Comment by bwateratmsft** [comment]
@rustamm Yes, this is the right place for VS2019 as well. I'm going to update readme page to make that clear.

**Comment by pratiksanglikar** [comment]
@twsouthwick, this issue has been partially fixed in the latest release of Visual Studio 2019 16.5
You can now customize the `<OutputPath>` using Directory.Build.props.
Unfortunately,  `<BaseIntermediateOutputPath>` is not currently supported due to the way tooling is structured right now, and it will take significant engineering efforts to add support for it.
