### ISSUE TITLE
docker-compose (dcproj) projects doesn't support TFS integration

### ISSUE THREAD

**Issue by lechuckcaptain** [Microsoft/DockerTools#55]
It's not possible to checkout files into a docker-compose (dcproj) projects. The functionality is simply not available to the user (see screenshot).

![image](https://user-images.githubusercontent.com/341895/32722918-d75f160e-c86b-11e7-978d-58a18d1c13c7.png)

The developer needs to manually check-out the required files from Source Control Explorer

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
