### ISSUE TITLE
How can i debug a plugin?

### ISSUE THREAD

**Issue by CAH-FlyChen** [Microsoft/DockerTools#57]
I have a app docker named docker-main.Then i have a plugin solution which contans three project project-a project-b porject-c. project-b and project-c depands on project-a
when in debug mode, the plugin solution can not run.because i wirte copy file command which not work in debug in dockerfile.
what should i do?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
