### ISSUE TITLE
Support for Linux Docker Host

### ISSUE THREAD

**Issue by tibmeister** [Microsoft/DockerTools#59]
I would love to see the removal of Docker on Windows in order to use this.  I do ASP.NET Core Web API on a Linux host using Docker, at this time it's all manual build and run, and I can't debug on that platform easily.

**Comment by SleepyDeb** [comment]
Same ISSUE, there is no way to docker-compose using a remote docker instance

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
