### ISSUE TITLE
Visual Studio 2015 Publish to CustomDockerHost "Custom" was not found Error

### ISSUE THREAD

**Issue by dqywill** [Microsoft/DockerTools#6]
Hi All, I am trying to publish my asp.net 5 web app to my docker host, but it's not working. The error message like this:

Publishing with publish method [Custom]
 C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.DNX.Publishing.targets(386,5): Error : An error occurred during publish.
 AspnetPublishHandler with name "Custom" was not found

I use vs 2015 with update 1 and Tools for Docker 0.9.2.
I have repair the tools and vs, but it still not work.
Wish someone can help me, thanks.

**Comment by carolynvs** [comment]
I received the same error with VS 2015 Update 1 and Tools for Docker 0.9.2. I was able to get it working  finally by first repairing the ASP.NET 5 RC1 installation, deleting the PublishingProfile directory in the project and then running publish again.

**Comment by dqywill** [comment]
@carolynvs It's work, Thinks a lot.
