### ISSUE TITLE
Visual Studio cannot run ASP.NET Core app in docker

### ISSUE THREAD

**Issue by McMlok** [microsoft/DockerTools#60]
Hello,

I create new ASP.NET Core app from template and try tu run this app inside docker. But when I hit F5 I get error

1>docker ps --filter "status=running" --filter "name=dockercompose5249654611173997711_dockertest_" --format {{.ID}} -n 1
1>DockerTest -> D:\Projects\DockerTest\DockerTest\bin\Debug\netcoreapp2.0\DockerTest.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : An error occurred while sending the request.
1>Done building project "docker-compose.dcproj" -- FAILED.

Is there way to enable debug mode to get more info? Or how to handle this error?

I'm behind corporate proxy with NTLM auth. I have CNTLM proxy and this proxy is setup in docker for windows. We have private docker image repository and I change all reference to ms images in dockerfile to images from our repository (FROM ourreposiotory:port/microsoft/aspnetcore:2.0 AS base). Our repo work as proxy for images on docker.io.

When I run docker-compose build, image is successfully created and can be run via docker run imagename

What I have wrong?

Thanks

OS: Windows 10 1703
VisualStudio: 15.5.1
Docker: 17.09.0-ce
Docker-Compose: 1.16.1
Docker-Machine: 0.12.2

**Comment by CAH-FlyChen** [comment]
i have the similar situation   https://github.com/Microsoft/DockerTools/issues/63

**Comment by hgy59** [comment]
same for me, but I have to run/debug the app on a machine in an isolated network environment (no internet access)

> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : An error occurred while sending the request.

How can I find out what is requested?
Is there another docker image or nuget package to download?
working with private docker registry and local nuget repository.

I already downloaded vsdbg to and have onecoremsvscore in %USERPROFILE%.
Docker images microsoft/aspnetcore-build and microsoft/aspnetcore are available (versions 1.0-2.0/2.0 and 2.0.5-2.1.4/2.0.5)

What is the command behind building the docker-compose.dcproj?

OS: Windows 10 (10.0.14393)
Visual Studio: 15.5.4
Microsoft Visual Studio Tools for Containers: 1.1
Microsoft MI-Based Debugger: 1-0
Visual Studio Code Debug Adapter Host Package: 1.0
Docker: 17.09.1-ce
Docker-Compose: 1.17.1, build 6d101fb0
Docher-Machine: 0.13.0, build 9ba6da9

**Comment by McMlok** [comment]
Today I update Docker For Windows to version 17.12.0-ce and now debuging works. I use Visual Studio 2017.6 preview 2

Maybe issue was in Firewall setings now I see two new rules for docker

**Comment by medvedevua** [comment]
My problem was with "limited" network - through mobile phone, as soon as switched into unlimited WiFi - magic happened and all docker builds started

**Comment by los93sol** [comment]
This issue is intermittent for me and extremely frustrating as it is killing my productivity.  It happens randomly, can be debugging just fine, stop, try to start again and boom, "An error occurred while sending the request".  Interestingly what I have noticed is that when it works I typically see vsdbg is latest, skipping download, but when it fails I never see any message about vsdbg because it fails too soon.  If someone can point me to some log or something that would help troubleshoot my own issue that would be great.

**Comment by los93sol** [comment]
Bueller?

**Comment by los93sol** [comment]
Mic check.....1......2.....

**Comment by bwateratmsft** [comment]
@los93sol , you are on the right track with vsdbg. Part of the Docker compose project build task is to try to get the latest copy of vsdbg from `https://aka.ms/getvsdbgps1`, if the files in your user profile are more than a day old. Likely, there is some issue preventing your machine from connecting to aka.ms, either consistently or intermittently (could be firewall, internet connectivity, security settings, proxy, etc.). You may be able to get more information from a detailed msbuild log, using the command:
`msbuild /v:d YourSolutionFile.sln > msbuild.log`. Search that log file for "vsdbg" and it might have some more detailed error information. Otherwise, you can try opening that same URL in your browser.

**Comment by los93sol** [comment]
There is definitely something intermittently blocking it, but I don’t understand why.  It happened again today and I actually went to the aka.ms site in my browser without issue, VS continued to have issues though.  I finally downloaded the file and placed it in my temp directory and it took off after that.  I am behind a corporate proxy and I’m assuming that has something to do with it, but if VS is pulling my proxy settings from Windows correctly I should have the same result as in the browser.  In either case that error should be updated to give the user a clue as to what actually failed, request to where?  What was the error?  Etc. the way it is now you just look at it like well cool, something failed and I don’t have enough info to troubleshoot without digging around for an hour to figure out what log, if any, has the details I need to resolve the issue.

**Comment by gregnightingale** [comment]
This also plagues me.  I am using VS on a Macbook pro. and I am also running CNTLM proxy which is the only way to get reliable connection to the internet via our horrible BlueCoat proxy restricted network.  I get so frustrated with this issue, that I have to switch to a "guest" wifi network to get the docker-compose project to run.

**Comment by los93sol** [comment]
Are we just pretending like this isn't a real issue and going to continue ignoring it for another two years?  This issue is rampant....just search google for it and you find tons of people with the same issue.  Somebody please acknowledge this and fix it

**Comment by dbreshears** [comment]
Thanks for  bringing this to our attention.    We are bumping the priority and working on a fix.

**Comment by dbreshears** [comment]
@los93sol. Can you please confirm whether this is fixed 15.9.10 servicing update when you have a moment

**Comment by McMlok** [comment]
I update my VS2017 and try to debug solution for several times and everything works.

I also update VS2019 to latest preview and same old project works.

I try new template from VS2019 but first I need to arange new proxy for Microsoft container registry in our Nexus server.
