### ISSUE TITLE
I can't Add Docker Support in Asp.Net Core 2.0 Targeting Full .Net Framework 4.7

### ISSUE THREAD

**Issue by cluka** [Microsoft/DockerTools#64]
If I create new Asp.Net Core 2.0 WebApi project that targets .Net Framework 4.7 I can't Add Docker Support to it. The option in context menu of the project odes not show Add->Docker Support.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!

**Comment by chintan3100** [comment]
Do we any update on above issue

**Comment by bwateratmsft** [comment]
Hey @chintan3100, unfortunately it is not supported to use Docker tools for ASP.NET Core targeting .NET Framework.  You can see more [here](https://github.com/Microsoft/DockerTools/issues/34#issuecomment-481731741).
