### ISSUE TITLE
Question - why build on docker, and not host-only on docker

### ISSUE THREAD

**Issue by alexzaytsev-newsroomly** [Microsoft/DockerTools#65]
With the latest versions of docker tools, the dockerfile contains a whole bunch of containers, and i really struggle to understand why.
We copy all projects (and they are hardcoded into the dockerfile) to a container, then build, then copy the output to another container and then host.

Why is that? what is the reasoning the team had behind it?

My workflow is fairly simple:
1. Develop on Windows. Debug on Windows. Never run inside docker on Windows
2. CI on Linux. Always unit test and compile on build agent.
3. For CD, build a container and upload to my private repository.

So i have my dotnet sdk and docker on my ci agent.
I run `dotnet build` and `docker build`. That is it. 

Why can't the same workflow be facilitated by default on Windows?

Also, why does the tooling start building docker as soon as i click `add docker integration`. If the internet connection is not great that's a few hundred MBs down the drain when all i wanted to do was add `.dcproj` (or actually the `.yml` file) to push to my CI?

**Comment by dbreshears** [comment]
We switched to a multi-stage build Dockerfile in the latest tools.     Even though this is the default scaffolded in Dockerfile, you can switch back to the old format if you choose and your scenario should continue to work.  FWIW, nearly all of this new Dockerfile format is only relevant when choosing the Release build configuration as we do things much differently in Debug configuration mentioned below.    For the benefits of multi-stage build, please see -> https://docs.docker.com/engine/userguide/eng-image/multistage-build/ . 

Our tooling does optimize for the  the F5 debugging experience, so for performance reasons we  warm up the debug (F5) environment by doing a couple of things  you mentioned,  first is to pull down the required Docker images in the background on solution load and the second is to automatically start a container in the background so we don't need to create and tear down on every F5 which is a bit of  a perf hit.   Thus, the  application is  built on the host and volume mapped into the container, along with the debugger.     Both of these performance related  options can be disabled in Tools->Options->Container Tools->Settings.     Hope this helps.

**Comment by alexzaytsev-newsroomly** [comment]
@dbreshears thank you for the info 👍 
I guess the main use case for VS integration (Docker tools) is more to diagnose issues when the app doesn't work specifically in docker.

For most cases, this tooling is not necessary (it is faster to debug the app outside of docker).

**Comment by dbreshears** [comment]
Sure.  To debug your application code or logic it may make sense to simply use IISExpress or run outside the container for optimal perf although we are making performance improvements here and there to get as close as possible.  The tooling certainly will be beneficial when composing multiple containers and attempting to get more production realism when debugging,  hence why we still volume mount the debugger in Release configuration , but leverage the multi-stage build as well.
