### ISSUE TITLE
Consider Multi-arch container support

### ISSUE THREAD

**Issue by AceHack** [microsoft/DockerTools#67]
Please add multi-arch support for docker tools for visual studio allowing targeting of multiple environments, basically all those .net core is based on like Linux, windows, arm, etc...

Also just to clarify, I want to be able to create multi-arch containers using one project, kind of like .NET has TargetFrameworks for .NET class libraries allowing to target multiple versions of .NET.

https://docs.microsoft.com/en-us/dotnet/standard/frameworks
https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

**Comment by AceHack** [comment]
More info
https://blog.docker.com/2017/11/multi-arch-all-the-things/

**Comment by yanchenw** [comment]
@AceHack Using platform specific image names is a design choice we made to make sure users know exactly what platform their images will be build against.

But if you want to take advantage of multi-arch image tags, you can easily change the base image name inside the generated Dockerfile from platform specific tags to multi-arch tags.

e.g. you can change the following tag in Dockerfile in a dotnet core web application from:
```
FROM microsoft/aspnetcore:2.0-nanoserver-1709 AS base
```
to
```
FROM microsoft/aspnetcore:2.0 AS base
```

**Comment by AceHack** [comment]
@yanchenw Your response is missing the point of my request.  What I'm asking is to create one docker file but produce multiple arch docker images from it, with one build command in VS.  I understand that I can target any specific platform image, I want to produce multiple platform/arch images in one build, just like you can with the TargetFrameworks.

**Comment by AceHack** [comment]
@bwateratmsft why was this closed?

**Comment by bwateratmsft** [comment]
@AceHack we closed some issues that hadn't been updated in some time. Since this is still relevant I'm happy to reopen it.

**Comment by fiveisprime** [comment]
@AceHack I'm sorry, but this isn't something that has much demand and we won't be picking it up as a feature. That said, you can add this as a suggestion in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/VisualStudio) where we can track votes to gauge interest.
