### ISSUE TITLE
dnu restore fails when projects references another project from solution

### ISSUE THREAD

**Issue by NickAb** [Microsoft/DockerTools#7]
After adding Docker support to a project and running it, Docker build step failed on `dnu restore` because it could not find dependencies, specifically, another project in same solution that is referenced by current project. This is due to fact that only current project is copied to Docker container.

Manually chaining Dockerfile templates to copy whole solution or both projects fixes the problem.

Will there be a support in DockerTools out of the box for projects that reference another project in solution, or should every dependency be packed and pushed to nuget feed?

**Comment by SteveLasker** [comment]
This has become outdated as we've moved to RC2 and dotnet APIs, including restore.
