### ISSUE TITLE
Please support the new LCOW (Linux Containers on Windows)

### ISSUE THREAD

**Issue by AceHack** [microsoft/DockerTools#74]
This only support the legacy Linux containers not the new style

**Comment by AceHack** [comment]
Any update on this?  Just tried with the new 2.1 version and still didn't work.  Thanks.

**Comment by OneCyrus** [comment]
too bad there's no progress on LCOW support. any feedback from the product group would be greatly appreciated.

**Comment by haniamr** [comment]
There's an open work item to do the changes necessary to support LCOW, I'll update this issue accordingly as soon as it's completed.

**Comment by haniamr** [comment]
LCOW is now supported as of Visual Studio 16.0 and above.
