### ISSUE TITLE
Subsequent docker-compose run from VS fails in case of named containers

### ISSUE THREAD

**Issue by evil-shrike** [Microsoft/DockerTools#76]
I have a docker-compose with several services where I specied names for containers.

Like:
```
version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - .\Server\.docker\DB\etc:/etc/postgresql
      - .\Server\.docker\DB\log:/var/log/postgresql
      - .\Server\.docker\DB\lib:/var/lib/postgresql
    container_name: db_pg

  server:
    build:
      context: Server/.
    ports:
      - "5000:80"
    environment:
      - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    container_name: web
    hostname: Docker
    depends_on: 
      - postgres
```
If I run `docker-compose up` it works fine. I can start, stop and then start again. 
But if I start debugging from VS by pressing F5 then docker-compose fails with error:

```
Building server
Creating db_pg ... 
[2A[2K
Creating db_pg ... [31merror[0m
[2B
ERROR: for db_pg  Cannot create container for service postgres: Conflict. The container name "/db_pg" is already in use by container "66c8e9c9b1ec4cf85f3be5f25fe314dff3c67d275d5d4682365e29c90061107f". You have to remove (or rename) that container to be able to reuse that name.
ERROR: for postgres  Cannot create container for service postgres: Conflict. The container name "/db_pg" is already in use by container "66c8e9c9b1ec4cf85f3be5f25fe314dff3c67d275d5d4682365e29c90061107f". You have to remove (or rename) that container to be able to reuse that name.
Encountered errors while bringing up the project..
```
Well I understand in general what causes the error. It's the same case if I run `docker run --name <name>` for a named container without removing the previous and instead of just starting it.

Here's the output:
```
1>docker-compose  -f "D:\Work\...\docker-compose.yml" -f "D:\Work\...\docker-compose.override.yml" -f "D:\Work\...\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose14867793435139719692 up -d --build --force-recreate --remove-orphans
```

But it's terrible dev experience. 
I believe VS Docker Tools should support named containers. If you really need to recreate them then add logic for removing then, otherwise just start them. Why the flag `--force-recreate` is needed?

**Comment by arielmoraes** [comment]
I'm facing the same issue here, I have a container created outside visual studio and I just need it to start when I debug my application as I have persisted data inside the container's volume.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please reply with any additional context for our consideration, we are happy to take a look!

**Comment by IUnknownPtr** [comment]
The bug is still actual. If I use container_name in service definition VS fails to start debugging because service with the same name already exists. With container_name removed I get another error that some ports are already in use.
