### ISSUE TITLE
The command '/bin/sh -c apt-get install -y libgdiplus' returned a non-zero code: 100

### ISSUE THREAD

**Issue by sokol74** [Microsoft/DockerTools#78]
Hello guys.
I have some difficult issues, when attempt to build project with docker
1>Building rpd.loader.service
1>Step 1/9 : FROM microsoft/aspnetcore:2.0
1> ---> 21cdbb87454f
1>Step 2/9 : ARG source
1> ---> Running in 3e33c437740e
1>Removing intermediate container 3e33c437740e
1> ---> d4668730dcd3
1>Step 3/9 : RUN apt-get update
1> ---> Running in 75faae6bd09c
1>Err:1 http://deb.debian.org/debian stretch InRelease
1>  Temporary failure resolving 'deb.debian.org'
1>Err:2 http://security.debian.org stretch/updates InRelease
1>  Temporary failure resolving 'security.debian.org'
1>Err:3 http://deb.debian.org/debian stretch-updates InRelease
1>  Temporary failure resolving 'deb.debian.org'
1>Reading package lists...
1>[91mW: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
1>W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
1>W: Failed to fetch http://security.debian.org/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
1>W: Some index files failed to download. They have been ignored, or old ones used instead.
1>[0mRemoving intermediate container 75faae6bd09c
1> ---> a715f10224b2
1>Step 4/9 : RUN apt-get install -y libgdiplus
1> ---> Running in 607e2336ebc2
1>Reading package lists...
1>Building dependency tree...
1>Reading state information...
1>[91mE[0m[91m: Unable to locate package libgdiplus[0m[91m
1>Service 'rpd.loader.service' failed to build: The command '/bin/sh -c apt-get install -y libgdiplus' returned a non-zero code: 100
1>[0m
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(111,5): error : Building rpd.loader.service
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(111,5): error : Service 'rpd.loader.service' failed to build: The command '/bin/sh -c apt-get install -y libgdiplus' returned a non-zero code: 100.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(111,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.Docker.targets(111,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
1>Done building project "docker-compose.dcproj" -- FAILED.

I have no idea how can i solve this.
Could somebody help me plzzzz

**Comment by sokol74** [comment]
Somebody plz help me.
I have no idea how to resolve this issue

**Comment by lnimong** [comment]
Hi,
I'm running into the same problem
did you solve it ?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!

**Comment by porscheme** [comment]
'RUN apt-get update' is ignored....

#My docker file code snippet
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
FROM microsoft/dotnet:3.0-sdk AS runtime

RUN apt-get update

**Comment by bwateratmsft** [comment]
@porscheme When running in Debug mode, only the "base" stage of the Dockerfile is run.

**Comment by changhuixu** [comment]
same here. Anyone has a solution?
Thanks.
