### ISSUE TITLE
Adding service with alpine based image results in failed build 

### ISSUE THREAD

**Issue by SvenPetroll** [Microsoft/DockerTools#79]
I have added a service that is based on an `alpine` image (nginx hosted angular frontend) to my `docker-compose.yaml` file. This `alpine` image doesn't include `/bin/bash`.

When I start my `docker-compose` project, it looks for the `dotnet` process inside this container and fails on build:

    1>docker ps --filter "status=running" --filter "name=services.dev.frontend" --format {{.ID}} -n 1
    1>54d7e6e3cdc6
    1>docker exec -i 54d7e6e3cdc6 /bin/bash -c "if PID=$(pidof -x dotnet); then kill $PID; fi"
    1>OCI runtime exec failed: exec failed: container_linux.go:296: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
    1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error : .
    1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error : 
    1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(314,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
    1>Done building project "docker-compose.dcproj" -- FAILED.

**Comment by yanchenw** [comment]
@SvenPetroll  Can you share a sample docker-compose file with us to reproduce this issue?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
