### ISSUE TITLE
Dockerignore file copied to .dcproj's folder instead of added from its location

### ISSUE THREAD

**Issue by alexvy86** [microsoft/DockerTools#81]
I noticed that when I try to add a `.dockerignore` file to the `docker-compose` project in VS, if the `.dockerignore` is in different folder than `docker-compose.dcproj`, the file gets copied to the project location, and that file is the one that gets added to the project. Is this expected? I end up with two files that need to be synced manually, and more importantly, my `docker-compose.dcproj` file is not located in the folder I want to use as context for `docker build` (where `.dockerignore` needs to be).

I want to end up with this (simplified) project structure (where `repo_root`, not `src`, is the context for `docker build`, so my Dockerfile can copy files from `repo_root` into the container image):
```
repo_root/
  - .dockerignore
  - <other files that need to go in the built docker image>
  - src/
    - MySolution.sln
    - docker-compose.dcproj 
    - docker-compose.yml (and other yml files)
    - MyProject/
      - Dockerfile
```

For now I just removed `.dockerignore` from the `dcproj`, since I believe the debugging experience when running projects inside containers doesn't have any need for it...? The containers used for debugging are completely empty, if I recall correctly, and just get the project source code mounted, no `docker build` happens, correct? If that's the case, does the `dcproj` need to reference the `.dockerignore` file at all?

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!

**Comment by alexvy86** [comment]
@bwateratmsft what additional information do you need? I think the issue is pretty clear in the original post.

**Comment by NCarlsonMSFT** [comment]
Closing older issues. You were correct the .dcproj does not need a reference to the .dockerignore file. Also if it comes up again you can add the item as a link instead of just add and then VS with reference the file where it is instead of copying it to the project.
