### ISSUE TITLE
Cannot use .env file

### ISSUE THREAD

**Issue by AceHack** [microsoft/DockerTools#82]
I get the following error when trying to use an .env file in the same directory as my docker-compose.yml file.

The DOCKER_PRIMARY_VERSION variable is not set. Defaulting to a blank string.
The ASSEMBLY_VERSION variable is not set. Defaulting to a blank string.
The FILE_VERSION variable is not set. Defaulting to a blank string.
The BuildConfiguration variable is not set. Defaulting to a blank string.
The NUGET_CONFIG variable is not set. Defaulting to a blank string.

These are all set in the .env file.

**Comment by WolfspiritM** [comment]
The .env file only works for me when loading the solution via the .sln file from explorer.
If loading the solution via visual studio itself it seems like VS doesn't properly set the working directory for docker-compose preventing the .env file from working...

I hope that gets fixed...

**Comment by dazinator** [comment]
Same problem. Not sure if it matters but I am logged into windows with a standard (non admin) user account, and then running VS as Administrator.

**Comment by dbreshears** [comment]
.env support should be the latest version of Visual Studio 2022
