### ISSUE TITLE
Config transformation for DockerTools

### ISSUE THREAD

**Issue by kalexii** [Microsoft/DockerTools#86]
Hello, guys!

Here's a feature request (or an explanation request if that kind of thing is already possible, though I wasn't able to find any docs mentioning that):
It would be really great if docker-compose build would differentiate between build configuration, so that different settings would take effect (e.g. environment variables like ASPNETCORE_ENVIRONMENT specified in docker-compose.override.yml).

Or, config transformation for .env files?

Thank you.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!
