### ISSUE TITLE
network nat is ambigous

### ISSUE THREAD

**Issue by nphmuller** [microsoft/DockerTools#89]
When I create a new ASP.NET Web Application in VS 15.6.4 with Docker Support enabled, I immediately get the following build error:
```
1>WebApplication3 -> c:\users\mulle\source\repos\WebApplication3\WebApplication3\bin\WebApplication3.dll
1>docker-compose  -f "c:\users\mulle\source\repos\WebApplication3\docker-compose.yml" -f "c:\users\mulle\source\repos\WebApplication3\docker-compose.override.yml" -f "c:\users\mulle\source\repos\WebApplication3\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose8443036482498000778 --no-ansi up -d --build --force-recreate --remove-orphans
1>2 matches found based on name: network nat is ambiguous
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : 2 matches found based on name: network nat is ambiguous.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(363,5): error : For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting
1>Done building project "docker-compose.dcproj" -- FAILED.
```

`docker network ls` produces the following output:
```
NETWORK ID          NAME                DRIVER              SCOPE
5c2f84200f27        nat                 nat                 local
90484bbaf01b        nat                 nat                 local
33131c23180b        none                null                local 
```

Both nat network cannot be removed because:
```
> docker network rm 5c2f84200f27
Error response from daemon: nat is a pre-defined network and cannot be removed 
```

According to https://github.com/moby/moby/issues/20648#issuecomment-188215208 duplicate network names in Docker are by design. So this might be a bug.

**Comment by nphmuller** [comment]
Docker factory reset can be used as a workaround.
Factory reset still creates 2 nat driver networks for me, but with a unique name:
```
> docker network ls
NETWORK ID          NAME                                                               DRIVER              SCOPE
c16d631fff32        3a58d72283c3b3da9debb8bb753d0327b1e15437dcb293e46bc1340b87a52290   nat                 local
fe93466d138c        nat                                                                nat                 local
70d7f97915be        none                                                               null                local
````

**Comment by bospoort** [comment]
The factory reset didn't work for me. I uninstalled Docker and then reinstalled. There were still two networks named nat. After uninstall, I had to remove all folders named Docker or .docker from Program Files, ProgramData, my profile etc. Then reinstall, and I had only one network named nat. Uninstalling Docker seems to leave a lot behind. 
I'm also not sure if two nat networks is by design.

**Comment by TribeDataWorksJim** [comment]
I have tried factory reset, reinstalling (and tried to find all occurrences of the folders), but am still having this issue.

**Comment by dbreshears** [comment]
You might try this network cleanup script.   It has helped with similar issues in the past -> https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/master/windows-server-container-tools/CleanupContainerHostNetworking 

.\WindowsContainerNetworking-LoggingAndCleanupAide.ps1 -Cleanup

**Comment by bplasmeijer** [comment]
same here on (Version 18.05.0-ce-rc1-win63 (17439))
docker run --rm --platform linux busybox echo hello --network d9e5b31562b8
docker.exe: Error response from daemon: network nat is ambiguous (2 matches found on name).
docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
d9e5b31562b8        nat                 nat                 local
029ff73b534f        nat                 nat                 local
8b14c3c19549        none                null                local

**Comment by bplasmeijer** [comment]
reinstall and prune network didn't work for me

**Comment by andrehe001** [comment]
same for me with docker version 18.05.0-ce-rc1-win63 (17439). Any help or fixes in the queue?

**Comment by tbertenshaw** [comment]
same here with 18.03.1-ce-win65 (17513)

**Comment by fals** [comment]
I have the same problem:

Docker version 18.03.1-ce, build 9ee9f40

NETWORK ID          NAME                                       DRIVER              SCOPE
0aa6fcfc5fc9        bridge                                     bridge              local
225fbdbda06e        dockercompose7610429240741085608_default   bridge              local
1e6fca6d8459        dockercompose7610429240741085608_default   bridge              local
9784cadbee3a        host                                       host                local
7cf1551affda        none                                       null                local
2f20552ffff9        setup_default                              bridge              local

two defaults with the same name

**Comment by Fredoid** [comment]
Same probem with Docker version 18.03.1-ce, build 9ee9f40, Windows 10 and Windows Containers.
`docker network ls` shows 2 networks nat.

**Comment by Fredoid** [comment]
I've just found a solution in [this topic](https://social.msdn.microsoft.com/Forums/vstudio/en-US/a49c5cf8-b089-4421-bb12-ffa84f63a65c/docker-network-ls-is-showing-2-nat-networks?forum=windowscontainers) 

Simply run this following ps script to clean keys named "nat" and restart your computer.

```
$KeyPath = "HKLM:\SYSTEM\CurrentControlSet\Services\vmsmp\parameters\SwitchList"
$keys = get-childitem $KeyPath

foreach($key in $keys) {
	if($key.GetValue("FriendlyName") -eq 'nat')	{
		$newKeyPath = $KeyPath+"\"+$key.PSChildName
		Remove-Item -Path $newKeyPath -Recurse
	}
}

remove-netnat -Confirm:$false
```

Works on Windows 10 Pro with Docker version 18.03.0-ce-win59, build 0520e24302.

Thanks

**Comment by Fredoid** [comment]
Hi, Sometimes it is mentioned `Get-NetNat` PS function, but in my case this function always a return empty result. The script above worked nice twice.

I my case this problem appeared when I unstalled and re-installed Docker. Two times, and same issue on both case.

**Comment by dmitriykanarskiy** [comment]
Hi, i don't know which of this helped, but i've got rid of duplicate 'nat' networks as follows:

1. Stop service docker
2. Unregister service docker
3. Stop service `HNS`
4. Delete all instances of registry keys with the name of 'nat' network
5. Delete "`C:\ProgramData\Microsoft\Windows\HNS\HNS.data`"
6. Delete "`C:\ProgramData\docker\network\files\local-kv.db`"
7. Restart computer

Hope this will help.

**Comment by TribeDataWorksJim** [comment]
That finally fixed my issue. I believe it was step 5 or 6 that done it! Thanks!!!

**Comment by kpabich** [comment]
> > at finally fixed my issue. I believe it was step 5 or 6 that done it! Thanks!!!
> 
> Same here! My steps were
> 
> 1. Stop service docker
> 2. Stop service HNS
> 3. Delete "C:\ProgramData\Microsoft\Windows\HNS\HNS.data"
> 4. Delete "C:\ProgramData\docker\network\files\local-kv.db"
> 5. Start service HNS
> 6. Start docker
> 
> no pc restart required.

Worked for me!
Thank you.

**Comment by pritamhere** [comment]
> I've just found a solution in [this topic](https://social.msdn.microsoft.com/Forums/vstudio/en-US/a49c5cf8-b089-4421-bb12-ffa84f63a65c/docker-network-ls-is-showing-2-nat-networks?forum=windowscontainers)
> 
> Simply run this following ps script to clean keys named "nat" and restart your computer.
> 
> ```
> $KeyPath = "HKLM:\SYSTEM\CurrentControlSet\Services\vmsmp\parameters\SwitchList"
> $keys = get-childitem $KeyPath
> 
> foreach($key in $keys) {
> 	if($key.GetValue("FriendlyName") -eq 'nat')	{
> 		$newKeyPath = $KeyPath+"\"+$key.PSChildName
> 		Remove-Item -Path $newKeyPath -Recurse
> 	}
> }
> 
> remove-netnat -Confirm:$false
> ```
> Works on Windows 10 Pro with Docker version 18.03.0-ce-win59, build 0520e24302.
> 
> Thanks

tried this and it fixed my issue after restart. running on windows 10.

**Comment by philipktlin** [comment]
I have the same issue on a testing machine.  When running e2e tests, we will uninstall and install docker (moby) and this issue happens randomly.  I would like to ask, does anyone know what the root cause is.

**Comment by kvskranthikumar** [comment]
These steps worked for me on Windows 10 -

Delete "C:\ProgramData\Microsoft\Windows\HNS\HNS.data"
Delete "C:\ProgramData\docker\network\files\local-kv.db"

**Comment by stiko** [comment]
The way I solved this is by listing the networks
`docker network ls` as @Fredoid  mentioned you'll see a duplicated network as the error indicated,
then use the id of the network causing the error to remove it 
` docker network rm  NETWORK_ID`

**Comment by mail2hjain** [comment]
> > at finally fixed my issue. I believe it was step 5 or 6 that done it! Thanks!!!
> 
> Same here! My steps were
> 
> 1. Stop service docker
> 2. Stop service HNS
> 3. Delete "C:\ProgramData\Microsoft\Windows\HNS\HNS.data"
> 4. Delete "C:\ProgramData\docker\network\files\local-kv.db"
> 5. Start service HNS
> 6. Start docker
> 
> no pc restart required.

Worked for me as well. Thanks.

**Comment by quan-h-tran** [comment]
> > at finally fixed my issue. I believe it was step 5 or 6 that done it! Thanks!!!
> 
> Same here! My steps were
> 
> 1. Stop service docker
> 2. Stop service HNS
> 3. Delete "C:\ProgramData\Microsoft\Windows\HNS\HNS.data"
> 4. Delete "C:\ProgramData\docker\network\files\local-kv.db"
> 5. Start service HNS
> 6. Start docker
> 
> no pc restart required.

It's 2023 and this also a fixed for me

**Comment by fiveisprime** [comment]
Unfortunately, this is all done by Docker and not something we can control. The steps above resolve the issue, so I'd recommend following those and possibly reporting this to the Docker folks again.
