### ISSUE TITLE
Progress unknown when pulling images

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/DockerTools#90]
The docker CLI has a nice progress indicator when pulling images. The Visual Studio tools are missing this, which is especially noticeable when pulling big images. For example: the windows server images. This can take minutes, in which there is no visible progress.

**Comment by haniamr** [comment]
@nphmuller thanks for the feedback. There are 2 occasions when the tools will pull images:
- On project load if you have that enabled under tools -> options -> Container Tools
- When you debug/build the project

In the first case, there's a command window that will be minimized by default which is basically executing `docker pull {imageName}` and you can track the progress there or abort the download if you wish. If you're talking about the second case, then yes there is no progress indicator at the moment.

**Comment by nphmuller** [comment]
@haniamr Thanks! It's probably the 2nd case then, since I didn't see a command window,

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
