### ISSUE TITLE
Unable to start debugging on the web server

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/DockerTools#91]
This happens when I create a new ASP.NET Web Application in VS 15.6.4 with Docker Support enabled.

I get the following output when I start a debugging session (F5)

```
docker ps --filter "status=running" --filter "name=dockercompose8437191478683566452_webapplication5_" --format {{.ID}} -n 1
15fac122bde7
docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}" 15fac122bde7
172.20.184.210 
docker exec 15fac122bde7 cmd /c "C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.applicationHost/applicationPools /[name='DefaultAppPool'].processModel.identityType:LocalSystem /commit:apphost & C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/security/authentication/anonymousAuthentication /userName: /commit:apphost"
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
(At this point I sometimes get a dialog box with 'A remote operation is taking longer than expected.')
Applied configuration changes to section "system.webServer/security/authentication/anonymousAuthentication" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
(At this point I get a dialog box with: Unable to start debugging on the web server. The Visual Studio 2017 Remote Debugger (MSVSMON.EXE) does not appear to be running on the remote computer. This may be because a firewall is preventing communication to the remote computer. Please see Help for assistance on configuring remote debugging.)
```

docker version output:
```
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24
 Built: Wed Mar 21 23:06:28 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.03.0-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.4
  Git commit:   0520e24
  Built:        Wed Mar 21 23:21:06 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

**Comment by nphmuller** [comment]
This always happens when adding Docker support for Windows. So it doesn't matter if the project targets .NET Full or .NET Core. No problem when using Linux containers.

**Comment by nphmuller** [comment]
I also tried deleting the folders mentioned [here](https://docs.microsoft.com/en-us/azure/vs-azure-tools-docker-troubleshooting-docker-errors#unable-to-start-debugging) which didn't help.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please re-open with any additional context for our consideration, we are happy to take a look!

**Comment by chetanchougle** [comment]
@nphmuller   Yes i can confirm the same issue on VS 2017 . The containers and images get created but are unable to attach for debugging i tried to restart the Ethernet Nat but no use.

**Comment by spottedmahn** [comment]
Looks like the [same issue here in Dev Community](https://developercommunity.visualstudio.com/content/problem/223526/unable-to-start-debugging-for-docker-project-that.html), FYI.

**Comment by Tschrock** [comment]
I'm also having this issue when trying to debug any project in Docker

Even using "Start without Debugging", I can't get the web app to load in the browser - which makes me think it might be a Docker/Networking issue?

![devenv_2019-06-07_16-45-20](https://user-images.githubusercontent.com/2406499/59132611-ae347b80-8943-11e9-87ad-e787d35b67f8.png)

![devenv_2019-06-07_16-07-40](https://user-images.githubusercontent.com/2406499/59131309-0a959c00-8940-11e9-9431-f465fa4be790.png)

Things I've tried:
- Resetting Windows using the "Reset this PC" feature
- Reinstalling Visual Studio
- Reinstalling Docker For Windows
- Deleting `%userprofile%\onecoremsvsmon` (https://docs.microsoft.com/en-us/visualstudio/containers/troubleshooting-docker-errors?view=vs-2019#unable-to-start-debugging)
- Running the `CleanupContainerHostNetworking` powsershell script (https://docs.microsoft.com/en-us/visualstudio/containers/troubleshooting-docker-errors?view=vs-2019#errors-specific-to-networking-when-debugging-your-application)

Environment:

Windows 10 Pro (1903)
Visual Studio Community 2019 (16.1.2)

<details>
<summary>Docker Version</summary>

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false
```

</details>

<details>
<summary>Container Tools output in VS</summary>

```
========== Checking for Container Prerequisites ==========
Verifying that Docker Desktop is installed...
Docker Desktop is installed.
========== Verifying that Docker Desktop is running... ==========
Verifying that Docker Desktop is running...
Docker Desktop is running.
========== Verifying Docker OS ==========
Verifying that Docker Desktop's operating system mode matches the project's target operating system...
Switching Docker to use Windows containers...
C:\Program Files\Docker\Docker\DockerCli.exe -SwitchDaemon
Docker is now using Windows containers.
Docker Desktop's operating system mode matches the project's target operating system.
========== Pulling Required Images ==========
Checking for missing Docker images...
Pulling missing Docker images. To cancel this download, close the command prompt window.
docker pull mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
Docker pull completed.
Docker images are ready.
========== Warming up container(s) for RockWeb ==========
Starting up container(s)...
docker build -f "C:\Users\tschrock\source\repos\Rock\RockWeb\Dockerfile" -t rockwebapp:dev --build-arg "source=obj\Docker\empty" --label "com.microsoft.created-by=visual-studio" --label "com.microsoft.visual-studio.project-name=RockWeb" "C:\Users\tschrock\source\repos\Rock\RockWeb" 
Sending build context to Docker daemon  3.584kB

Step 1/6 : FROM mcr.microsoft.com/dotnet/framework/aspnet:4.7.2-windowsservercore-ltsc2019
 ---> 792abef31b89
Step 2/6 : ARG source
 ---> Running in 35034709e74b
Removing intermediate container 35034709e74b
 ---> ef32ce7e0b50
Step 3/6 : WORKDIR /inetpub/wwwroot
 ---> Running in 0475f95abe12
Removing intermediate container 0475f95abe12
 ---> 83a384c04e1a
Step 4/6 : COPY ${source:-obj/Docker/publish} .
 ---> 4bfef84e7a69
Step 5/6 : LABEL com.microsoft.created-by=visual-studio
 ---> Running in e6655db695ac
Removing intermediate container e6655db695ac
 ---> b02a950feaa2
Step 6/6 : LABEL com.microsoft.visual-studio.project-name=RockWeb
 ---> Running in 089b8eb860f6
Removing intermediate container 089b8eb860f6
 ---> 5f09bb622c2c
Successfully built 5f09bb622c2c
Successfully tagged rockwebapp:dev
docker run -dt -v "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Remote Debugger:C:\remote_debugger:ro" -v "C:\Users\tschrock\source\repos\Rock\RockWeb:C:\inetpub\wwwroot" -e "DEV_ENVIRONMENT=1" -e "VBCSCOMPILER_TTL=604800" -P --entrypoint cmd rockwebapp:dev /c "start /B C:\ServiceMonitor.exe w3svc & C:\remote_debugger\x64\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /fallbackloadremotemanagedpdbs /timeout:2147483646" 
2ff180ab9ea1e86661e785a7dfb4bf2592e690b5e3a7c5e42ba69a2af7c2f829
docker exec 2ff180ab9ea1e86661e785a7dfb4bf2592e690b5e3a7c5e42ba69a2af7c2f829 cmd /c "C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.applicationHost/applicationPools /[name='DefaultAppPool'].processModel.identityType:LocalSystem /commit:apphost & C:\Windows\System32\inetsrv\appcmd.exe set config -section:system.webServer/security/authentication/anonymousAuthentication /userName: /commit:apphost"
Applied configuration changes to section "system.applicationHost/applicationPools" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
Applied configuration changes to section "system.webServer/security/authentication/anonymousAuthentication" for "MACHINE/WEBROOT/APPHOST" at configuration commit path "MACHINE/WEBROOT/APPHOST"
Trying to connect to 172.18.221.129 for debugging
Trying to connect to 172.18.221.129 for debugging
Trying to connect to 172.18.221.129 for debugging
Trying to connect to 172.18.221.129 for debugging
Trying to connect to 172.18.221.129 for debugging
Trying to connect to 172.18.221.129 for debugging
Container started successfully.
========== Finished ==========
```

</details>

**Comment by sgreenmsft** [comment]
@Tschrock - This sounds like it might be a known issue in Win10 19H1 with Windows container networking.  If so, there are some steps to work around the problem:
1)	Remove all containers (run “docker rm -f” until “docker ps -a” shows nothing)
2)	In PowerShell, run this command to remove the network used by Docker:
Get-hnsnetwork | remove-hnsnetwork
3)	In PowerShell, run this command to restart the docker service, which will recreate the network:
Restart-service docker

Could you give that a shot and see if it resolves the issue?

**Comment by blakeholl** [comment]
> @Tschrock - This sounds like it might be a known issue in Win10 19H1 with Windows container networking. If so, there are some steps to work around the problem:
> 
> 1. Remove all containers (run “docker rm -f” until “docker ps -a” shows nothing)
> 2. In PowerShell, run this command to remove the network used by Docker:
>    Get-hnsnetwork | remove-hnsnetwork
> 3. In PowerShell, run this command to restart the docker service, which will recreate the network:
>    Restart-service docker
> 
> Could you give that a shot and see if it resolves the issue?

I had the same symptoms as @Tschrock, and this resolved my problems.

**Comment by Tschrock** [comment]
That did indeed resolve my issue, thanks so much!

**Comment by bwateratmsft** [comment]
Glad it working! The Windows team has created and released an update to fix this networking issue, but unfortunately those that upgraded to 19H1 before this update was released were not automatically fixed upon installing the update.

**Comment by vselale** [comment]
I got he same issue after docker update. I notice the network card of virtual machine was removed. When I add the card it become to work.

![image](https://user-images.githubusercontent.com/47344945/93320467-ccad4600-f819-11ea-8937-592b13b9ee35.png)

**Comment by nilavanrajamani** [comment]
![image](https://user-images.githubusercontent.com/17172648/101035124-abe6c800-35a0-11eb-8b55-d2bbe0203288.png)

Try sharing remote debugger volume from host to the container. Also try setting configuration/system.web/compilation[debug='true'] in web.config

**Comment by nilavanrajamani** [comment]
Also try setting the entrypoint in compose file as below
![image](https://user-images.githubusercontent.com/17172648/101037663-5ced6280-35a1-11eb-994d-1ec154dbb32f.png)
