### ISSUE TITLE
When debugging netcoreapp2.1 with docker support, VS does not stop on breakpoints

### ISSUE THREAD

**Issue by dmaksim** [Microsoft/DockerTools#92]
Hello,

**Scenario / repro steps:**
1. In VS 15.7.0 Preview 2 -> create a new project -> ASP.NET Core 2.1 -> enable docker support (linux)
2. In the Dockerfile, replace default generated image names with:
`FROM microsoft/aspnetcore:2.1.0-preview1 AS base`
`FROM microsoft/aspnetcore-build:2.1.300-preview1 AS build`
3. Place a breakpoint in code, e.g. in Startup.cs -> `await context.Response.WriteAsync("Hello World!");`
4. Hit F5 to start debugging

**Expected result:**
The breakpoint is being hit.

**Actual result:**
The breakpoint is not hit. Visual Studio says:
> The breakpoint will not currently be hit. No symbols have been loaded for this document. Location: Startup.cs.

Which is strange, because .pdb file is right next to the .dll, just like in every normal default project :)

The exact same scenario **works** with ASP.NET Core 2.0 app with microsoft/aspnetcore:2.0 docker images.
The exact same scenario **does not work** with ASP.NET Core 2.0 app with 2.1 docker images.
I believe VS version doesn't have to do anything with this problem.

**By the way:**
The image names in generated Dockerfile in a new project are not valid and non existant. That's why I have to perform step 2 above.
Dockerfile is generated with `microsoft/aspnetcore:2.1` and `microsoft/aspnetcore-build:2.1`. When I click F5, I have this message in Output window:
> ========== Pulling Images ==========
Pulling missing Docker images.
docker pull microsoft/aspnetcore:2.1
docker pull failed

Any info would be appreciated. Thanks very much.

**Comment by dmaksim** [comment]
I've made some progress.

I've managed to get the web app (.net core 2.1 preview 2) to debug correctly. Specifically, I installed `libunwind8` package on the `microsoft/dotnet:2.1-aspnetcore-runtime` image. I've noticed that this package is missing from `microsoft/dotnet:2.1-***` docker images (comparing to 2.0 images), and it turns out that this is required for the debugger to attach correctly to the docker container.

So the **correct working `Dockerfile` fragment** at the beginning looks like this:

    FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
    WORKDIR /app
    EXPOSE 60927 44368
    RUN apt-get update \
        && apt-get install -y --no-install-recommends libunwind8 \
        && rm -rf /var/lib/apt/lists/*
    # the rest...

Now, I still failed to debug when using Alpine image `microsoft/dotnet:2.1-aspnetcore-runtime-alpine`. From [this packages mapping table](https://github.com/dotnet/core/issues/226) I see that on Alpine there is a `libunwind` package (notice the lack of '8' at the end). But when I add it to the Dockerfile, debugger still fails to attach (error: "Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))")

So, **this `Dockerfile` fragment still doesn't work**:

    FROM microsoft/dotnet:2.1-aspnetcore-runtime-alpine AS base
    WORKDIR /app
    EXPOSE 60927 44368
    RUN apk update \
        && apk -X https://dl-cdn.alpinelinux.org/alpine/edge/main add --no-cache libunwind
    # the rest...

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
