### ISSUE TITLE
.Net Framework ASPNet Core Application Errors

### ISSUE THREAD

**Issue by mikebollandajw** [Microsoft/DockerTools#94]
When attempting to create a docker enabled project which is using .Net Framework and ASPNet core the dockerfile generated is invalid and an error is throwing when attempting to run the project

Error		Value cannot be null. Parameter name: stream	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	294	

See how to reproduce below

![ezgif-5-1cd6a24df7](https://user-images.githubusercontent.com/38316056/38670510-e3d69a10-3e40-11e8-9396-6398c66024b6.gif)

**Comment by haniamr** [comment]
@mikebollandajw thanks for reporting. This scenario where you target .net framework in an ASP.NET Core Web app is not supported (i.e. not containerizeable), may I ask what's your VS version? We blocked that from the UI if you have the latest 15.7.

**Comment by mikebollandajw** [comment]
hi yes this doesnt seem to be an option any more!

**Comment by andreujuanc** [comment]
Looks like .Net is getting fragmented.. Just got this issue today.
