### ISSUE TITLE
.NET Core Docker enabled project doesn't work with the 2.1-preview2 images

### ISSUE THREAD

**Issue by MichaelSimons** [Microsoft/DockerTools#95]
**Repo Steps**
1. Create a new  `ASP.NET Core Web Application`
1. Choose  ` Web Application` and `Enable Docker Support`
1. Navigate to the generated Dockerfile and change the .NET base images to use the 2.1-preview2 images.
    1. `FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base`
    1. `FROM microsoft/dotnet:2.1-sdk AS build`
1. F5

**Actual Results**
![image](https://user-images.githubusercontent.com/8290530/38939363-61851c92-42ed-11e8-858d-12f410386fcd.png)

**Expected Results**
Web application should launch with the debugger attached

**Workaround**
Change the `base` stage in the Dockerfile to the following:

```
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		libcurl3 \
		libunwind8 \
		libuuid1 \
	&& rm -rf /var/lib/apt/lists/*
WORKDIR /app
EXPOSE 80
```

**Comment by dbreshears** [comment]
There is a vsdbg fix that is needed to fix debugging on 2.1 images.   The updates are in testing and should be available in the next few days I would think.
