### ISSUE TITLE
Template Dockerfiles should use more specific tags

### ISSUE THREAD

**Issue by mjrousos** [Microsoft/DockerTools#96]
Creating a new ASP.NET Core 2.0 MVC project and adding Windows Docker support produces a Dockerfile with microsoft/aspnetcore:2.0-nanoserver-1709 as its base image

```
FROM microsoft/aspnetcore:2.0-nanoserver-1709 
```

The problem is that the image the 2.0-nanoserver-1709 tag refers to changes over time as new 2.0 updates are released. In my case, a new project wouldn't run because I had an older 2.0-nanoserver-1709 image on my dev machine that didn't include 2.0.5+ ASP.NET Core stores. Running `docker pull microsoft/aspnetcore:2.0-nanoserver-1709` fixed the issue, but it wasn't immediately obvious why the container wasn't working (aspnet/aspnet-docker#412).

The templates should use more specific base image versions (microsoft/aspnetcore:2.0.7-nanoserver-1709) to avoid this problem.

**Comment by bwateratmsft** [comment]
This issue is being closed as an inactive issue. If you wish to keep it active, please let us know, we are happy to take a look!
