### ISSUE TITLE
--no-cache (docker-compose)

### ISSUE THREAD

**Issue by dazinator** [Microsoft/DockerTools#97]
When docker-compose is invoked, how can we pass additional arguments like  `--no-cache` ? I just got burned because I amended a powershell script that is run as part of a docker build. After cleaning the solution and running the docker project again - docker compose built the docker file and brought it up - but it used the previously cached layer for that powershell RUN step meaning my changes to that script didn't take effect.

**Comment by haniamr** [comment]
I'm afraid there's no straightforward way to achieve this at the moment. You can override the build task responsible for calling `docker-compose build` which is non-trivial but can be done. Here's an example: https://github.com/Microsoft/DockerTools/issues/46. Hope this helps!

**Comment by dazinator** [comment]
> I'm afraid there's no straightforward way to achieve this at the moment.

Ok thanks for the reply.
Please consider making this straightforward in the future! It's easier for me to run `docker-compose` manually from the command line and bypass the dockertools projects system completely, than it is for me to create  override the custom build task :-)

**Comment by haniamr** [comment]
Surely, thanks for the feedback. We will certainly take that under consideration.
